### ISSUE TITLE
Jenkins-master in docker container

### ISSUE THREAD

**Issue by wharfedale01** [jenkinsci/mesos-plugin#100]
I'm running a mesos-cluster and a jenkins-master on a separate server in a docker container.
I've used the official jenkins image from docker hub and installed the mesos-plugin. 
The jenkins-framework is terminated and not registered on the mesos-cluster.

```
I0420 17:26:38.397886  7869 master.cpp:3625] Framework failover timeout, removing framework 20150415-183002-1784283914-5050-7846-0235 (Jenkins Scheduler) at scheduler-1aa187ec-a93f-49c3-97bb-6d62b4352598@172.17.0.39:50222
I0420 17:26:38.397925  7869 master.cpp:4183] Removing framework 20150415-183002-1784283914-5050-7846-0235 (Jenkins Scheduler) at scheduler-1aa187ec-a93f-49c3-97bb-6d62b4352598@172.17.0.39:50222
I0420 17:26:38.398061  7869 hierarchical.hpp:354] Removed framework 20150415-183002-1784283914-5050-7846-0235
```

172.17.0.39 is the ip addres of the container. How do i change this ip address to the ip of the host?
Port 8080 and 50000 is mapped to the docker host. Is this enough?
I probably need to map the ports like 50222 in the example to my host. How do i accomplish this?

**Comment by geoffroyjabouley** [comment]
Hello

can you try starting your docker container using "--net=host" options? By doing this your container has the same IP address than the host.

Maybe this solution is not suitable for your purpose, but at least try it so if framework is able to correctly register then you will know this is a docker configuration issue and not a jenkins-mesos plugin issue.

Regards
