### ISSUE TITLE
Using docker as jenkins slave

### ISSUE THREAD

**Issue by wharfedale01** [jenkinsci/mesos-plugin#103]
I'm currently trying to use docker containers as jenkins slaves in a mesos cluster.
In this docker containers i build docker containers.
I use this image tehranian/dind-jenkins-slave and added the --privileged parameter.

The image uses CMD to run wrapdocker.sh but the mesos plugin overwrites it to "java -DHUDSON_HOME=jenkins..."

How do i add the wrapdocker script to execute on startup? Or should I use another image or something?
I'm using Centos 7, Jenkins 1.596.2 and mesos 0.22 btw.

Anyone running docker containers as jenkins slaves in a mesos cluster?

**Comment by maselvaraj** [comment]
Did you mean you want to use a custom workspace directory for the Jenkins slave?

**Comment by wharfedale01** [comment]
i fixed it by running the script as a task, not ideal i think but i works.
