### ISSUE TITLE
docker  image

### ISSUE THREAD

**Issue by suchisubhra** [jenkinsci/mesos-plugin#104]
I have docker  image which  is running a jenkins.Then  I added  mesos plugins.
It is just  keep registering and unregistering itself..

ID  Host    User    Name    Registered  Unregistered
…5050-4285-1889
    142e2d55fc61    root    MyJenkins   2 minutes ago   a minute ago
…5050-4285-1888
    142e2d55fc61    root    MyJenkins   3 minutes ago   2 minutes ago
…5050-4285-1887
    142e2d55fc61    root    MyJenkins   5 minutes ago   4 minutes ago

Also I check it is asking for high  cpu  and memory

ID  Host    User    Name    Active Tasks    CPUs    Mem     Max Share   Registered  Re-Registered…5050-4285-1891142e2d55fc61  root    MyJenkins   0   11.5    36.1 GB     97.308%     just now    -

Has anybody  able to  run jenkins docker with  mesos plugin...any help really  appreciated

**Comment by ederst** [comment]
There could be various (network related) reasons for this:
* Jenkins can connect to the Mesos hosts but not vice versa. Check this by pinging the IP of the Jenkins host from your Mesos hosts.
* The hostname of Jenkins resolves to 127.0.0.1, so the Mesos hosts try to connect to 127.0.0.1. Actually this is kind of weird, because you have to modify the `/etc/hosts` (or DNS resolution) on the Jenkins host to fix this. Jenkins sends the resolved IP and the hostname to the Mesos cluster. Therefore, put something like `<IPOfDockerContainer> <YourJenkinsHostname>` in the `/etc/hosts` of the Jenkins host.

**Comment by h0tbird** [comment]
@suchisubhra I had the same problem (#108) and I fixed it by using host networking mode in my Jenkins container.

**Comment by suchisubhra** [comment]
i  tried that..  No luck.. After I configure mesos plugin and press save button, jenkins crashed and marathon starts new container. So old jenkins is gone.
Looking at  docker log I see this

time="2015-05-26T21:44:32Z" level="info" msg="-job execStart(1e1bdfcd9f12a8689578ce2d6ddbb288b2c6cbda6a6c6d1491e109cf18e7471d) = OK (0)"
2015/05/26 21:44:32 http: response.WriteHeader on hijacked connection
time="2015-05-26T21:44:32Z" level="info" msg="+job log(oom, 4a685255d1e106f7a00f8056cc52bbd4811f27a3a83ee2158f2807db9adce2e1, artifactory.adskengineer.net/jenkins-mesos:dev)"
time="2015-05-26T21:44:32Z" level="info" msg="-job log(oom, 4a685255d1e106f7a00f8056cc52bbd4811f27a3a83ee2158f2807db9adce2e1, artifactory.adskengineer.net/jenkins-mesos:dev) = OK (0)"
time="2015-05-26T21:44:32Z" level="info" msg="+job log(die, 4a685255d1e106f7a00f8056cc52bbd4811f27a3a83ee2158f2807db9adce2e1, artifactory.adskengineer.net/jenkins-mesos:dev)"
time="2015-05-26T21:44:32Z" level="info" msg="-job log(die, 4a685255d1e106f7a00f8056cc52bbd4811f27a3a83ee2158f2807db9adce2e1, artifactory.adskengineer.net/jenkins-mesos:dev) = OK (0)"
time="2015-05-26T21:44:32Z" level="info" msg="-job logs(mesos-f1ba315a-40a6-4c98-a0a4-1ccfb77a5148) = OK (0)"
time="2015-05-26T21:44:32Z" level="info" msg="-job attach(4a685255d1e1) = OK (0)"
time="2015-05-26T21:44:32Z" level="info" msg="-job wait(mesos-f1ba315a-40a6-4c98-a0a4-1ccfb77a5148) = OK (0)"
time="2015-05-26T21:44:32Z" level="info" msg="-job wait(mesos-f1ba315a-40a6-4c98-a0a4-1ccfb77a5148) = OK (0)"
time="2015-05-26T21:44:32Z" level="info" msg="POST /v1.17/containers/mesos-f1ba315a-40a6-4c98-a0a4-1ccfb77a5148/stop?t=0"
time="2015-05-26T21:44:32Z" level="info" msg="+job stop(mesos-f1ba315a-40a6-4c98-a0a4-1ccfb77a5148)"
Container already stopped
time="2015-05-26T21:44:32Z" level="info" msg="-job stop(mesos-f1ba315a-40a6-4c98-a0a4-1ccfb77a5148) = ERR (1)"
time="2015-05-26T21:44:39Z" level="info" msg="GET /v1.17/containers/artifactory.adskengineer.net/jenkins-mesos:dev/json"
time="2015-05-26T21:44:39Z" level="info" msg="+job container_inspect(artifactory.adskengineer.net/jenkins-mesos:dev)"
No such container: artifactory.adskengineer.net/jenkins-mesos:dev
time="2015-05-26T21:44:39Z" level="info" msg="-job container_inspect(artifactory.adskengineer.net/jenkins-mesos:dev) = ERR (1)"
time="2015-05-26T21:44:39Z" level="error" msg="Handler for GET /containers/{name:.*}/json returned error: No such container: artifactory.adskengineer.net/jenkins-mesos:dev"
time="2015-05-26T21:44:39Z" level="error" msg="HTTP Error: statusCode=404 No such container: artifactory.adskengineer.net/jenkins-mesos:dev"
time="2015-05-26T21:44:39Z" level="info" msg="GET /v1.17/images/artifactory.adskengineer.net/jenkins-mesos:dev/json"
time="2015-05-26T21:44:39Z" level="info" msg="+job image_inspect(artifactory.adskengineer.net/jenkins-mesos:dev)"
time="2015-05-26T21:44:39Z" level="info" msg="-job image_inspect(artifactory.adskengineer.net/jenkins-mesos:dev) = OK (0)"
time="2015-05-26T21:44:39Z" level="info" msg="POST /v1.17/containers/create?name=mesos-c7bb8775-da6e-42cf-ad1c-7d1f2dd0cfef"
time="2015-05-26T21:44:39Z" level="info" msg="+job create(mesos-c7bb8775-da6e-42cf-ad1c-7d1f2dd0cfef)"
time="2015-05-26T21:44:39Z" level="info" msg="+job log(create, a85685d43da8c0e1f89b6c033efa9ceb1632cb26ea8639a0de3c234e26ed0fcd, artifactory.adskengineer.net/jenkins-mesos:dev)"
time="2015-05-26T21:44:39Z" level="info" msg="-job log(create, a85685d43da8c0e1f89b6c033efa9ceb1632cb26ea8639a0de3c234e26ed0fcd, artifactory.adskengineer.net/jenkins-mesos:dev) = OK (0)"


so  looks like it is OOM error.  I gave 3gb memory

**Comment by jeschkies** [comment]
@suchisubhra, is this still an issue with the newest version?

**Comment by jeschkies** [comment]
Closing for lack of response.
