### ISSUE TITLE
NullPointerException on 0.7.0

### ISSUE THREAD

**Issue by bacoboy** [jenkinsci/mesos-plugin#113]
INFO: MesosCloud provisioning successfully completed. We have now 8 computer(s)
    java.lang.NullPointerException
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.matches(JenkinsScheduler.java:325)
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.resourceOffers(JenkinsScheduler.java:252)
    Jun 02, 2015 1:24:35 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run  
    SEVERE: The Mesos driver was aborted! Status code: 3

Line 325 on the scheduler is this line:

      String requestedPorts = StringUtils.join(request.request.slaveInfo.getContainerInfo().getPortMappings().toArray(), "/");

Seems like we need some null/undefined guards here....  Since this was an upgrade, the port mappings probably hasn't been defined yet.  Perhaps this would be fixed if I just go re-save the configuration as a workaround.  But I wanted to make sure this got documented for others with this issue

**Comment by bacoboy** [comment]
OK I verified that saving the configuration does NOT provide a workaround.  0.7.0 seems outright broken.  Can anybody else verify this?

**Comment by bacoboy** [comment]
The build off commit id aa7ba53ac2072734cefd239ba0dc64b4f53bad9c works fine.

**Comment by geoffroyjabouley** [comment]
Hello
i think this is the same error as https://github.com/jenkinsci/mesos-plugin/issues/111
can you confirm it?

**Comment by bacoboy** [comment]
I know https://github.com/jenkinsci/mesos-plugin/commit/aa7ba53ac2072734cefd239ba0dc64b4f53bad9c is included in 0.7.0.  I referenced it as the last known working version to highlight the breakage introduced in commit 8805f0a5c76498d0e60a8375182a8b4891a11db0

I believe this is the same issue.  Once this is triggered, the Scheduler aborts and you have to restart jenkins to fix.  

0.7.0 should be pulled and patched quickly IMHO since most people already using this plugin will NOT be using the port mapping stuff.
