### ISSUE TITLE
jobs fail if 'Additional Jenkins Slave Agent JNLP arguments' is blank

### ISSUE THREAD

**Issue by bhepple** [jenkinsci/mesos-plugin#122]
I found this in 0.6.0 but may be in 0.7.0

If 'Additional Jenkins Slave Agent JNLP arguments' is left blank then slave.jar throws a an error annotated with 'No argument is allowed: null' 

Tracing back through the code it appears that it's trying to dereference a null string where it should be putting the slave agent JNLP arguments.

Presumably putting a blank there would fix the problem. My solution was to add -noCertificateCheck there (which I needed anyway).

**Comment by rasputnik** [comment]
I add -noReconnect there to prevent "jenkins.slaves.restarter.JnlpSlaveRestarterInstaller" stack traces when tasks exit. 

I don't know if that should be there by default (only started using this today)? If so it'd fix your issue too :)
