### ISSUE TITLE
During the offer process is Jenkins label information available

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#139]
I have a number of mesos slaves that have different labels -- they all end up in the same queue. How do I have one slave pool with multiple or single frameworks that use the correct node.  It appears that anything in the queue that meets the physical requirements is used.  The physical requirements being memory and cpu ...

**Comment by maselvaraj** [comment]
I have a number of mesos slaves that have different labels - Did you mean mesos slaves with different attributes ? If yes, you can use 'Mesos Offer Selection Attributes' to differentiate them. 
![screen shot 2015-06-28 at 6 24 31 pm](https://cloud.githubusercontent.com/assets/6958022/8396446/3090c228-1dc3-11e5-917c-deb722ae4540.png)

**Comment by digitalrinaldo** [comment]
Sorry I am being  so dense here.  Suppose i have 5 types of slaves and I want to share them with several jenkins instances -- what is a good way to do it.

Can I create one list of slave clients for mesos and still use the jenkins label approach?

**Comment by maselvaraj** [comment]
Yes. Once you have a mesos cluster, you can configure and share it with several Jenkins instances. 

Label is to differentiate slave requirements for Jenkins job. For ex: Jenkins job which might require lot of compute can be labelled as heavy_node with more CPU, MEM etc.  Corresponding heavy_node in label in Mesos plugin configuration should be configured the resource requirement.

**Comment by geoffroyjabouley** [comment]
Something a bit painfull is sharing the same configuration between jenkins
instances.

It would have been great if Cloud definitions were not stored in the main
conffig.xml file of Jenkins, but rather in a dedicated xml file.

This would be much easier to share Mesos cloud definition accross masters,
and to maintain/update it (using git for example). Today we have to alter
the big xml file to add new Mesos slaves definitions.

But it is a Jenkins core choice, so we have to deal with it

2015-07-06 5:47 GMT+02:00 Manivannan Selvaraj <notifications@github.com>:

**Comment by digitalrinaldo** [comment]
Eventually the jenkins community realized that a big config.xml file was bad for sharing nodes and they have the nodes in a seperate file now.  Maybe soon they will do it for clouds in the typical jenkins way one small thing instead of making the entire config.xml file composable from smaller files or a single include file.   There aren't enough hours in the day to fix all the broken software. :)

**Comment by digitalrinaldo** [comment]
I am still very confused on how to do the following.   I have some linux nodes and mac nodes, ( mesos-slaves)   I want to send some jobs to the macs and some jobs to the linux nodes.  How do I configure this with the mesos-plugin?

**Comment by vinodkone** [comment]
When you start mesos slave daemons on those nodes, set their "attributes" appropriately (e.g., "os:linux" and "os:mac"). In the plugin you should be able to launch jenkins slaves based on specific mesos slaves via attributes.

**Comment by digitalrinaldo** [comment]
I have done the following.

start a slave with --attributes="jenkins:big"

When I try to add the above to mesos offer attributes for the label in the mesos configuration screen it never keeps the value. In other words I enter "jenkins:big" and it gets accepted but next time the plugin displays it is blank.

there is no help on this item either.

I have two types of slaves jbig and small and I want to use different ones with labels so I have two slaves defined in Jenkins.

**Comment by rasputnik** [comment]
The label is to categorize the particular (plugin) slave info settings so jobs can be launched on them.

slave is overridden here and that's confusing. as far as i can make out.

1 mesos cloud has multiple 'slave info' subentries (definition of how mesos tasks will be launched to run the jenkins slave). each 'slave info' entry can have a label so you can restrict builds to only run on that task config.

Within the settings for that slave info entry, you can request mesos attributes to filter which _mesos_ slave you want those tasks to be launched on (the 'Mesos Offer Selection Attributes' field).

**Comment by digitalrinaldo** [comment]
Belated thanks but this is working well for us.
