### ISSUE TITLE
Support Scheduler HA

### ISSUE THREAD

**Issue by adam-mesos** [jenkinsci/mesos-plugin#147]
The Jenkins scheduler should persist its frameworkId so that it can reregister under the same frameworkId on failover and reconnect to its running tasks. Also need to set failover_timeout to a sufficient duration.

**Comment by elingg** [comment]
+1

**Comment by christianparpart** [comment]
+1

**Comment by ayoubboulila** [comment]
+1

**Comment by jeschkies** [comment]
The new 2.0 persists the framework id. The failover timeout can be set via `-Dusi.jenkins.failover-timeout` Java property.
