### ISSUE TITLE
Mesos Task keep running while jenkins node is cleaned

### ISSUE THREAD

**Issue by hfufu** [jenkinsci/mesos-plugin#149]
As reported by others, i'm too facing NPE problem in 0.7 so is using 0.8 snapshot too.

I've tried submit 2 jenkins job that run on different mesos slave node label. The mesos slave is configured have just enough resource to run 1 job instance, so the second job will need to wait for the first jenkins node to go offline before it can start up another node with different node label to run. 

The problem is: the first jenkins node will goes offline, but the corresponding mesos task will not be Killed. So the framework will not have enough resource for starting next jenkins node. 

I'm using external containerizer.

To make the long story short, the root cause of the problem is the driver in JenkinsScheduler is null because driver.run() was aborted by some exception.  The exception is caused by containerInfo.getPortmappings() call.

Exception in thread "Thread-37" java.lang.NullPointerException
  at org.jenkinsci.plugins.mesos.JenkinsScheduler.matches(JenkinsScheduler.java:370)
  at org.jenkinsci.plugins.mesos.JenkinsScheduler.resourceOffers(JenkinsScheduler.java:292)
I0707 20:15:30.397056  6124 sched.cpp:1320] Asked to abort the driver
I0707 20:15:30.397146  6124 sched.cpp:777] Aborting framework '20150707-160107-1113862922-5050-32551-0015'
Jul 07, 2015 8:15:30 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
SEVERE: The Mesos driver was aborted! Status code: 3

Doing a simple null check on getPortmappings() fix my problem: https://github.com/hfufu/mesos-plugin/commit/d9494ddb809a058010d6e96f52d7da5d91a053ff

 The requestPorts string is for logging purpose only so the diff should do no harm right?

**Comment by geoffroyjabouley** [comment]
Hello

can you have a look at my comment here: https://github.com/jenkinsci/mesos-plugin/issues/111#issuecomment-108481811

Are the xml fields available in your Jenkins config.xml file?

If not, try to add them and then use the 0.8.0-SNAPSHOT version without your commit hfufu@d9494dd, see if it fixes the issue.

**Comment by hfufu** [comment]
Thanks for your response. I can see the config.xml is trying to make a empty portmappings list instead of return null. 

However, my jenkins setup is using external containerizer instead of docker containerizer. The portmappings field is for docker containerizer only and does not appear under external containerizer.
