### ISSUE TITLE
Jenkins workflow plugin and mesos-plugin

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#151]
The jenkins workflow plugin has many advantages over the previous approaches.  I did not see the mesos plugin listed as working with workflow.

https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md

**Comment by maselvaraj** [comment]
Have you tried using workflow plugin with Mesos plugin ? What is the issue that you are seeing ?

**Comment by geoffroyjabouley** [comment]
Hello

i think it should work fine, as mesos plugin is not directly "called" when you define a workflow job.

In the node syntax, just set a valid Mesos slave label to execute the step:
```
node('mesos_slave_label') {
    // as before
}
```

Can you give us some feedback when you have done some tests?

**Comment by digitalrinaldo** [comment]
I have tested a number of configurations of the workflow plugin with the mesos plugin and I am pleased to report that many of the cases work.  I have been filing some issues in the google group about some of the issues. One of the major issues is that jenkins supports labels that can have many different labels like  this    linuxnode || macnode || windowsnode -- the mesos plugin doesn't iterate over all the labels it uses the first one only and asks for that node. I don't know that I have a solution to this.

**Comment by digitalrinaldo** [comment]
Don't make the same mistake I made labels with spaces in them work very well with the mesos jenkins driver. We have been using the driver off and on and works for most of our use cases.
