### ISSUE TITLE
Mesos slave cleanup process is verbose

### ISSUE THREAD

**Issue by geoffroyjabouley** [jenkinsci/mesos-plugin#152]
Every minute, the following lines are printed in the jenkins log:

```
Jul 09, 2015 11:37:45 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Mesos pending deletion slave cleanup
Jul 09, 2015 11:37:45 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Mesos pending deletion slave cleanup. 0 ms
```

It is not possible to filter it because it comes from the common class hudson.model.AsyncPeriodicWork, which may be also used for other matters...

**Comment by geoffroyjabouley** [comment]
Maybe the problem is that the mesos deletion slave cleanup thread is always running, even when "on demand registration" is activated.
For example, i have started a new Jenkins instance yesterday. It did not execute any build yet, but still i already have a 1MB log filled with the slave cleanup traces.

**Comment by tangicolin** [comment]
Maybe, as in Jcloud Plugins do, in the function getRecurrencePeriod() (https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/java/org/jenkinsci/plugins/mesos/MesosCleanupThread.java#L55) the value should be increase to MIN*5

**Comment by jeschkies** [comment]
@geoffroyjabouley, do you see the same behaviour with 1.0 or 2.0?

**Comment by gjabouley-invn** [comment]
Hi, don't know as i don't use Mesos plugin anymore

**Comment by jeschkies** [comment]
What are you using instead, if you don't mind me asking.
