### ISSUE TITLE
plugin not registering...?

### ISSUE THREAD

**Issue by tony-kerz** [jenkinsci/mesos-plugin#156]
so, trying to get this setup on an instance of mesosphere/dcos (which uses mesos `v0.22.1`).

i have an instance of jenkins `v1.609.2` running via marathon/docker with a `Dockerfile` something like

```
FROM jenkins
#...
RUN apt-get -y install mesos=0.22.1-1.0.ubuntu1404
#...
```
(i'm not building mesos as suggested in the docs)

i installed the mesos-plugin `v0.8.0` on this instance of jenkins via the 'Manage Plugins' screen.

(i'm not building mesos-plugin as suggested in the docs)

i [configure the plugin as suggested in the docs](https://github.com/jenkinsci/mesos-plugin#configuring-the-plugin), and when i click "test connection" i see:
```
Connected to Mesos successfully
```
but after i click 'Save' i'm not seeing jenkins register as a mesos framework in the mesos ui (http://my-mesos-master:5050/#/frameworks)...?

any guidance appreciated!

regards,
tony.

**Comment by maselvaraj** [comment]
Have you enabled 'on demand' registration feature?

What do you see in Jenkins log after you click save?

**Comment by albsOps** [comment]
I am having the same issue than tony: Jenkins is not registering in mesos. The difference in my set-up is that my master jenkins is in its own server.
The Jenkins log is updated each minute with:
Aug 28, 2015 2:38:19 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Mesos pending deletion slave cleanup
Aug 28, 2015 2:38:19 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Mesos pending deletion slave cleanup. 0 ms

**Comment by asdfsx** [comment]
I got the same problem.
And I want to know, whether this plugin support zookeeper?

**Comment by geoffroyjabouley** [comment]
Hello
what you're seeing are just periodics logs from the Mesos Slaves cleanup process.

You should be able to get other logs from Jenkins, regarding the JenkinsScheduler class. Set log level to INFO may help.
Also on Mesos master, check logs relevant to framework registration.

Can you also post a screenshot of your Mesos plugin configuration?


Note: when using zookeeper path for Mesos master, the Test Connection button does not works (Zookeeper paths can be used, but the connection cannot be tested prior to saving this page).

**Comment by asdfsx** [comment]
Thx to remind to see the mesos-master's log
in this log I find the following
```shell
mesos-master.WARNING:W0831 18:55:59.697871 27469 master.cpp:4952] Possibly orphaned completed task jenkins-on-mesos.86de6851-4d6b-11e5-bc96-0242c7c54f62 of fr
amework 20150825-123820-604154048-5050-4792-0000 that ran on slave 20150824-193556-620931264-5050-682-S1 at slave(1)@192.168.2.38:5051 (mesos_38)  
```
And in jenkins's log I still find nothing......

my mesos config in jenkins
![image](https://cloud.githubusercontent.com/assets/2292716/9577642/835e54fa-5015-11e5-86ca-8a002b77f3ba.png)

**Comment by rasputnik** [comment]
Unless I set a build to use a label I've previously configured on the mesos 'slave' (task is probably a closer description) nothing gets scheduled on it. 

Jenkins doesn't seem to register itself as a framework until it has a build to launch (I believe that's togglable with the on-demand settings mentioned earlier, though i haven't tried that).

**Comment by asdfsx** [comment]
I think this can be closed~~~~I solve the problem too after reading some source code~~~
