### ISSUE TITLE
${MESOS_SANDBOX-.}/slave.jar or slave-agent.jnlp: No such file or directory, docker cannot be launched in mesos

### ISSUE THREAD

**Issue by ryanivanka** [jenkinsci/mesos-plugin#157]
Hi Experts, 

My issue is about launching docker, jenkins launch slave with error return, so it keep trying like infinite. 

![image](https://cloud.githubusercontent.com/assets/2649096/9623131/3c1a22ee-516f-11e5-8100-31167b42e8f0.png)

Here is my mesos-plugin setting:
![image](https://cloud.githubusercontent.com/assets/2649096/9623138/652b8696-516f-11e5-8f26-8068a64e7df6.png)
![image](https://cloud.githubusercontent.com/assets/2649096/9623148/7ad3c986-516f-11e5-9d85-eb679eb71fbe.png)
![image](https://cloud.githubusercontent.com/assets/2649096/9623152/848e6efe-516f-11e5-8e3a-726649598edd.png)

But jenkins slave cannot be launch:
![image](https://cloud.githubusercontent.com/assets/2649096/9623163/9bbd467c-516f-11e5-8435-659bcf01cbfd.png)

In mesos sandbox, it looks like this:
![image](https://cloud.githubusercontent.com/assets/2649096/9623170/ae49cad6-516f-11e5-813f-15d253b59d79.png)

The stdout:

```
Registered executor on mesos-slave1.labs.microstrategy.com
Starting task mesos-jenkins-a415c1f2-9077-4a15-927f-ea015ed8e1f9
/bin/sh -c exit `docker wait mesos-c81ce40e-812a-493d-af7d-eb7fde4fd550` 
Forked command at 4626
Command exited with status 127 (pid: 4626)
```

The stderr:

```
I0902 00:28:47.807456  4543 fetcher.cpp:214] Fetching URI 'http://mesos-slave3.labs.microstrategy.com:31999/jnlpJars/slave.jar'
I0902 00:28:47.807708  4543 fetcher.cpp:125] Fetching URI 'http://mesos-slave3.labs.microstrategy.com:31999/jnlpJars/slave.jar' with os::net
I0902 00:28:47.807729  4543 fetcher.cpp:135] Downloading 'http://mesos-slave3.labs.microstrategy.com:31999/jnlpJars/slave.jar' to '/tmp/mesos/slaves/20150619-031335-353639178-5050-14206-S11/frameworks/20150812-175543-353639178-5050-5642-0033/executors/mesos-jenkins-a415c1f2-9077-4a15-927f-ea015ed8e1f9/runs/c81ce40e-812a-493d-af7d-eb7fde4fd550/slave.jar'
I0902 00:28:47.973688  4543 fetcher.cpp:329] Skipped extracting path '/tmp/mesos/slaves/20150619-031335-353639178-5050-14206-S11/frameworks/20150812-175543-353639178-5050-5642-0033/executors/mesos-jenkins-a415c1f2-9077-4a15-927f-ea015ed8e1f9/runs/c81ce40e-812a-493d-af7d-eb7fde4fd550/slave.jar'
/bin/bash: java -DHUDSON_HOME=jenkins -server -Xmx640m -Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true -jar ${MESOS_SANDBOX-.}/slave.jar   -jnlpUrl http://mesos-slave3.labs.microstrategy.com:31999/computer/mesos-jenkins-a415c1f2-9077-4a15-927f-ea015ed8e1f9/slave-agent.jnlp: No such file or directory
I0902 00:28:52.797610  4606 exec.cpp:132] Version: 0.22.1
I0902 00:28:52.805742  4619 exec.cpp:206] Executor registered on slave 20150619-031335-353639178-5050-14206-S11
```

It looks like /slave-agent.jnlp is not found. Or maybe the  ${MESOS_SANDBOX-.}/slave.jar is not found? 

**How to fix this to load right jnlp and jar?**

I have tried to launch this docker image in shell command, it all works fine. 

Thank you!

**Comment by geoffroyjabouley** [comment]
Hello

have you tried without specifying a custom docker command shell? Please check that it is still not working without this option.

Although you can start your investigations by trying to start a simple container pulled from the official docker registry (ubuntu:latest)

**Comment by ryanivanka** [comment]
Hi Geoffroyjabouley,

I tried this, I can docker run an image in jenkins job shell command setting. That's why I post an issue on this plugin for help.

Thanks,
Ying

**Comment by pangzheng** [comment]
I have such an error, the solution is to copy slave.jar host, and the directory is mounted to the docker's / mnt / mesos / ... designated slave.jar

**Comment by ryanivanka** [comment]
@pangzheng Could you please explain more? I'm not clear about your solution.

**Comment by ktf** [comment]
I had the same problem at some point. In my case the issue was that I was running the slave inside docker in privileged mode and I had a volume for /var/lib/mesos, e.g.:

```
 docker run --privileged ... -v /scratch:/var/lib/mesos alisw/mesos-slave
```

this is wrong because the subsequent docker command inside the privileged container will still see the host filesystem, not the container one. I changed it to have matching names for my volume:

```
 docker run --privileged ... -v /var/lib/mesos:/var/lib/mesos alisw/mesos-slave
```

and everything started to work.

**Comment by jeschkies** [comment]
@ryanivanka, is this still an issue with the newest version?

**Comment by jeschkies** [comment]
Closing for lack of response.
