### ISSUE TITLE
Lack of multimaster Mesos support

### ISSUE THREAD

**Issue by szwed** [jenkinsci/mesos-plugin#158]
In Cloud definition we can define only one Mesos Master server:
	*Mesos Master [hostname:port]*

While in more complex environments based on multimaster architectures we should be able to list in the field a number of Mesos master instances as the master server may change with time (leadership election procedure & quorum)

**Comment by geoffroyjabouley** [comment]
Hello

you can use zookeeper urls to specify multiple masters:

We have 3 Mesos masters nodes. The url we specify in the plugin is: zk://<master_1>:2181,<master_2>:2181,<master_3>:2181/mesos

**Comment by szwed** [comment]
Works like a harm, thanks!
