### ISSUE TITLE
Docker volumes inside of the jenkins slave docker

### ISSUE THREAD

**Issue by mgummelt** [jenkinsci/mesos-plugin#159]
I can't run docker containers inside of a build due to issues with volumes.

My jenkins slave is running inside a docker, as specified in my jenkins-mesos plugin configuration.  I have a build running on that slave that runs another docker container which mounts the project workspace as a volume (i.e. `-v /jenkins/workspace/project-name:/jenkins`).  However, the mount inside the container is unexpectedly empty.  I think this is because the jenkins slave docker mounts `docker.sock` via `-v /var/run/docker.sock:/var/run/docker.sock`, which means that the container inside the build is actually executing on the host's docker daemon.  So rather than mounting the `/jenkins/workspace/project-name` directory from the jenkins slave, it mounts it from the host. The host does have a `/jenkins/workspace/project-name` directory, which is created dynamically somehow, but it's empty.  That directory inside of the jenkins slave container is non-empty, and is the one I want to mount.

So I have two questions:

1)  What creates the `/jenkins/workspace/project-name` directory on the host, and why?
2) How can I run a docker container in my build that mounts the project's workspace?

**Comment by tony-kerz** [comment]
this might be related to this: https://github.com/docker/docker/issues/15637

**Comment by mgummelt** [comment]
@tony-kerz: Ah, that does explain #1.  I didn't realize docker creates non-existent host volumes.

I still need a solution for #2 though.  Any ideas?

**Comment by tony-kerz** [comment]
hi @mgummelt,

w.r.t. how to mount the project's workspace, if you read thru [this comment](https://github.com/docker/docker/issues/15637#issuecomment-135502676), i allude to it towards the end.

in my case, i am mounting a specific file, but the concept is the same, you have to mount based on the 'volumes' of the ultimate host, not the workspace if that makes sense. 

so if you are telling the image running jenkins to use the docker instance on the host by linking to the host `/var/run/docker.sock`, then docker will only really know about the host's volumes...

so the solution is to refer to the ultimate host's volumes when mounting within a jenkins job, if that makes sense.

feel free to reach out for further clarification.

**Comment by xoco70** [comment]
> so the solution is to refer to the ultimate host's volumes when mounting within a jenkins job, if that makes sense.

Can you please elaborate this point ? I am running on the same issue, but don't really know how to fix it

**Comment by gypark** [comment]
@xoco70 
I got a trouble with this issue yesterday, and I'll describe what I'd done and what I understand from this thread:

I ran jenkins using docker,

    docker run \
        --name jenkins \
        -d \
        --restart always \
        -u root \
        -e JAVA_OPTS="-Duser.timezone=Asia/Seoul" \
        -p 20100:8080 \
        -p 20110:50000 \
        -v jenkins-data:/var/jenkins_home \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "$HOME":/home \
        --network dev-network \
        jenkinsci/blueocean

Inside jenkins, I tried to run another docker image to execute my source script:

    docker run -t --rm -v $WORKSPACE:/usr/src/myapp -w /usr/src/myapp perl:5.26 perl my_script.pl

`$WORKSPACE` is `/var/jenkins_home/workspace/myproject`, which exists INSIDE jenkins container.

However, perl:5.26 container could not find my_script.pl. In fact, `/usr/src/myapp` was empty. And I found `/var/jenkins_home/workspace/myproject` directory had been created inside my host machine. This means the docker inside jenkins referred to directories 'in the host' rather than directories in Jenkins container.

So, I just edited the mount point, to refer the directory in my host:

    docker run -t --rm -v /var/lib/docker/volumes/jenkins-data/_data/workspace/myproject:/usr/src/myapp -w /usr/src/myapp perl:5.26 perl my_script.pl

And this works.

I don't know whether this is the best way to solve this problem. (I don't think so...)

**Comment by ckatzorke** [comment]
I am still looking for a sophisticated solution, since "hard coding" the hosts data dir is not an option, especially when running multi branch builds. 
For now I am just replacing the folder structure up to the dynamic part (job + branch name), but this feels really dirty. :pig:
