### ISSUE TITLE
Docker container won't start when volume is configured with no host path

### ISSUE THREAD

**Issue by branden** [jenkinsci/mesos-plugin#163]
When I configure the Docker containerizer with a volume that has no host path, Jenkins slaves fail to start. I see this error in Mesos logs:

> Container '27538997-a50c-47c4-a34e-50e49349440b' for executor 'mesos-jenkins-24ca2566-957b-4a0d-a5a2-51094f5d6797' of framework '20150819-185023-2260476938-5050-1915-0001' failed to start: Host path is required with mode

It seems like the mode portion of the volume is being passed regardless of whether I've checked the "Read-Only" box. My intention is to pass only the container path with no host path or mode, like `--volume /foo/bar`.

I'm running Jenkins 1.602 with version 0.8.0 of the mesos plugin.

**Comment by jeschkies** [comment]
@branden, what is you expected behavior? Does it work for you in 1.0 or 2.0 of the plugin?

**Comment by branden** [comment]
@jeschkies Good question! I've forgotten all about this issue, so I'll go ahead and close it.
