### ISSUE TITLE
Why is the latency so high for identical work requests.

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#165]
Using the workflow plugin two builds are requested. The builds both ask for the same resource. The system is quiescent. The first request for a node  is scheduled within 10 seconds.  The second request for a node takes on average between 1 and 2 minutes.

**Comment by digitalrinaldo** [comment]
I am not sure if I should be posting two lists. If this is not useful -- which list would you prefer I post to.

https://groups.google.com/forum/#!topic/jenkins-mesos/YhynZdQFjMk

**Comment by geoffroyjabouley** [comment]
Hello
have you tried configuring node provisioning:
https://github.com/jenkinsci/mesos-plugin#over-provisioning-flags

We use the following java option when starting Jenkins: -Djava.hudson.slaves.NodeProvisioner.MARGIN=1

It gives good reactivity without overprovisioning too much

**Comment by digitalrinaldo** [comment]
Thanks I will try it -- the following is resulting in very long delays.

Using parallel tasks in workflow the following code doesn't get a second resource from the mesos-plugin for over 60 seconds sometimes 120 seconds.  Granted this may be an issue with workflow or mesos.  If other labels are used the task runs immediately.

def tasks = ["Task One", "Task Two"]
def branches = [:]
for (int i = 0; i < tasks.size(); i++) {
  def taskName = tasks.get(i);
  branches[taskName] = {
    node('mesos') {
      wrap([$class: 'TimestamperBuildWrapper']) {
        echo ("${taskName}")
        sh 'uname -a;sleep 120'
      }
   }
  }
}
parallel branches

Trying to narrow ir down so I get it resolved and others don't have the same issue.

**Comment by digitalrinaldo** [comment]
The doc suggests --- -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85


https://github.com/jenkinsci/mesos-plugin#over-provisioning-flags

What I am seeing is lots of nodes quickly show up but they all seem to fail when there are more requests than resources. Is this the expect behaviour.  In fact it is so bad nothing actually gets allocated.  Suppose I have ten nodes and 30 requests, I see constant resource request failures.

**Comment by digitalrinaldo** [comment]
I have verified that this is the default behaviour and IMO it is misleading to users. If you have more requests than nodes the current driver attempts to satisfy all of them and those that fail for whatever reason are should with the little red box. Since we don't have reservations this can be a problem but given that many users will have smaller configs, I would reduce the chance of the red x occurring by asking mesos how many requests would be filled, I assume mesos has such a ability. Clearly no one is interested in this since it  has been opened up for over 6 months, closing it.
