### ISSUE TITLE
How to terminate nodes gracefully

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#166]
Is there a user action one can take on the node to release the resources immediately.  There is another discussion on this topic at user@mesos.apache.org

Saw this issue https://github.com/mesosphere/marathon/issues/712

response from spodila@netflix.com

I believe this depends on the executor being used. A kill request to mesos driver from the framework scheduler is delivered to the executor. The kill request by itself is not a guarantee that the task will be killed, until honored by the executor. So, it is possible that the executor can be written to achieve the "graceful" behavior you desire. The resources assigned to the task aren't reclaimed until the task is reported killed/terminated by the executor. It is possible, for example, to perform "clean up" or "checkpointing" as part of a task kill request. But, that can be tricky in terms of delaying the actual kill logistics, and therefore making the resources available. 

If your question regarding a specific executor you are already using?

In case you are referring to resource oversubscription feature recently introduced, those kills are determined by an entity local to the Mesos agent node. "Grace" would be majorly influenced by that entity and less by the executor.

On Tue, Sep 22, 2015 at 9:39 AM, Jerry Lam chilinglam@gmail.com wrote:
Hi mesos users,

anyone knows how to kill a task running in Mesos gracefully? Thanks!

Best Regards,

Jerry

**Comment by vinodkone** [comment]
On Tue, Sep 22, 2015 at 2:31 PM, Rinaldo Di Giorgio <
notifications@github.com> wrote:

> Is there a user action one can take on the node to release the resources
> immediately. There is another discussion on this topic at
> user@mesos.apache.org
>
>
What do you mean by "release the resources immediately"? The plugin
utilizes the default mesos command executor which terminates as soon as the
underlying task (in this case it is the jenkins slave) terminates. Mesos
releases and reoffers the resources immediately after an executor/task
terminates. Are you seeing something different?


-- Vinod

**Comment by digitalrinaldo** [comment]
When a task is complete on the mesos allocated resource, I want to shut it down release resources and not have a killed message in the framework. Words are important -- Killed is the wrong word.

**Comment by devinsba** [comment]
I noticed this myself. In my opinion if the Jenkins slave is not running a job and shuts down due to timeout it should register as finished instead of killed.

I understand that the underlying issue is that the framework tells mesos to kill the task so it ends up with that status. maybe we can come up with a way to signal the executor to exit(0) instead so that the task is differentiated from one that actually fails because of a failure. For instance I was debugging some actual job failures that were intermingled with tasks that "failed" successfully

**Comment by jeschkies** [comment]
I'm not sure I understand what's meant by a graceful shutdown. I would like to have all build agents to be one-off jobs. That means the executor exits once a build is done. A graceful shutdown would simply mean not to schedule new builds. USI would then suppress all offers.

**Comment by jeschkies** [comment]
Closing for lack of response.
