### ISSUE TITLE
no mesos in java.library.path

### ISSUE THREAD

**Issue by dragon9783** [jenkinsci/mesos-plugin#175]
### [Environment]

Jenkins +1 (docker container and mapping host directory /data to /var/jenkins_home )
Mesos master +1 (docker container)
Mesos slave +2 (docker container)
### [steps]

already copy mesos native library to /var/jenkins_home, 
on jenkins web interface add mesos cloud, test connection run success, but have a issue when save config 
![image](https://cloud.githubusercontent.com/assets/2681774/10416368/ff206820-7046-11e5-8c4c-3134f1321d5f.png)
the native library is the path on mesos master ? any recommendations how to proceed?

**Comment by dragon9783** [comment]
the web interface configurations
![image](https://cloud.githubusercontent.com/assets/2681774/10416396/8785ad1e-7048-11e5-8952-41cf394824d3.png)

**Comment by fin09pcap** [comment]
Have you attempted to bind mount the mesos native library path inside the Jenkins container with all required dependencies for the library?

The alternative is to install the mesos and its dependencies to mirror the system you running mesos on to ensure the same packages are being used inside the Jenkins container.

**Comment by talktorana** [comment]
I am also facing exactly same issue. I am not running jenkins in docker mode. mesos cluster is up and I compiled mesos on jenkins master and pointed "Mesos native library path:" to /home/mesos/mesos-1.1.0/build/src/.libs . Any workarounds please?

**Comment by ryoichitaniguchi** [comment]
Previously I also encountered same issue, (and also jenkins failed to startup). As my tentative workaround, leave "native library path" blank/null by modifying config file directly and tried to launch again. In such condition,  jenkins successfly load default location of mesos library, libmesos.so, according to #lsof command, I donot think its ideal solution though.

**Comment by jeschkies** [comment]
@dragon9783, do you still have this issue? Could you try 2.0 of the plugin. It does not require the native library.

**Comment by jeschkies** [comment]
Closing for lack of response.
