### ISSUE TITLE
Cannot shut down unknown framework also not able to launch jenkins slave.

### ISSUE THREAD

**Issue by ravinder1985** [jenkinsci/mesos-plugin#180]
It is able to connect to master but i am having following issue.

Logs from slave:

W1027 20:23:45.965175 30147 master.hpp:1532] Master attempted to send message to disconnected framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
W1027 20:23:45.965875 30147 master.hpp:1532] Master attempted to send message to disconnected framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:45.966071 30147 master.cpp:1143] Giving framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256 0ns to failover
I1027 20:23:45.966191 30147 hierarchical.hpp:599] Deactivated framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:45.966313 30147 hierarchical.hpp:1103] Recovered cpus():1; mem():244; disk():14972; ports():31000-32000 on slave df5d0974-8a3c-4d65-9d36-c2c22fd035b1-S1 from framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:45.966473 30147 hierarchical.hpp:1103] Recovered cpus():0.9; mem():228; disk():14972; ports():31000-31341, 31343-32000 on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 from framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:45.974308 30147 master.cpp:4815] Framework failover timeout, removing framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:45.974344 30147 master.cpp:5571] Removing framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:45.974576 30147 hierarchical.hpp:552] Removed framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:46.461467 30147 master.cpp:2179] Received SUBSCRIBE call for framework 'Jenkins Scheduler' at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:46.461665 30147 master.cpp:2250] Subscribing framework Jenkins Scheduler with checkpointing disabled and capabilities [ ]
I1027 20:23:46.462273 30147 hierarchical.hpp:515] Added framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0391
I1027 20:23:46.463017 30147 master.cpp:4967] Sending 2 offers to framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0391 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256

also

W1027 20:12:33.288890 22887 slave.cpp:1995] Cannot shut down unknown framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0171
I1027 20:12:36.314723 22887 slave.cpp:1980] Asked to shut down framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0172 by master@96.119.242.62:5050
W1027 20:12:36.314999 22887 slave.cpp:1995] Cannot shut down unknown framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0172
I1027 20:12:39.347779 22887 slave.cpp:1980] Asked to shut down framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0173 by master@96.119.242.62:5050
W1027 20:12:39.347932 22887 slave.cpp:1995] Cannot shut down unknown framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0173

MASTER :

master:
ct 27 19:47:42 testmesosmas-cmce-01 marathon[24375]: [2015-10-27 19:47:42,964] INFO 10.36.123.233 - - [27/Oct/2015:19:47:42 +0000] "GET //96.119.247.56:8080/v2/apps HTTP/1.1" 200 1458 "http://96.119.247.56:8080/ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$284a2e90:14)
Oct 27 19:47:43 testmesosmas-cmce-01 mesos-master[4231]: E1027 19:47:43.348151 4251 socket.hpp:174] Shutdown failed on fd=24: Transport endpoint is not connected [107]
Oct 27 19:47:43 testmesosmas-cmce-01 mesos-master[4231]: E1027 19:47:43.348683 4251 socket.hpp:174] Shutdown failed on fd=44: Transport endpoint is not connected [107]
Oct 27 19:47:43 testmesosmas-cmce-01 mesos-master[4231]: I1027 19:47:43.348780 4243 master.cpp:1119] Framework 2120f1d1-ba6b-45f1-9f80-7d57005eabe7-0693 (Jenkins Scheduler) at scheduler-60588491-ed72-4166-82e1-2755ab6ae164@96.119.2.253:59256 disconnected

**Comment by bhuvan** [comment]
@ravinder1985 what version of mesos-master and mesos-slave you running?

This framework was built using mesos-0.22.1 https://github.com/jenkinsci/mesos-plugin/blob/master/pom.xml#L81. May be we should release a newer version of this plugin built using newer mesos release to account for recent protobuf changes, perhaps?

In 0.23 and 0.24 there are few changes to replace `Framework.Id` with `FrameworkInfo.id`. It's a work in progress, which breaks framework built against older mesos version.

Ref:
  1. https://issues.apache.org/jira/browse/MESOS-905
  1. https://issues.apache.org/jira/browse/MESOS-2558
  1. https://issues.apache.org/jira/browse/MESOS-2559

**Comment by ravinder1985** [comment]
I am working with 
Server:96.119.242.62:5050
Version:0.25.0 
Built: 2015-10-12T16:59:01-0400 
by root

I am going to install 0.22.1, will post it if start working. Thanks for you information.

**Comment by ravinder1985** [comment]
Down graded my mesos master to 0.22.1

still having following errors. please help. its keep disconnecting. 
i am running 0.8.0 version in jenkins and Jenkins ver. 1.625.1

1.552764  5100 master.cpp:1574] Received registration request for framework 'Jenkins Scheduler' at scheduler-a125dc00-0fdc-43c1-9c77-a086ea4093d6@96.119.2.253:55912
I1028 20:13:41.553812  5100 master.cpp:1638] Registering framework 20151028-193556-822114144-5050-5079-0043 (Jenkins Scheduler) at scheduler-a125dc00-0fdc-43c1-9c77-a086ea4093d6@96.119.2.253:55912
I1028 20:13:41.555249  5098 hierarchical.hpp:321] Added framework 20151028-193556-822114144-5050-5079-0043
I1028 20:13:44.555352  5099 master.cpp:878] Framework 20151028-193556-822114144-5050-5079-0043 (Jenkins Scheduler) at scheduler-a125dc00-0fdc-43c1-9c77-a086ea4093d6@96.119.2.253:55912 disconnected
I1028 20:13:44.555763  5099 master.cpp:1948] Disconnecting framework 20151028-193556-822114144-5050-5079-0043 (Jenkins Scheduler) at scheduler-a125dc00-0fdc-43c1-9c77-a086ea4093d6@96.119.2.253:55912
I1028 20:13:44.556026  5099 master.cpp:1964] Deactivating framework 20151028-193556-822114144-5050-5079-0043 (Jenkins Scheduler) at scheduler-a125dc00-0fdc-43c1-9c77-a086ea4093d6@96.119.2.253:55912
I1028 20:13:44.558123  5099 master.cpp:900] Giving framework 20151028-193556-822114144-5050-5079-0043 (Jenkins Scheduler) at scheduler-a125dc00-0fdc-43c1-9c77-a086ea4093d6@96.119.2.253:55912 0ns to failover
I1028 20:13:44.558271  5100 hierarchical.hpp:400] Deactivated framework 20151028-193556-822114144-5050-5079-0043

**Comment by ravinder1985** [comment]
Now i am having  following issue. my framework connected to mesos master.

W1028 20:48:50.633822   346 protobuf.hpp:426] Initialization errors: framework_info.name, request.requests[0].slave_id.value


I1028 20:42:56.258544   342 master.cpp:3760] Sending 1 offers to framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:42:56.322768   342 master.cpp:2273] Processing ACCEPT call for offers: [ 20151028-182427-1056077664-5050-325-O935 ] on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 at slave(1)@96.119.242.139:5051 (testmesosslv-cmce-01.sys.comcast.net) for framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:42:56.323144   342 hierarchical.hpp:648] Recovered cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000] (total allocatable: cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000]) on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 from framework 20151028-182427-1056077664-5050-325-0926
W1028 20:42:57.409857   342 protobuf.hpp:426] Initialization errors: framework_info.name, request.requests[0].slave_id.value


I1028 20:48:41.565811   349 master.cpp:2273] Processing ACCEPT call for offers: [ 20151028-182427-1056077664-5050-325-O952 ] on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 at slave(1)@96.119.242.139:5051 (testmesosslv-cmce-01.sys.comcast.net) for framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:48:41.566212   349 hierarchical.hpp:648] Recovered cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000] (total allocatable: cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000]) on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 from framework 20151028-182427-1056077664-5050-325-0926
I1028 20:48:43.728907   349 http.cpp:516] HTTP request for '/master/state.json'
I1028 20:48:47.510210   346 master.cpp:3760] Sending 1 offers to framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:48:47.570078   346 master.cpp:2273] Processing ACCEPT call for offers: [ 20151028-182427-1056077664-5050-325-O953 ] on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 at slave(1)@96.119.242.139:5051 (testmesosslv-cmce-01.sys.comcast.net) for framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:48:47.570458   346 hierarchical.hpp:648] Recovered cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000] (total allocatable: cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000]) on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 from framework 20151028-182427-1056077664-5050-325-0926
I1028 20:48:50.078353   346 http.cpp:516] HTTP request for '/master/state.json'
W1028 20:48:50.633822   346 protobuf.hpp:426] Initialization errors: framework_info.name, request.requests[0].slave_id.value
I1028 20:48:52.802696   346 http.cpp:516] HTTP request for '/master/state.json'
I1028 20:48:53.515955   346 master.cpp:3760] Sending 1 offers to framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:48:53.575810   346 master.cpp:2273] Processing ACCEPT call for offers: [ 20151028-182427-1056077664-5050-325-O954 ] on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 at slave(1)@96.119.242.139:5051 (testmesosslv-cmce-01.sys.comcast.net) for framework 20151028-182427-1056077664-5050-325-0926 (Jenkins Scheduler) at scheduler-af14e3ab-df7a-4231-b162-191e1443a4a7@96.119.0.49:42817
I1028 20:48:53.576115   346 hierarchical.hpp:648] Recovered cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000] (total allocatable: cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000]) on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 from framework 20151028-182427-1056077664-5050-325-0926
I1028 20:48:54.733062   346 http.cpp:516] HTTP request for '/master/state.json'

**Comment by ravinder1985** [comment]
it is working as expected in 0.22.1 version with mesos plugin 0.8.0
Thanks a lot for help
