### ISSUE TITLE
Expose taskId to container

### ISSUE THREAD

**Issue by keis** [jenkinsci/mesos-plugin#184]
I'm using the MESOS_TASK_ID exposed by marathon to identify the logs captured from the containers running on mesos. It would be great if I could use the same method for the tasks started by jenkins.

It should be a simple patch but I wanted to check if you think this a good idea before digging in.

**Comment by vinodkone** [comment]
Can you elaborate a bit more on how marathon exposes "MESOS_TASK_ID" ?

**Comment by keis** [comment]
It takes the generated id and adds it to the environment of the container. That is done by adding an entry to the `Environment` bit of `CommandInfo`. It might not seem super useful at first but the nice thing about it is that it will show up in `docker inspect` so you get a easy way of finding the task of a container you have.

https://mesosphere.github.io/marathon/docs/task-environment-vars.html

**Comment by jeschkies** [comment]
@keis, would you like the logs of the executor or of the build? I don't think a user should be exposed to the executor logs. An operator might want to.

**Comment by keis** [comment]
I don't quite remember what this was about but I think the point was to label the logs pumped from the system to elk to have some sensible labels.

For me personally I don't particularly care; I'm not working for the same company anymore, they are not using mesos, and these days not even sure if jenkins is in the picture.

**Comment by jeschkies** [comment]
@keis, thanks for the reply. Unfortunately we dropped the ball there ☹️
