### ISSUE TITLE
mesos-executor failed with permission denied 

### ISSUE THREAD

**Issue by vidyajothiraman** [jenkinsci/mesos-plugin#187]
Hi
I am following instructions at https://github.com/jenkinsci/mesos-plugin and registered Jenkins scheduler as a framework in Mesos. 
Have setup a new project in Jenkins with a Mesos cloud. 
While I initiate the job, I see the Job is pending with message as "pending—Waiting for next available executor)". In the framework I see all tasks are failed. All the slaves have failed to initiate. 

Found this in stderr:

I1121 04:27:54.646160 15048 fetcher.cpp:414] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/e958e439-dda8-4242-94bb-2bea4414668e-S0\/jenkins","items":[{"action":"BYPASS_CACHE","uri":{"executable":false,"extract":false,"value":"http:\/\/9.xx.xx.xxx:8080\/jnlpJars\/slave.jar"}}],"sandbox_directory":"\/tmp\/mesos\/slaves\/e958e439-dda8-4242-94bb-2bea4414668e-S0\/frameworks\/e958e439-dda8-4242-94bb-2bea4414668e-0001\/executors\/mesos-jenkins-ff119920-d912-45d7-80d6-b526301cdc33\/runs\/66f837a1-34cd-4c49-9da6-25902a585b66","user":"jenkins"}
I1121 04:27:54.655375 15048 fetcher.cpp:369] Fetching URI 'http://9.xxx.xx.xxx:8080/jnlpJars/slave.jar'
I1121 04:27:54.655441 15048 fetcher.cpp:243] Fetching directly into the sandbox directory
I1121 04:27:54.655490 15048 fetcher.cpp:180] Fetching URI 'http://9.xxx.xx.xxx:8080/jnlpJars/slave.jar'
I1121 04:27:54.655560 15048 fetcher.cpp:127] Downloading resource from 'http://9.xxx.xx.xxx:8080/jnlpJars/slave.jar' to '/tmp/mesos/slaves/e958e439-dda8-4242-94bb-2bea4414668e-S0/frameworks/e958e439-dda8-4242-94bb-2bea4414668e-0001/executors/mesos-jenkins-ff119920-d912-45d7-80d6-b526301cdc33/runs/66f837a1-34cd-4c49-9da6-25902a585b66/slave.jar'
I1121 04:27:54.668056 15048 fetcher.cpp:446] Fetched 'http://9.xxx.xx.xxx:8080/jnlpJars/slave.jar' to '/tmp/mesos/slaves/e958e439-dda8-4242-94bb-2bea4414668e-S0/frameworks/e958e439-dda8-4242-94bb-2bea4414668e-0001/executors/mesos-jenkins-ff119920-d912-45d7-80d6-b526301cdc33/runs/66f837a1-34cd-4c49-9da6-25902a585b66/slave.jar'
sh: /root/mesos-0.25.0/build/src/mesos-executor: Permission denied

I have modified the permission to be 777 for /root/mesos-0.25.0/build/src/mesos-executor but still same message. 
Mesos version: 0.25.0
Jenkins version: 1.638

**Comment by maselvaraj** [comment]
what is the username you are starting Jenkins with ?

**Comment by vidyajothiraman** [comment]
Hi Mani

I started jenkins as root.

**Comment by vidyajothiraman** [comment]
Hi
Can some one please help me here?

**Comment by geoffroyjabouley** [comment]
can you post a screeshot of your mesos cloud config in Jenkins?

**Comment by vidyajothiraman** [comment]
![mesos_cloud](https://cloud.githubusercontent.com/assets/15954794/11741813/62ddce5c-a021-11e5-9414-730fbf72ae11.jpg)
Here is the screenshot

**Comment by geoffroyjabouley** [comment]
Is your mesos slave started with the jenkins user? You should put here the
unix username actually running the mesos slave process

2015-12-11 11:38 GMT+01:00 vidyajothiraman <notifications@github.com>:

**Comment by vidyajothiraman** [comment]
Hi, it is running with root, though I tried earlier giving root, looks like a jenkins restart was required. I updated slave username as root , restarted jenkins. Now it works :)
Btw can you help me to find out what is the time basis on which the mesos slave agent gets killed. I mean after launching jenkins slave running the build there, how many minutes later that slave gets killed. Where to set this value?

**Comment by geoffroyjabouley** [comment]
Have a look at the "Idle Termination Minutes" option in each Slave Info of
your Mesos Cloud configuration.
Minimum value is 1 (1 minute)

2015-12-11 14:47 GMT+01:00 vidyajothiraman <notifications@github.com>:

**Comment by vidyajothiraman** [comment]
From my github repository, under web hooks, i created a new web hook as in attached picture. But this web hook is not able to connect to my Jenkins server. It says Invalid http response: 401. And in repsonse tab
 i see this :

 Headers

Connection: close

![web-hook](https://cloud.githubusercontent.com/assets/15954794/11752952/72d123d0-a068-11e5-9846-1df8b52150fa.jpg)

**Comment by vidyajothiraman** [comment]
Any help on my above post will be appreciated. Because of this failure in post from git hub to Jenkins, the build is not getting triggered if i push something to github.

**Comment by vinodkone** [comment]
I don't think it is related to the Mesos plugin. Did you try getting it to work with your jenkins master without the mesos plugin?

Also, please ask questions on the mailing list jenkins-mesos@googlegroups.com instead of asking several different questions on one GitHub issue.

**Comment by vidyajothiraman** [comment]
Hi Vinod 
yes this is not related to mesos. The hook does not work with my jenkins master. 

Going forward let me post my questions to google group. Thanks for pointing me to it
