### ISSUE TITLE
[QUESTION] mesos-plugin is marathon replacement?

### ISSUE THREAD

**Issue by a93ushakov** [jenkinsci/mesos-plugin#190]

**Comment by vinodkone** [comment]
No. Mesos plugin allows a Jenkins master to elastically launch Jenkins slaves. Unlike marathon it cannot launch arbitrary applications on a mesos cluster.

**Comment by a93ushakov** [comment]
Thanks for reply.

So, for building distributed CI can be used these result-equivalent methods:
* mesos + jenkins framework
* mesos + marathon?

**Comment by geoffroyjabouley** [comment]
Hi

Mesos + jenkins framework will allow you to dynamically create jenkins
slaves, based on your Jenkins master load. These on-demand slaves are
automatically attached to your Jenkins master, execute builds in the queue,
and are then killed and their resources returned to the Mesos cluster when
not needed anymore

Mesos + marathon if more oftenly used to create Jenkins masters instance.
But it could also be possible to create new Jenkins slaves using Marathon.
In this case, the connexion master <-> slave has to be done manually.

Cheers

2016-01-15 3:55 GMT+01:00 Alex Ushakov <notifications@github.com>:
