### ISSUE TITLE
mesos 0.27.0 support

### ISSUE THREAD

**Issue by ghost** [jenkinsci/mesos-plugin#201]
Will be realized in future?

**Comment by geoffroyjabouley** [comment]
https://github.com/jenkinsci/mesos-plugin/pull/186#issuecomment-168652356

If you have a Mesos 0.26 setup available, maybe you can make the change and test it yourself, then gives us some feedback.

**Comment by a93ushakov** [comment]
```sh
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:40.265s
[INFO] Finished at: Tue Feb 02 21:14:44 EET 2016
[INFO] Final Memory: 44M/378M
[INFO] ------------------------------------------------------------------------
```

befor
```java
      if (StringUtils.isNotBlank(secret)) {
        Credential credential = Credential.newBuilder()
                .setPrincipal(principal)
                .setSecret(ByteString.copyFromUtf8(secret))
                .build();
```

after
```java
      if (StringUtils.isNotBlank(secret)) {
        Credential credential = Credential.newBuilder()
                .setPrincipal(principal)
                .setSecret(secret)
                .build();
 
```

**Comment by a93ushakov** [comment]
But there are several problems - I hope you help:
* I try to forward [this tutorial](https://www.cloudbees.com/blog/apache-mesos-and-jenkins-elastic-build-slaves)
* ```sh
sudo mvn hpi:run
```
I open `localhost:8080` and see this error 
![2016-02-02-220135_1600x900_scrot](https://cloud.githubusercontent.com/assets/13286493/12762603/9799322a-c9f8-11e5-87e7-c874b8b6c86d.png)

I had configured mesos cloud in jenkins settings and create new job - execute shell command
```sh
sleep 3000
```

but there aren't neither  in jenkins dashbord nor in mesos dashbord nothing new.

Can you help?

**Comment by maselvaraj** [comment]
http://localhost:8080/jenkins

What does the jenkins logs say ?

**Comment by a93ushakov** [comment]
```sh
Feb 02, 2016 10:00:59 PM INFO jenkins.InitReactorRunner$1 onAttained
Started initialization
Feb 02, 2016 10:00:59 PM INFO jenkins.InitReactorRunner$1 onAttained
Listed all plugins
Feb 02, 2016 10:00:59 PM INFO jenkins.InitReactorRunner$1 onAttained
Prepared all plugins
Feb 02, 2016 10:00:59 PM INFO jenkins.InitReactorRunner$1 onAttained
Started all plugins
Feb 02, 2016 10:00:59 PM INFO jenkins.InitReactorRunner$1 onAttained
Augmented all extensions
Feb 02, 2016 10:01:00 PM INFO jenkins.InitReactorRunner$1 onAttained
Loaded all jobs
Feb 02, 2016 10:01:01 PM INFO org.jenkinsci.main.modules.sshd.SSHD start
Started SSHD at port 60868
Feb 02, 2016 10:01:02 PM INFO jenkins.InitReactorRunner$1 onAttained
Completed initialization
Feb 02, 2016 10:01:02 PM INFO hudson.TcpSlaveAgentListener 
JNLP slave agent listener started on TCP port 35783
Feb 02, 2016 10:01:02 PM INFO hudson.WebAppMain$3 run
Jenkins is fully up and running
Feb 02, 2016 10:01:02 PM INFO jenkins.model.Jenkins 
Effective SlaveRestarter on master: null
Feb 02, 2016 10:01:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:01:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 33 ms
Feb 02, 2016 10:02:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:02:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 0 ms
Feb 02, 2016 10:03:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:03:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 0 ms
Feb 02, 2016 10:04:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:04:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 1 ms
Feb 02, 2016 10:05:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:05:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 0 ms
Feb 02, 2016 10:06:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:06:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 0 ms
Feb 02, 2016 10:07:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 02, 2016 10:07:08 PM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 68 ms
Feb 03, 2016 6:22:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 03, 2016 6:22:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 1 ms
Feb 03, 2016 6:23:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 03, 2016 6:23:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 0 ms
Feb 03, 2016 6:24:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 03, 2016 6:24:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 0 ms
Feb 03, 2016 6:25:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Started Mesos pending deletion slave cleanup
Feb 03, 2016 6:25:18 AM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Mesos pending deletion slave cleanup. 1 ms
```

In fact - after managing mesos cloud in `jenkins` dashboard new framework must be registered in `mesos` dashboard. But in my case it empty.

**Comment by maselvaraj** [comment]
Have configured 'on demand registration - yes ?

**Comment by a93ushakov** [comment]
I had :
* installed standalone `jenkins`
* copy plugin

Now messos see jenkins framework.

But I have new trouble:  
when I create new job - shell command -`sleep 600` and press "to schedule" button - in jenkins dashboard I see that this job processing starts but in mesos dashboard I don't see any new task.

**Comment by a93ushakov** [comment]
And yet one more question - how to make all builds only on slave instances?

**Comment by maselvaraj** [comment]
have you labelled the job as 'mesos' ? 

Yes, this plugin creates jenkins slave instances when there is a build in queue and kills it when the builds is complete.

**Comment by a93ushakov** [comment]
I had created new job with `mesos` label, checkpointed `Mesos Single-Use Slave` option.
![2016-02-03-074159_1600x900_scrot](https://cloud.githubusercontent.com/assets/13286493/12774013/b7d2b0ce-ca49-11e5-8f18-4b42bd0b8f54.png)

**Comment by maselvaraj** [comment]
Can you please check the jenkins logs if the resource offers are sent from mesos ?

**Comment by a93ushakov** [comment]
http://pastebin.com/4rGBS19j

**Comment by maselvaraj** [comment]
Is there any other framework other than Jenkins registered in your Mesos ? 

Can you try restarting your jenkins ? 
<your jenkins url>/restart

**Comment by a93ushakov** [comment]
I had
```sh
sudo service jenkins restart
```
and recreate job - the same error.

**Comment by a93ushakov** [comment]
I had also `marathon` installed - but it's disabled (`sudo service marathon stop`).

**Comment by maselvaraj** [comment]
Not sure whats going wrong yet.
I'll squeeze to squeeze sometime this week to debug Mesos 0.26.0 with Jenkins Mesos plugin. Meantime if you have any updates please post it here.

**Comment by a93ushakov** [comment]
I upgraded to `mesos 0.27.0`, recompile by `sudo mvn package`, remove in `jenkins` plugins path `mesos.hpi` and `mesos` dir-ry, restart `mesos` master and slaves, jenkins services.

this is mesos in jenkins settings:
![Uploading 2016-02-03-082535_1600x900_scrot.png…]()

I use debian apt repo from mesosphere.

**Comment by a93ushakov** [comment]
Maybe problem in permissions? `Marathon` run with `root` permissions, `jenkins` - with `jenkins` user permissions.

**Comment by a93ushakov** [comment]
![2016-02-03-085647_1600x900_scrot](https://cloud.githubusercontent.com/assets/13286493/12775126/242f824c-ca54-11e5-8c66-f90dc447b745.png)

**Comment by maselvaraj** [comment]
Above screenshot, I see that resources are offered to Jenkins. Can you check Mesos sandbox logs ?

**Comment by a93ushakov** [comment]
http://pastebin.com/QjGr7VR7

**Comment by geoffroyjabouley** [comment]
Have you configured LIBPROCESS_IP & cie variables?



2016-02-03 8:19 GMT+01:00 Alex Ushakov <notifications@github.com>:

**Comment by a93ushakov** [comment]
No. In instruction i didnt see that.
Where they should be configured? Or you mean cloud (mesos) settings in
jenkins settings?

**Comment by pradeepchhetri** [comment]
I want to confirm that i am using jenkins plugin (0.10.1) with mesos 0.27.0 and it is working fine. So i guess we can close this issue.

**Comment by alexxxxx** [comment]
Hello @pradeepchhetri,
When builduing the plugin, you didn't had this problem:
[ERROR] ...../src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java:[559,18] cannot find symbol
  symbol:   class ContainerInfo
  location: class org.apache.mesos.Protos.CommandInfo

**Comment by pradeepchhetri** [comment]
@alexxxxx You dont need to build the plugin with each mesos version. You can just install the mesos plugin from Jenkins UI ("Manage Jenkins" -> "Manage Plugins") and install it from there.

Let me know if it works for you or not. I will help you out.

**Comment by alexxxxx** [comment]
Thanks a lot for your quick reply.
I have build and install the plugin (0.10.1 with mesos 0.26.0). from the
UI, I can connect to mesos.
My problem is that the framework received offers but decline them all (and
I don't know how to see the reason).
This is why I was trying to compile the plugin with the latest mesos (The
one I am currently running)
Cheers,
Alex

**Comment by pradeepchhetri** [comment]
Hello Alex,

First thing i would like you to check is:

Did you configure Mesos Cloud correctly (specially did you set the Label string and using the same Label in the job configuration as well) ? 

I am attaching the screenshot of both below:

**Mesos Cloud Setting**

![screen shot 2016-02-24 at 13 59 05](https://cloud.githubusercontent.com/assets/2232667/13287458/208141d8-daff-11e5-8a2e-53c8612f6a83.png)

**Jenkins Job Setting**

![screen shot 2016-02-24 at 14 00 52](https://cloud.githubusercontent.com/assets/2232667/13287474/2dc9ad9e-daff-11e5-9d63-e87751cc9256.png)

**Comment by alexxxxx** [comment]
I confirm that the label is properly set. I also use the magic role *. The
only difference is that I don't put any credentials since my mesos only
authenticate slave.

this is the mesos logs:
I0224 15:13:46.972976 30789 master.cpp:5350] Sending 1 offers to framework
24baf11e-29b4-4175-bfde-e80e3f435036-0026 (Jenkins Scheduler) at
scheduler-ab2279f8-55a2-4c24-a0bd-c00703e95cde@10.80.4.31:45937
I0224 15:13:46.975461 30791 master.cpp:3673] Processing DECLINE call for
offers: [ 24baf11e-29b4-4175-bfde-e80e3f435036-O3379 ] for framework
24baf11e-29b4-4175-bfde-e80e3f435036-0026 (Jenkins Scheduler) at
scheduler-ab2279f8-55a2-4c24-a0bd-c00703e95cde@1.2.3.4:45937

And in the jenkins executor list, I see that the plugin kepp trying to
bootstrap new executor.

Alex

**Comment by geoffroyjabouley** [comment]
Hello
have you properly set the field "slave username"? This must be set to the
unix user to be used on the mesos slave machine.

2016-02-24 15:19 GMT+01:00 abeche <notifications@github.com>:

**Comment by tangicolin** [comment]
Related PR :  https://github.com/jenkinsci/mesos-plugin/pull/210

**Comment by cornelf** [comment]
Do you have more than one label set? I am running this with Mesos 0.27.1 and Marathon 0.15.3 - all good.
Or, perhaps resource offer does not match demand?

**Comment by iax7** [comment]
I'm running Mesos 0.28.2 and Jenkins 1.651.3 (also testing 2.7) with plugin version 0.13.0, (as I saw that 0.13.1 is tied to Mesos 1.0)

I'm getting disconnected. 
![image](https://cloud.githubusercontent.com/assets/6983510/18013816/890e9e3c-6b85-11e6-9faf-7c8cb128c6af.png)

my configuration is this:
![image](https://cloud.githubusercontent.com/assets/6983510/18013875/d29b2534-6b85-11e6-8644-db398b07c626.png)

**Comment by jeschkies** [comment]
1.0 and 2.0 will not aim to support 0.27.0.
