### ISSUE TITLE
Add an option to Slave Info for limiting the number of Jenkins slaves which can be created in order to keep control on resources

### ISSUE THREAD

**Issue by jlrigau** [jenkinsci/mesos-plugin#203]
When you have to manage a lot of Jenkins jobs with many different resource requirements, it is usual to configure several Slave Info with accurate resource values.

For example you can configure 4 Slave Info with specific CPU and memory requirements:
- light-weight (0.5 cpu with 512MB of memory)
- default (1 cpu with 1024MB of memory)
- medium-size (2 cpu with 4096MB of memory)
- powerful (4 cpu with 8192MB of memory)

In order to avoid that all the resources are used simultaneously, it may be interesting to have a way to indicate the maximum number of slave Jenkins can create per Slave Info.

By this way, you will be able to indicate a limit for powerful Slave Info, which will prevent to reach resource limit too quickly.

**Comment by geoffroyjabouley** [comment]
Have you tried playing a bit with provisioning variables in Jenkins?
https://github.com/jenkinsci/mesos-plugin#over-provisioning-flags

Maybe you can configure it less aggressively to avoid creation of uneeded slaves.

Btw, you can also configure a short "idle timeout" of 1minute (i think it is the minimum) in the Slave Info of powerful slave to ensure unused slaves are quickly destroyed and resources made available for others.

**Comment by maselvaraj** [comment]
@jlrigau I hope @geoffroyjabouley 's suggestion of over provisioning flags helped you. Marking this issue as closed. Please reopen if required.
