### ISSUE TITLE
Error in getWorkspace while running polling source code manager

### ISSUE THREAD

**Issue by jAlpedrinha** [jenkinsci/mesos-plugin#204]
I'm running a DCOS (v0.3.0) cluster with Jenkins installed, and I'm trying to trigger builds on git repository changes, but during polling every now and then I get an error on Polling Logs.

Stacktrace:
```
Started on Feb 3, 2016 3:48:35 PM
ERROR: Failed to record SCM polling
java.lang.NullPointerException
	at org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser.getWorkspace(MesosWorkspaceBrowser.java:38)
	at hudson.model.AbstractProject._poll(AbstractProject.java:1395)
	at hudson.model.AbstractProject.poll(AbstractProject.java:1355)
	at com.cloudbees.jenkins.GitHubPushTrigger$1.runPolling(GitHubPushTrigger.java:84)
	at com.cloudbees.jenkins.GitHubPushTrigger$1.run(GitHubPushTrigger.java:110)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:118)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'd be more than glad to share any more details you require.

**Comment by maselvaraj** [comment]
Can you please post your Jenkins - mesos cloud config ?

**Comment by jAlpedrinha** [comment]
Sure! 
I believe I understood the issue now, when polling tasks are performed, there are no executors available, since there is no slave working, and the master has 0 executors so the mesos plugin can't provide a workspace. I found a workaround for this issue by enabling one executor on the master node, which will be able to perform the polling tasks, instead of relying on slaves. Additionaly I set a tag on slaves so that build jobs can only run on slaves (avoiding using master to perform such tasks).
I still believe this is a bug, because when there are no executors available polling doesn't work, and the message could be slightly better. This could be solved by either allowing a special worker to perform such tasks, or by triggering a dedicated slave for this. 

Any thoughts? 

My mesos cloud config is below. Let me know if you need anything else.
```
Mesos native library path:                          /opt/mesosphere/lib/libmesos.so
Mesos Master [hostname:port]:                       zk://leader.mesos:2181/mesos
Description:
Framework Name:                                     jenkins
Slave username:                                     root
Framework credentials:
Jenkins URL:
Checkpointing:                                      Yes
On-demand framework registration                    Yes
    Label String:
    Jenkins Slave CPUs:                             0.5
    Jenkins Slave Memory in MB:                     512
    Maximum number of Executors per Slave:          4
    Jenkins Executor CPUs:                          0.1
    Jenkins Executor Memory in MB:                  128
    Remote FS Root:                                 jenkins
    Idle Termination Minutes:                       3
    Mesos Offer Selection Attributes:
    Additional Jenkins Slave JVM arguments:         -Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true
    Additional Jenkins Slave Agent JNLP arguments:
```

**Comment by maselvaraj** [comment]
That makes sense. 
Which version of git plugin are you running? There is an option to poll without the workspace.

**Comment by jAlpedrinha** [comment]
I am using version 0.9.0, although I now see there's an update available for 0.10.0. Was the option added in v0.10.0 ?

**Comment by maselvaraj** [comment]
https://github.com/jenkinsci/mesos-plugin/compare/mesos-0.9.0...mesos-0.10.0

**Comment by sathiya-mit** [comment]
@jAlpedrinha You are seeing the above exception since label string is empty in mesos cloud config.

On-demand framework registration                    Yes
    **Label String:**
    Jenkins Slave CPUs:                             0.5

By default it should be 'mesos' without quotes.

**Comment by sathiya-mit** [comment]
@jAlpedrinha came to know from @maselvaraj from version 0.9.0, label string can be empty. Let me fix this exception.

**Comment by sathiya-mit** [comment]
@maselvaraj Its fixed. You can close this issue.

**Comment by jAlpedrinha** [comment]
@maselvaraj @sathiya-mit 
Thank you !

**Comment by maselvaraj** [comment]
Thanks @sathiya-mit  @jAlpedrinha :+1:
