### ISSUE TITLE
Support for Maintenance Primitives

### ISSUE THREAD

**Issue by nnordrum** [jenkinsci/mesos-plugin#216]
I wanted to get a conversation started on supporting [Maintenance Primitives](http://mesos.apache.org/documentation/latest/maintenance/) in the Framework. They are discussed in this [Mesos blog post](https://mesosphere.com/blog/2015/10/07/mesos-inverse-offers/).

> ## Maintenance-ready frameworks
> 
> One important note before we continue: the interface for inverse offers was not added to the native C++ scheduler interface. Instead, a framework must use the V1 HTTP API to receive inverse offers.
> 
> For maintenance primitives, inverse offers play a key role in draining a machine of tasks prior to starting maintenance on a machine. Draining a machine means stopping all the tasks running on the machine prior to the maintenance event. Frameworks are responsible for draining machines when instructed by the Mesos master (if they don’t, the operator can still “hard drain” the machine by pulling the plug).
> 
> In the workflow provided by the maintenance primitives feature, a machine starts to drain resources as soon as it is scheduled for maintenance. (For more details on how schedules are constructed, see the maintenance documentation). All frameworks using resources on the draining machine receive inverse offers periodically, asking for the resources back.

I have yet to find an example of how to have your framework register/talk to/etc. master using the .so _and_ the HTTP API, so that's probably step one.

Just starting the conversation, so, GO!

**Comment by vinodkone** [comment]
Mesos maintenance primitives have not been ported to the SchedulerDriver interface, but you can get access to them with new HTTP API interface. So, step 1) is likely to port Jenkins Scheduler to use the new HTTP API interface.

**Comment by nnordrum** [comment]
I got the impression reading the docs that it's not an either/or situation, but not _sure_ one way or the other. I think that becomes step 1 :)

**Comment by nnordrum** [comment]
[Here's a reactive library that may be a good plugin](https://github.com/mesosphere/mesos-rxjava)

**Comment by jeschkies** [comment]
[USI](https://github.com/mesosphere/usi) uses the V1 API. Please ask for maintenance support there.
