### ISSUE TITLE
Registered framework got clean up when saving Jenkins config

### ISSUE THREAD

**Issue by hfufu** [jenkinsci/mesos-plugin#220]
I am using mesos-plugin 0.11.0.

When I go into the Jenkins "Manage Jenkins" (i.e http://jenkins:8080/configure) page and click "save" or "apply" button, the registered framework will then be immediately cleanup. 

I read the code, and find the the org.jenkinsci.plugins.mesos.Mesos.GarbageCollectorImpl.onChange method are supposed to call stopScheduler on those MesosCloud objects that are no longer valid (e.g. removed in configuration). 
However, the j.clouds in the onChange() method seems doesn't contain the existing registered and running MesosCloud because MesosCloud.equals() return false. 

Further tracing the code turns out the ContainerInfo are "different", and it turns out the root cause is missing "equals" method in the following:
- org.jenkinsci.plugins.mesos.MesosSlaveInfo.URI
- org.jenkinsci.plugins.mesos.MesosSlaveInfo.Volume
- org.jenkinsci.plugins.mesos.MesosSlaveInfo.PortMapping
- org.jenkinsci.plugins.mesos.MesosSlaveInfo.Parameter

Unless the above fields are null or having same reference, the ContainerInfo.equals() will unexpectedly return false even their values are the same.

**Comment by Vlatombe** [comment]
Thanks for logging this issue, I'll add the missing equals implementations.
