### ISSUE TITLE
Idle Pool

### ISSUE THREAD

**Issue by nnordrum** [jenkinsci/mesos-plugin#221]
Would be really nice to have an ability to say "keep 5 computers idle" so Jobs could get picked up faster. I know I could stop using single-use slaves, but I really like KNOWING that I'm starting from the same point every time, regardless of what the person did on the computer before me.

If somebody can give me some direction on how this could be implemented, I'll take a stab at it. I just don't know the internals that well.

**Comment by geoffroyjabouley** [comment]
Have you tried tuning the aggressivity of the plugin, so slaves are spawned faster?
https://github.com/jenkinsci/mesos-plugin#over-provisioning-flags

**Comment by nnordrum** [comment]
Yup. That helps, but still see longer queued times than I would like.

I get why it's doing it, but it would be nice if we could just bypass all the queuing somehow and just shortcut it to "new job" -> create slave for job (ideally with the job passed in as context for the slave creation process to be able to take hints from) -> start job on newly created slave.

I realize there may not be an extension point that makes this possible, and adding one would be outside the scope of this issue/plugin.

**Comment by Vlatombe** [comment]
There is already a proposal under way to make this possible in core : https://github.com/jenkinsci/jenkins/pull/2045
Closing this as with the current state it isn't possible

**Comment by nnordrum** [comment]
that is a fantastic issue name :) "improvements required to hack-less one-shot-executor"
