### ISSUE TITLE
Can labels be an OR so that requests match one of the label

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#224]
When you define a label in the mesos configuration. One can enter a label. I have been able to get it to work with labels that are a term. For example I can have some labels like this with each one being a distinct entry.  I would like to enter a number of terms like this.

linux || linux-86 || linux-x64 (the spaces are there for readability)

Jenkins supports this on label definitions. It may require a plugin.

Should this work?  Does anyone else need a feature like this.

**Comment by geoffroyjabouley** [comment]
You can set several labels for a type of mesos slave, just separate each
term by a space.

at job level, see
https://stackoverflow.com/questions/31367663/how-to-require-two-or-more-labels-for-a-jenkins-job

2016-04-02 2:24 GMT+02:00 Rinaldo Di Giorgio <notifications@github.com>:

**Comment by digitalrinaldo** [comment]
I just assumed it was an or like the syntax for a node ( "a|b" ) { } in pipeline

**Comment by digitalrinaldo** [comment]
Thanks
