### ISSUE TITLE
Is there rest API support for adding mesos nodes

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#225]
Can one add mesos nodes to the configuration using the rest api? I need to add 16 types of nodes and they change depending on the instance.  I would like to do this an API.

**Comment by nnordrum** [comment]
Not quite what you're asking, but you can go into the file system and edit the config.xml file and just add more "org.jenkinsci.plugins.mesos.MesosSlaveInfo" elements into the <slaveInfos>.

Just make one for reference and copy/generate/whatever the rest.

**Comment by digitalrinaldo** [comment]
Ok thanks, I wrote some groovy code that also does it. Maybe it is of some interest I will post it later.

**Comment by kmadel** [comment]
@digitalrinaldo I would be interested in your groovy approach - thanks!
