### ISSUE TITLE
Why does the node show offline yet it is building

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#226]
Two nodes are showing that they are offline yet there are active jobs on those nodes.

<img width="330" alt="screen shot 2016-04-01 at 9 13 43 pm" src="https://cloud.githubusercontent.com/assets/799458/14223581/bffd795e-f84e-11e5-9fae-4204610ee57e.png">

**Comment by geoffroyjabouley** [comment]
Are you using "Mesos Single-Use Slave" option?

**Comment by digitalrinaldo** [comment]
No I am not I don't even know what it does, there is no documentation for it. I see it in the configuration panel for manage jenkins however. I will check again and thanks for answering.

**Comment by digitalrinaldo** [comment]
I read  up on Mesos Single Slave and I am not using it.

**Comment by maselvaraj** [comment]
@digitalrinaldo I believe this is not a problem with Mesos plugin. I believe it is an existing bug in Jenkins where JNLP broke but Jenkins still assumes the slave is available. I could not find the bug id though.

**Comment by rmathure** [comment]
For the cleanup, I would just stop the task running on Mesos slave that is offline. Then Idle termination should clean up up your slave. My patch here does that https://github.com/rmathure/mesos-plugin/commit/e5ce51d5a081000fcad61eaaaf3b4688ad1f29ff

**Comment by jeschkies** [comment]
@digitalrinaldo, did it work for you?

**Comment by jeschkies** [comment]
Closing for lack of response.
