### ISSUE TITLE
Unable to remove failed "agents"

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#230]
I have some agents that are no longer running in the mesos cluster but they are still showing up in the mesos UI commonly found at 5050.  I would like to delete them but I cannot.  Can someone suggest where to  start looking to see what piece of software is broken.

<img width="337" alt="screen shot 2016-04-12 at 4 58 11 am" src="https://cloud.githubusercontent.com/assets/799458/14459244/9a0ae3b0-006b-11e6-99cb-eab52c4ad05a.png">

**Comment by maselvaraj** [comment]
I believe this is same as https://github.com/jenkinsci/mesos-plugin/issues/226
