### ISSUE TITLE
Docker feature not available

### ISSUE THREAD

**Issue by getstek** [jenkinsci/mesos-plugin#231]
Hi,

I am using the latest stable version of Jenkins with the Mesos 0.27 and the latest release of the Mesos plugin for Jenkins from the plugin repository and when it comes to configuration I have no option to select Docker as the Jenkins slave type. 

In an attempt to check if it was a plugin problem, I then downloaded the latest code from Github and built the Jenkins/Mesos plugin from scratch, same issue. Are there dependencies specific to Docker which are not documented?

Jenkins version: 
jenkins-1.642.4-1.1.noarch

Java version:
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

Jenkins plugin version (current in use): 
latest built from Git (0.12.1-SNAPSHOT)

Mesos version: 
mesos-0.27.0-0.2.190.centos701406.x86_64

<img width="1237" alt="screen shot 2016-04-13 at 9 27 26 am" src="https://cloud.githubusercontent.com/assets/537885/14483698/b1bb1b70-015a-11e6-8c6c-4f7403e6b6f1.png">

Any thoughts on why the Docker containerizer option isn't available?

**Comment by geoffroyjabouley** [comment]
Hi

there is an Advanced button for each slave info. This is where you'll
define the docker image to be used, and others docker stuffs

[image: Images intégrées 1]

[image: Images intégrées 2]

Cheers

2016-04-13 7:34 GMT+02:00 Stephen Knight <notifications@github.com>:

**Comment by getstek** [comment]
Hi Geoffrey,

Thanks for the response back, I can't see the Docker tab though. I've got through the Advanced Tab and set the Jenkins slave resources for example but there's no Docker option - from what you are saying I should see it as per the screenshot here: https://github.com/jenkinsci/mesos-plugin/issues/157

But no such luck. Could it be a missing plugin? I also tried to build the plugin against the updated Mesos version by modifying pom.xml and running 'maven package'. Still stuck.

**Comment by geoffroyjabouley** [comment]
Hi
have you scrolled to the top right of the config page?
What you see in https://github.com/jenkinsci/mesos-plugin/issues/157 only
appears after you click on the Advanced button, under the "Additional
Jenkins Slave Agent JNLP arguments" option line.

[image: Images intégrées 1]

2016-04-13 9:39 GMT+02:00 Stephen Knight <notifications@github.com>:

**Comment by geoffroyjabouley** [comment]
Have you been able to configure Docker?

**Comment by getstek** [comment]
I have, thank you. The option wasn't very clear to find, but it is sorted now. Thanks.
