### ISSUE TITLE
No 'Marathon Deployment' option in 'Add post-build action' drop-down in configure page

### ISSUE THREAD

**Issue by alexraju** [jenkinsci/mesos-plugin#237]
I have installed jenkins from DC/OS universe and mesos-plugin is automatically configured and is working fine. Issue here is No 'Marathon Deployment' option in 'Add post-build action' drop-down in configure page. Everything else is working fine. I have created successful builds. What could be the reason for this.

**Comment by Vlatombe** [comment]
No idea, but it has probably nothing to do with this plugin since it doesn't talk to Marathon...

**Comment by geoffroyjabouley** [comment]
Hello

i think it is linked to the implementation of the Jenkins Mesos plugin done by Mesosphere for Velocity

https://docs.mesosphere.com/usage/services/velocity/marathon-deployment-on-velocity-walkthrough/
