### ISSUE TITLE
Jenkins framework getting registered and unregistered continuosly

### ISSUE THREAD

**Issue by vidyajothiraman** [jenkinsci/mesos-plugin#238]
Hi
I have installed mesos plugin on Jenkins server and added a new mesos cloud. But in mesos this jenkins framework is getting unregistered immediately as soon its registered. 

Details 
Jenkins version - 2.5 
Mesos plugin version - 0.12.0
Mesos master version - 0.28.0
Installed mesos 0.28.0 rpm on the Jenkins master server. 

Mesos cloud config attached 
![cloud_mesos](https://cloud.githubusercontent.com/assets/15954794/15814076/b54e3cd4-2be1-11e6-8881-aa1d0dbfa651.jpg)

**Comment by vinodkone** [comment]
Looks like the Mesos master is unable to talk to the Jenkins master/scheduler. What do master logs say? Are there any firewall or networking rules that stop the mesos node from talking to the Jenkins node on the given port?

**Comment by vidyajothiraman** [comment]
Hi Vinod
Am not sure what fixed but now the Jenkins framework got registered :) But there is a different issue now. Mesos framework is not able to start the job in slave, it says 

: Failed to fetch 'host-name:8080/jnlpJars/slave.jar': A relative path was passed for the resource but the Mesos framework home was not specified. Please either provide this config option or avoid using a relative path
Failed to synchronize with slave (it's probably exited)

**Comment by maselvaraj** [comment]
Are you able to download slave.jar URL using wget  ?

I don't understand why do you need to configure Mesos framework home here. Mesos slave process should know where Mesos work directory is and the jenkins tasks should automatically use the folder within mesos work dir.

**Comment by maselvaraj** [comment]
Also, I suspect you have configured a wrong Jenkins url in Mesos. Try if this works : hostname:8080/**jenkins**/jnlpJars/slave.jar

**Comment by vinodkone** [comment]
Failed to fetch 'host-name:8080/jnlpJars/slave.jar'. Try with adding a "http://" prefix to the "Jenkins URL" field.

**Comment by vidyajothiraman** [comment]
Hi Vinod and Mani

Silly me :) As you had said I had done a mistake of missing http:// in Jenkins Mesos cloud.  

Was breaking my head yesterday and found it out by comparing the stderr of a setup where things work 

stderr from a working setup 
: I0606 10:58:15.363909 21281 fetcher.cpp:379] Fetching URI '**http://*.***.**.**:9090/jnlpJars/slave.jar'**
I0606 10:58:15.364008 21281 fetcher.cpp:250] Fetching directly into the sandbox directory

stderr of the setup where i got error : 
I0607 19:12:37.390153 19490 fetcher.cpp:379] Fetching URI '**hostname:8080/jnlpJars/slave.jar**'
I0607 19:12:37.390198 19490 fetcher.cpp:250] Fetching directly into the sandbox directory

It would be good if Jenkins has the intelligence to correct this. Like when we give http:// in mesos url while creating mesos cloud, it says "Please omit 'http://'." Like wise it should also say "Please add http://" if it is missed in Jenkins url :-)
