### ISSUE TITLE
Mesos CLI giving error 

### ISSUE THREAD

**Issue by vidyajothiraman** [jenkinsci/mesos-plugin#239]
Hi 
On a CentOS server where we have configured mesos 0.28.2, I am getting error when running "mesos ps"
# mesos ps
Traceback (most recent call last):
  File "/usr/bin/mesos-ps", line 10, in <module>
    from mesos import http
ImportError: cannot import name http

Tried setting PYTHONPATH to be "/usr/lib/python2.7/site-packages/" but stil not helping. 

Python version is 2.7.5
Saw this https://issues.apache.org/jira/browse/MESOS-3149 , but not getting exactly what action is required. 
If this is not the right forum please direct me to the correct one. Thanks in advance

**Comment by maselvaraj** [comment]
You can ask your question here : https://groups.google.com/forum/#!forum/meso-user

**Comment by vinodkone** [comment]
Never heard of this group? Who maintains it? The official one is linked from mesos website. 

@vinodkone

**Comment by geoffroyjabouley** [comment]
I think people are misusing this meso-user google group, which initially
deals with http://mesowest.utah.edu/ API ...

2016-06-10 5:23 GMT+02:00 Vinod Kone <notifications@github.com>:

> Never heard of this group? Who maintains it? The official one is linked
> from mesos website.
>
> @vinodkone
>
>
> > On Jun 9, 2016, at 10:37 PM, Manivannan Selvaraj <

**Comment by maselvaraj** [comment]
Oops, my bad. I just gave a wrong URL[which popped up when I googled for "mesos google group"]. Should have been http://mesos.apache.org/community/

**Comment by vidyajothiraman** [comment]
Thanks Mani
