### ISSUE TITLE
Adjusting slaveInfos causes JenkinsScheduler to reconnect

### ISSUE THREAD

**Issue by nnordrum** [jenkinsci/mesos-plugin#244]
When you change a value in a slaveInfo, specifically a CPU setting, it restarts the JenkinsScheduler, which terminated all running jobs. Not sure why it would need to do a reconnect when changing a slaveInfo.

It would be a nice improvement if it was more selective as to when it recreated the JenkinsScheduler.

**Comment by titosand** [comment]
I am currently working on a fix for this! When implemented, changes to the MesosCloud config will not terminate all running jobs.

**Comment by nnordrum** [comment]
#246
