### ISSUE TITLE
Mesos slave hostname in build output is null

### ISSUE THREAD

**Issue by damomurf** [jenkinsci/mesos-plugin#247]
I'm seeing jobs launched display the following right at the beginning of the console output in Jenkins:

```
09:51:11 Started by user <user>
09:51:14 Mesos slave(hostname): null
09:51:14 [EnvInject] - Loading node environment variables.
09:51:14 Building remotely on mesos-jenkins-e6b17268c13e4e26b0d261372e46b493-... (...) in workspace ...
...
```

The mesos slave hostname would be really handy at times. Is this a bug or something I've done wrong?

**Comment by maselvaraj** [comment]
Are you using docker ? If yes,  the hostname inside the docker container might be null.

**Comment by damomurf** [comment]
We are using Docker, yes - is this something that shouldn't work at all with Docker? I could have sworn I've seen it work previously under Docker.

**Comment by nnordrum** [comment]
If you're running your containers as privileged, you can mount the docker socket in the container and ask the docker engine where it's running.

**Comment by sbeaulie** [comment]
Definitely a bug.

Mesos plugin does a [computer.getHostName()](https://github.com/jenkinsci/mesos-plugin/blob/b0f9968d786daf41c48544945b53cd23dc7e291c/src/main/java/org/jenkinsci/plugins/mesos/listener/MesosRunListener.java#L47-L47)

In jenkins core `hudson.model.Computer` that function [tries to ping](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java#L1263) and fails and fallsback to using `null` as the hostname

I have enabled logging on `hudson.model.Computer` and with docker, as expected you get the container IP, which by default is private and unreachable.
```
172.17.0.6 didnt respond to ping
```

**Comment by jeschkies** [comment]
@sbeaulie, do you see the bug with 1.0 or 2.0 of the plugin and Mesos 1.x?

**Comment by jeschkies** [comment]
Closing for lack of response.
