### ISSUE TITLE
Docker slaves launched with invalid hostname when label contains underscores

### ISSUE THREAD

**Issue by thecubed** [jenkinsci/mesos-plugin#251]
Hi all,

It would appear that if the label string for a Docker slave contains an underscore (i.e. `j_node5`) , Mesos tries to launch the Docker image with `--hostname mesos-jenkins-(UUID)-j_node5`.

Docker then complains that this is an invalid hostname and fails to launch the Jenkins node.
(This continues forever, filling up Jenkins with slaves that don't exist in Mesos)

A simple fix would be to strip the hostname of characters that aren't allowed as hostnames here: https://github.com/jenkinsci/mesos-plugin/blob/70fe128ca0d0e3f5d5718dbd9e8953133096331e/src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java#L708 (or so it appears).

Thanks!

**Comment by matt2000** [comment]
I'm having the same symptoms, but removing the underscore from my label did not resolve the issue. How do you know that "Docker the complains that this is an invalid hostname" ? Where can I find the logs indicating this? I see no such thing in the jenkins node launch log, before or after changing the label.

**Comment by thecubed** [comment]
The error was visible in the Mesos webui for the task. If you look at the bottom half of your Mesos webui, you should see the failed/finished tasks, and the Jenkins launch attempts should be there. The error was visible in one of the stderr/stdout links in the sandbox page.

It's also possible that your node name makes the Docker hostname too long - I think Docker enforces the 64-character limit on hostnames, so if the strings "mesos-jenkins-(whatever uuid here)-(your slave label here)" is too long it'll fail to launch as well.

**Comment by epkabeg** [comment]
We are having issues with this as well. Since a recent version of Docker, it enforces proper hostnames.

When the plugins is configured with "Docker Image Can Be Customized" it adds a : to the hostname so this functionality is broken with newer Docker versions.

**Comment by sbeaulie** [comment]
Did anyone find a workaround for this? Our mesos slave label ends up longer than 64, contains hyphens but no underscore and contains ":" to specify the image version we want

**Comment by jeschkies** [comment]
I think this has been fixed in #367.
