### ISSUE TITLE
Exponential back-off

### ISSUE THREAD

**Issue by nrshrivatsan** [jenkinsci/mesos-plugin#254]
# Proposal

Implement exponential back-off in Jenkins Mesos Plugin [JMP]
# Expected behavior

| Time X (in seconds) | Plugin | Mesos Master |
| --- | --- | --- |
| 0 | Does Nothing | Mesos has resources requested |
| 1 | JMP requests for resources to build code | Mesos doesn't have requested resources to offer |
| 2 | Jenkins Mesos Plugin retries after **2** seconds | Mesos doesn't have requested resources to offer |
| 4 | Jenkins Mesos Plugin retries after **4** seconds | Mesos doesn't have requested resources to offer |
| 8 | Jenkins Mesos Plugin retries after **8** seconds | Mesos doesn't have requested resources to offer |
| 16 | Jenkins Mesos Plugin retries after **16** seconds | Mesos doesn't have requested resources to offer |
| 32 | Jenkins Mesos Plugin retries after **32** seconds | Mesos doesn't have requested resources to offer |
| ... | Jenkins Mesos Plugin retries after **...** seconds | Mesos doesn't have requested resources to offer |
| ... | Jenkins Mesos Plugin Stops requesting, display a disposable JQuery banner on Jenkins Master | N/A |

**Comment by jeschkies** [comment]
@nrshrivatsan, I need a few more details. What should be backed of? In 2.0 a client launch should time out in five minutes. There is no notion of an exponential back-off though. Should the plugin retry after the first launch failed?

**Comment by jeschkies** [comment]
Closing for lack of response.
