### ISSUE TITLE
Release notes missing

### ISSUE THREAD

**Issue by ktf** [jenkinsci/mesos-plugin#255]
Looks like release notes are missing for 0.12.x and 0.13.x, at least on the Jenkins JIRA. Can they be added?

**Comment by Vlatombe** [comment]
All releases notes are posted on the jenkins-mesos mailing list.

**Comment by ktf** [comment]
I would find it more natural that the release notes are on the [Jenkins Wiki page](https://wiki.jenkins-ci.org/display/JENKINS/Mesos+Plugin) or in the Github releases page, so that clicking in Jenkins Plugin Manager or in Github gives sensible results. Moreover, if I google for: "mesos jenkins release notes" or "jenkins mesos release notes" I get pointers to both the above mentioned pages, but nothing that links to the mailing list.
