### ISSUE TITLE
Entrypoint in Dockerfile will be automatically overridden by "/bin/sh -c"

### ISSUE THREAD

**Issue by xiajidexue** [jenkinsci/mesos-plugin#257]
Descriptions:
_Entrypoint in Dockerfile will be automatically be overridden  by Java slave process, but CMD in Dockerfile will not be overridden.  I think this problem will block the users who want to adopt this plugin as no way to identify which executable should be run when a container is started from our images, and I tried to use **Use custom docker command shell** in Mesos Cloud section to work around it, but still fails, a defect has been tracking it for also year: https://github.com/jenkinsci/mesos-plugin/issues/157_

**Entrypoint**: /bin/bash --login -- /entrypoint.sh
**Java Slave process**: /bin/sh -c 'java -DHUDSON_HOME=jenkins -server -Xmx640m -Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true -jar ${MESOS_SANDBOX-.}/slave.jar -noReconnect -secret ... mesos-jenkins-do/slave-agent.jnlp

Expected (Shown by **COMMAND** via **docker ps** command):
"/bin/bash --login -- /entrypoint.sh /bin/sh -c 'java -DHUDSON_HOME=jenkins -server -Xmx640m -Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true -jar ${MESOS_SANDBOX-.}/slave.jar -noReconnect -secret 4026fda6995da3083527505a05d92cadcb5e00eb0b477f0ff357097fadd59ae7 -jnlpUrl http://jenkins.xxx.net/computer/mesos-jenkins-09a5fb6724b44ed4bf10339c6aae4f1d-mesos-jenkins-do/slave-agent.jnlp'"
But in fact (Shown by **COMMAND** via **docker ps** command, the command "/bin/bash --login -- /entrypoint.sh" in Entrypoint override):
"/bin/sh -c 'java -DHUDSON_HOME=jenkins -server -Xmx640m -Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true -jar ${MESOS_SANDBOX-.}/slave.jar -noReconnect -secret 4026fda6995da3083527505a05d92cadcb5e00eb0b477f0ff357097fadd59ae7 -jnlpUrl http://jenkins.xxx.net/computer/mesos-jenkins-09a5fb6724b44ed4bf10339c6aae4f1d-mesos-jenkins-do/slave-agent.jnlp'"

**Comment by xiajidexue** [comment]
I found similar problem: https://github.com/mesosphere/marathon/issues/2373

**Comment by fsfshijm** [comment]
have the same problem,  any update?

**Comment by vimalprakashts** [comment]
yes , I also have same problem :(

**Comment by hibbert** [comment]
+1

**Comment by gfrntz** [comment]
+1

**Comment by mainred** [comment]
any progress?

**Comment by zhangxinlong633** [comment]
+1
