### ISSUE TITLE
JNLP calling back to http even if https is specified

### ISSUE THREAD

**Issue by nnordrum** [jenkinsci/mesos-plugin#258]
Any reason we shouldn't do this:

https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/mesos/MesosComputer/mesos-slave-agent.jnlp.jelly

```
         <argument>-url</argument>
-        <argument>${app.rootUrlFromRequest}</argument>
+        <argument>${rootURL}</argument>
       </application-desc>
```

app.rootUrlFromRequest doesn't seem to be resolving to https even when HTTPS is set in JENKINS_URL, the Mesos plugin jenkins root, and specified in the URL when requesting the JNLP file.

**Comment by Vlatombe** [comment]
The slave may not have access to rootURL.

**Comment by nnordrum** [comment]
But where is it getting the http from in this situation? How can I force it to request https?

**Comment by Vlatombe** [comment]
Are you running Jenkins directly on https or do you have a reverse proxy doing the ssl termination?

**Comment by nnordrum** [comment]
reverse proxy doing the SSL termination. that's why it's getting app.rootUrlFromRequest as http.

Should we just add another jnlpUrl field?

Wait, how is this supposed to work if rootUrl may not be accessible?

```
 <jnlp spec="1.0+"
        codebase="${rootURL}computer/${h.encode(it.node.nodeName)}/">
```

**Comment by nnordrum** [comment]
reverse proxy doing the SSL termination. that's why it's getting app.rootUrlFromRequest as http.

Should we just add another jnlpUrl field?

Wait, how is this supposed to work if rootUrl may not be accessible?

```
 <jnlp spec="1.0+"
        codebase="${rootURL}computer/${h.encode(it.node.nodeName)}/">
```

**Comment by Vlatombe** [comment]
That is why you have a field 'Jenkins URL' in the cloud configuration

Inline help:

>http://HOST:PORT where Jenkins is actually running. For ex: http://myjenkinshost:8080. Jenkins URL provided in Jenkins location configuration could be a reverse proxy URL. In that case you can override it by specifying actual Jenkins URL here. This URL would be used by Jenkins slaves spawned by Mesos plugin to talk to Jenkins Master.

**Comment by Vlatombe** [comment]
You must configure your reverse proxy to add the header "X-Forwarded-Proto https".

**Comment by nnordrum** [comment]
Let me amend then:

since [`hudson.remoting.jnlp.Main.urls`](https://github.com/jenkinsci/remoting/blob/master/src/main/java/hudson/remoting/jnlp/Main.java#L76) is a List\<URL\>, any reason we shouldn't add `${rootURL}` _and_ `${app.rootUrlFromRequest}` as `-url` arguments? 

That way if one fails, it will at least try the other.

**Comment by Vlatombe** [comment]
That's possible, could you file a pull request?

**Comment by nnordrum** [comment]
Sorry, kept forgetting to do this, and then _had_ to do it tonight for something else.

**Comment by maselvaraj** [comment]
Thanks @nnordrum for the PR!
