### ISSUE TITLE
Single use slave in piepeline

### ISSUE THREAD

**Issue by cazino** [jenkinsci/mesos-plugin#262]
When setting up a 'standard' job in jenkins, one can tick the 'Mesos Single-Use Slave' box so that only one job can get executed on a slave before the slave gets deleted.

When setting up a job with the new 'pipeline' feature, one has to write the job instructions in a 'node' block :
    node('node_label) {
    }

Is is possible to specify the 'Mesos Single-Use Slave' thing in a pipeline job ?
I switched to pipeline jobs recently and the nice isolation I had before is gone now.

Thanks

**Comment by ryoichitaniguchi** [comment]
Similar to this topic... sometimes I want to force enable "Mesos Single-Use Slave" feature, bcoz in my case mesos-master apt to assign same node when its still active ( till "Idle Termination Minutes")  then causes disk full occasionally.
Hope this option will be flexible to configure..

**Comment by xiajidexue** [comment]
same issue encountered.

**Comment by maselvaraj** [comment]
As I understand, you want a config in mesos cloud that can say every slave provisioned through mesos should be 'Single use slave' will that work ?

**Comment by maselvaraj** [comment]
I've raised this PR with global config for making Mesos Single use slave feature default for all the jobs that are created/updated: https://github.com/jenkinsci/mesos-plugin/pull/275 .

**Comment by geoffroyjabouley** [comment]
Hello
i think it is a good first step to enable Single Use Slave feature in
Pipeline. But maybe it won't suit all potential use cases ;)
Next improvement shall be the support @node level, but not sure how to
implement that. Are other Cloud plugins also offering this Single Use
feature?

2016-12-09 8:36 GMT+01:00 Manivannan Selvaraj <notifications@github.com>:

**Comment by maselvaraj** [comment]
Thanks @geoffroyjabouley for the inputs. Jclouds plugin is one that I know which supports one of slaves : https://github.com/jenkinsci/jclouds-plugin/blob/master/jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsOneOffSlave.java
