### ISSUE TITLE
Randomise slave load on Mesos

### ISSUE THREAD

**Issue by fragpit** [jenkinsci/mesos-plugin#263]
Hi! 

trying to solve some problem with Mesos. For now, Mesos loads one agent(slave) as hard as possible, but I want it to spread jobs across all agents.. As I see, it's better to run three jobs on three agents, than on one. Is it possible to randomise job scheduling?

Or perhaps, I have such scenario. 2 large servers and one mini. I want to schedule Jobs on mini by default, and if it's not enough resources, then proceed to large servers. How can I achieve this goal? Is it possible to set priority for agents(slaves) to specify on which agent I want job to run at first?

**Comment by maselvaraj** [comment]
You can achieve that with mesos roles : http://mesos.apache.org/documentation/latest/roles/ 
Mesos plugin supports roles to be configured.
