### ISSUE TITLE
Shared workspaces 

### ISSUE THREAD

**Issue by fragpit** [jenkinsci/mesos-plugin#265]
Hi, guys!

Seems, that "Execute concurrent builds if necessary" option is useless (and often harmful), when building on different slaves (containers), but on one physical server, when workspace is persistent and mounted into container. 

How did you solve this issue?

**Comment by maselvaraj** [comment]
@fragpit You might want to check out docker volume plugin with which you can attach/detach a volume for your build

**Comment by fragpit** [comment]
Also, I found, that docker supports such keys:

docker run -v /jenkins_home:/jenkins_home -v /jenkins_home/workspace 

but mesos plugin is not. Container can't start. 

So the problem is that I need to have jenkins_home mounted, but I want workspace folder to be temporary. Now I use workaround, and don't mount jenkins_home for concurrent builds.

**Comment by jeschkies** [comment]
@fragpit, does it work with the newest plugin?

**Comment by fragpit** [comment]
@jeschkies  sorry, I'm not using mesos anymore.

**Comment by jeschkies** [comment]
Sad to hear that. Is there a special reason why you dropped Mesos?

**Comment by fragpit** [comment]
Well, at first, my team switched to gitlab. And as for me k8s infrastructure  seems more interesting for build agents

**Comment by jeschkies** [comment]
Thanks for the reply. So you are not using Jenkins anymore or did you switch to Jenkins X?
