### ISSUE TITLE
feature request: Docker once retention strategy like 'Availability' in Docker plugin 

### ISSUE THREAD

**Issue by fsfshijm** [jenkinsci/mesos-plugin#267]
Background:  When I using mesos plugin and enable 'Use Docker Containerizer Container Type',  mesos will run a docker container as the Jenkins slave,  and also configure 'Idle Termination Minutes' which's value is 1;

Issues:  In some times(one build is running, and another build is pending), two builds of one Jenkins job will run in the same salve which isn't what we want, each build of our Jenkins job need a clean slave environment.  

So, could you guys supply a feature like the feature 'Availability' in Jenkins Docker plugin, then I can use 'docker once retention strategy'

**Comment by maselvaraj** [comment]
This feature is already available in Jenkins Mesos plugin. In jenkins job configuration you can see an option "Mesos Single-Use Slave" . If you check it, the slave will be destroyed as soon as a build completes.

**Comment by fsfshijm** [comment]
@maselvaraj, Cool,  tested, it's workable for me,   thanks very much.
