### ISSUE TITLE
Jenkins framework unregisters from Mesos frequently

### ISSUE THREAD

**Issue by vidyajothiraman** [jenkinsci/mesos-plugin#268]
Hi
I have registered Jenkins frame work on Mesos and able to launch jobs.  But some times I see the framework goes to completed framework list in Mesos. Any help as why its going like this? 
I have got to save this Mesos cloud from Jenkins once again to register this framework on Mesos.

**Comment by maselvaraj** [comment]
Have you configured Mesos plugin with 'On Demand registration' ? If yes, then jenkins will connect to mesos only when there is a build in queue and disconnect from mesos after the build is complete.

**Comment by vidyajothiraman** [comment]
Hi Mani

I have made it as no in this option below: 
 	On-demand framework registration	 Yes  No

**Comment by jeschkies** [comment]
@vidyajothiraman, did you try 1.0 or 2.0 of the plugin?

**Comment by jeschkies** [comment]
Closing for lack of response.
