### ISSUE TITLE
GIT code visible from Mesos UI

### ISSUE THREAD

**Issue by vidyajothiraman** [jenkinsci/mesos-plugin#271]
Hi

We have setup continuous integration between GITHub, Jenkins and Mesos. ie, the Jenkins jobs get triggered on Mesos slaves. 
Since we have git integrated here, when i was browsing the Mesos UI, I came across I am able to see the source code from GIT accessible from workspace of a slave in Mesos 
This can seen from "Frameworks-> Active Frameworks->Click on sandbox of a completed task"
Here under workspace section I see the cloned content visible in Jenkins-> workspace folder 

So does it mean if any one has access to Mesos UI they can see the source code of any framework if cloned from GIT? 

How do we restrict access to a particular team alone to see the contents of a framework? As far as i see there is security enabled for registering a framework on Mesos. But not to see the contents of a framework on a Mesos cluster. Please correct me if am wrong 

Thanks 
Vidya

**Comment by maselvaraj** [comment]
If you use any other directory other than the Mesos sandbox directory as workspace, then you should be good.

**Comment by maselvaraj** [comment]
"Remote FS Root" in mesos cloud configuration will work. "Enables the user specify JENKINS_HOME of the jenkins slave. Relative path is relative to the Mesos slave/task home. Defaults to "jenkins" if empty. Change is applicable to the new mesos/jenkins slaves."

**Comment by vidyajothiraman** [comment]
Thanks Mani, i made "Remote FS Root" as /opt/jenkins. Now git clone happens under /opt/jenkins in mesos slave machine.  I am not able to see the contents from Mesos UI 
But is there any way we can automatically clean this dir from slave machine once the job is over? Because in a mesos slave shared by different teams, we do not want the git cloned code to remain in slave even after the job gets over.

**Comment by geoffroyjabouley** [comment]
Hello
maybe you can use the "Clean workspace" plugin to automatically wipe out
your workspace as a Post-Build step.
Another approach is to run your Jenkins slaves in docker container, so the
code is not directly available on the machine FS but rather in the
container FS. Then you can configure a policy in Mesos to clean up old
containers every hours for example...

2016-11-22 10:19 GMT+01:00 vidyajothiraman <notifications@github.com>:

**Comment by vidyajothiraman** [comment]
Thanks @geoffroyjabouley let me check these options..
