### ISSUE TITLE
All jobs's Mesos Single-Use Slave are selected in default

### ISSUE THREAD

**Issue by xiajidexue** [jenkinsci/mesos-plugin#272]
In order to a jenkins-mesos slave will not be reused, i want to rebuild mesos-plugin to support All jobs's **Mesos Single-Use Slave** are selected in default, but i cannot find the code place to map a job's  **Mesos Single-Use Slave**,  is there a jelly file mapped to  **Mesos Single-Use Slave** in a jenkins job's Configure?

https://github.com/jenkinsci/mesos-plugin/tree/master/src/main/resources/org/jenkinsci/plugins/mesos/MesosSingleUseSlave

![123321](https://cloud.githubusercontent.com/assets/6821543/20555853/1273bd56-b19f-11e6-854f-4e39aa03630b.png)

**Comment by ryoichitaniguchi** [comment]
jfyi, I prepared groovy script to force all jobs to enable to check "mesos single use slave" checkbox as workaround.
https://gist.github.com/ryoichitaniguchi/23f855c3eba0b0b05b44d2a5ae0d6d5b

**Comment by xiajidexue** [comment]
hi Ryoichi, thanks a lot for your quick response, i just tried groovy scripts you attached, but it dose not work, a job's **Mesos Single-Use Slave** still unselected.

**Comment by ryoichitaniguchi** [comment]
Hi, sorry for inconvenience.  Script is targeting hard-coded label "DOCKERNODE", and it just iterating jobs having(assigned) this label and add configuration one by one if checkbox is missing.  So I think you need to modify "DOCKERNODE". I tested with matrix, freestyle and maven job in my environment.

**Comment by xiajidexue** [comment]
@Ryoichi, i see, thanks a lot for your great help:)

**Comment by maselvaraj** [comment]
Thanks @ryoichitaniguchi for the groovy! 
Marking this issue as closed.

**Comment by maselvaraj** [comment]
https://github.com/jenkinsci/mesos-plugin/pull/275
