### ISSUE TITLE
Node Offline 

### ISSUE THREAD

**Issue by gvenka008c** [jenkinsci/mesos-plugin#278]
I am running a simple job using the meson-plugin. It always shows "Node as Offline". I see the below details when I click on one of the Nodes. Thoughts on how to fix this issue?

<img width="330" alt="screen shot 2016-12-23 at 2 53 34 pm" src="https://cloud.githubusercontent.com/assets/13439779/21461464/ab7cf30e-c91f-11e6-9935-758103e17491.png">

<img width="608" alt="screen shot 2016-12-23 at 2 53 42 pm" src="https://cloud.githubusercontent.com/assets/13439779/21461469/b0bf9d80-c91f-11e6-9692-dde11bbda793.png">

**Comment by jbinglei** [comment]
hello，i meet the same problem,how do you solve it?
