### ISSUE TITLE
Job queued and jenkins manage page hint: Some Mesos slaves cannot be provisioned on the following labels.

### ISSUE THREAD

**Issue by sic-z** [jenkinsci/mesos-plugin#280]
When a job was excuted there is a hint on my jenkins manage page:

> **Some Mesos slaves cannot be provisioned on the following labels:
>  mesos
> Please review the Mesos plugin configuration and check the cluster capacity to make sure the tasks can be launched successfully.** 

And jobs were queueing with black clock, mesos slave was offline. A few minutes later, jobs run normally and hint gone.

My jenkins version is 2.7.1 and mesos plugin version is 0.13.1.

What's meaning of this? Is it a problem? Is anything wrong?

**Comment by maselvaraj** [comment]
Did you have enough capacity in Mesos and what does Mesos logs say ?

**Comment by SeanZhu20** [comment]
@maselvaraj 
Thanks for your reply.

It showed again, then I check mesos logs on master, I got this:
> Jan 13 15:03:10 master2 mesos-master[4358]: W0113 15:03:10.731811  4377 master.cpp:5736] Received status update TASK_LOST (UUID: b62243df-1b1e-4941-9663-7ef10d081de5) for task
> mesos-jenkins-905ec9677ed04491ac80b959996cd398-mesos of framework b895280c-fa72-4342-a8ee-0183957ea88a-0015 from agent b895280c-fa72-4342-a8ee-0183957ea88a-S72 at slave(1)@192.
> 168.1.126:5051 (slave76.g1.r5.nj) for an unknown framework
> 
> Jan 13 15:03:10 master2 mesos-master[4358]: W0113 15:03:10.731874  4377 master.cpp:5745] Could not lookup task for status update TASK_LOST (UUID: b62243df-1b1e-4941-9663-7ef10d
> 081de5) for task mesos-jenkins-905ec9677ed04491ac80b959996cd398-mesos of framework b895280c-fa72-4342-a8ee-0183957ea88a-0015 from agent b895280c-fa72-4342-a8ee-0183957ea88a-S72
>  at slave(1)@192.168.1.126:5051 (slave76.g1.r5.nj)

**Comment by jeschkies** [comment]
@sic-z, do you still see this issue?

**Comment by sic-z** [comment]
> @sic-z, do you still see this issue?

No, it's long time ago
