### ISSUE TITLE
Node is offline when Mesos is placed at the remote machine

### ISSUE THREAD

**Issue by yarps95** [jenkinsci/mesos-plugin#281]
I use Jenkins ver. 1.609.3 and Mesos plugin ver. 0.14.1-SNAPSHOT at my local machine (with macOS). I have a simple job with `mesos` label.  My configuration for Mesos plugin:

![image](https://cloud.githubusercontent.com/assets/17267026/21983816/852c6838-dc25-11e6-80bf-f84ad317fa10.png)

If I launch Mesos at my machine:
```
./mesos-master --registry=in_memory --ip=192.168.3.35 # or 127.0.0.1
./mesos-slave --work_dir=/Users/user/mesos_slave_workdir --master=192.168.3.35:5050 # or 127.0.0.1
```
It works fine and my build starts.

But if I launch Mesos at different (also macOS, the same 1.1.0 version of Mesos) machine my build never gets started, because Jenkins node remains offline forever. The only thing I change in Jenkins configuration is IP of Mesos Master. I can access web interface of Mesos (and so 'Test connection' button works fine).

`JAVA_HOME` variable is set, username at the remote machine is `jenkins`, username at the local machine is `user` but I also tried with `jenkins`. At local machine it works fine no matter whether I specify `127.0.0.1` or `192.168.3.35` when launching Mesos master and slave. I use Mesos ver. 1.1.0 (in plugin's pom there's 1.0.0 Mesos version but I don't think this is the problem since everything works fine locally).

In Mesos master log I see multiple records like the following:
```
I0116 19:10:37.537348 92004352 master.cpp:2596] Received SUBSCRIBE call for framework 'Jenkins Scheduler' at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047
I0116 19:10:37.537463 92004352 master.cpp:2672] Subscribing framework Jenkins Scheduler with checkpointing disabled and capabilities [  ]
E0116 19:10:37.537832 95223808 process.cpp:2154] Failed to shutdown socket with fd 15: Socket is not connected
I0116 19:10:37.537901 93614080 hierarchical.cpp:275] Added framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006
I0116 19:10:37.538122 92004352 master.cpp:1297] Framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 (Jenkins Scheduler) at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047 disconnected
I0116 19:10:37.538148 92004352 master.cpp:2902] Disconnecting framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 (Jenkins Scheduler) at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047
I0116 19:10:37.538170 92004352 master.cpp:2926] Deactivating framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 (Jenkins Scheduler) at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047
I0116 19:10:37.538203 92004352 master.cpp:1310] Giving framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 (Jenkins Scheduler) at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047 0ns to failover
E0116 19:10:37.538280 95223808 process.cpp:2154] Failed to shutdown socket with fd 15: Socket is not connected
I0116 19:10:37.538399 93614080 hierarchical.cpp:386] Deactivated framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006
W0116 19:10:37.538450 92004352 master.cpp:6382] Master returning resources offered to framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 because the framework has terminated or is inactive
I0116 19:10:37.538709 92004352 master.cpp:6369] Framework failover timeout, removing framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 (Jenkins Scheduler) at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047
I0116 19:10:37.538734 92004352 master.cpp:7103] Removing framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006 (Jenkins Scheduler) at scheduler-a5d926fd-f61d-448e-b7ab-40159951cde5@127.0.0.1:57047
I0116 19:10:37.539314 91467776 hierarchical.cpp:337] Removed framework 39b5afc3-2c62-4427-a758-bd82566218b1-0006
```

Any ideas what should I do to make the plugin work with remote Mesos? Is something wrong in my Jenkins configuration? Any help is appreciated.

**Comment by kkalin78** [comment]
Your Jenkins uses 127.0.0.1 while registering on Mesos. How do you start Jenkins? What IP address it uses to bind?

**Comment by sbeaulie** [comment]
I have seen this issue before too, it seems like the mesos master uses an IP provided by the jenkins framework to connect back to it, instead of querying a DNS for the jenkins URL like normal systems do.

I had an entry of 127.0.1.1 in the `/etc/hosts` file of the **centos jenkins master** referring to its own FQDN and deleting that entry solved that issue!

I haven't looked at the code yet, but it is very strange that the framework would pass it's own 'resolved' IP for the mesos cluster to connect.

In your example I think you should use the IP of the machine instead of 'localhost' which is resolved to 127.0.0.1 and then passed to the mesos master.

**Comment by jeschkies** [comment]
@yarps95, did you get it to work with 1.0 or 2.0 of the plugin? I'm happy to help.

**Comment by jeschkies** [comment]
Closing for lack of response.
