### ISSUE TITLE
Spin up second slave with same label takes minutes

### ISSUE THREAD

**Issue by jwjanssen90** [jenkinsci/mesos-plugin#286]
I am struggling with a performance issue when I have configured a multijob pipeline.

The pipeline job and a subjob are using the same Docker image as slave. Performance wise it's desired to spin up two containers (one for the pipeline job and one for the subjob). What happened is that when the pipeline job is running, that Jenkins / Mesos plugin waits for up to 4 minutes before deciding to spin up the second container. Jenkins tries to reuse the container that is already running. While it only has 1 executor and all the jobs are configured with "Mesos Single-Use Slave".

It looks like that there is a timeout anywhere that will wait for a couple of minutes before deciding to spin up an extra container. 

Is there a way to set the timeout for this or can we solve the issue in a different way?

**Comment by maselvaraj** [comment]
Please see if 'Over provisioning flags'  in README helps you : https://github.com/jenkinsci/mesos-plugin/blob/master/README.md

**Comment by chr0n1x** [comment]
This recently started happening for me on version 0.15 and I *do* have those java opts in the running env.

Did anything change from 0.14 to 0.15 that may have caused this?

**Comment by sogajeffrey** [comment]
Ive added the over provisioning flag but it still shows the default jenkins behavior of waiting for one slave to finish. Any ideas?

**Comment by sbeaulie** [comment]
I also wonder if the 'Over provisioning flags' still works in 0.18+ and how to troubleshoot this issue.

**Comment by jeschkies** [comment]
The new 2.0 should be faster. This issue is the configuration of Jenkins itself. The plugin is fairly fast at launching a new agent. Do you know a cloud plugin that is faster? Maybe we could take over some of their configuration.
