### ISSUE TITLE
SSL/TLS Mesos Cluster via LIBPROCESS_SSL_*

### ISSUE THREAD

**Issue by chriskolenko** [jenkinsci/mesos-plugin#287]
Is there anyway to register a framework via SSL/TLS?

http://mesos.apache.org/documentation/latest/ssl/

Example of environment variables.
LIBPROCESS_SSL_ENABLED=true
LIBPROCESS_SSL_REQUIRE_CERT=true
LIBPROCESS_SSL_CA_FILE=path
LIBPROCESS_SSL_CERT_FILE=path
LIBPROCESS_SSL_KEY_FILE=path
LIBPROCESS_SSL_SUPPORT_DOWNGRADE=false
LIBPROCESS_SSL_VERIFY_IPADD=true
LIBPROCESS_SSL_VERIFY_CERT=true

**Comment by jeschkies** [comment]
Could you try 2.0. It does support anything that [Lightbend SSL Config](https://lightbend.github.io/ssl-config/) supports. You should be able to set CA files via the `application.conf` or Java properties. If you are interested you can describe your use case with an example and I write up a small guide.
