### ISSUE TITLE
Using Mesos pods for enhancing the capabilities of the Mesos plugin

### ISSUE THREAD

**Issue by jlrigau** [jenkinsci/mesos-plugin#288]
By using Mesos pods, it should be possible to implement new capabilities for the Mesos plugin like being able to use any Docker image as slave template and having the possibility to add side-containers to a build.

For using any Docker image as slave template, a pod with a Jenkins slave template linked to a build container should be created. The Jenkins slave manage the communication with the master and the build container is used for building using an ephemeral volume.

For side-containers we can consider to use the network capability for being able to access to the side container from `localhost`.

These kind of features are already available in [Jenkins Docker Slaves plugin](https://plugins.jenkins.io/docker-slaves) but without the ability to use an orchestrator like Mesos for running the containers.

**Comment by jeschkies** [comment]
2.0 uses task groups, aka pods, through [USI](https://github.com/mesosphere/usi) by default. I'm a little skeptical, though. What would side-containers or side-cars do in a build? I'm afraid this could be rather complex.

**Comment by jeschkies** [comment]
Closing for lack of response.
