### ISSUE TITLE
Mesos slaves fails intermittently

### ISSUE THREAD

**Issue by hbajaj2** [jenkinsci/mesos-plugin#289]
Hi, I keep on getting random failure from the mesos slaves and post restart everything works fine, I am using the latest version of mesos plugin with Jenkins and not able to get any useful information from the logs, can you kindly suggest how to go about solving this issue.

I0407 18:03:35.087230 20112 fetcher.cpp:498] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/ac0cfc59-0733-4224-8179-01a6d5e0ed9f-S3\/jenkins2","items":[{"action":"BYPASS_CACHE","uri":{"executable":false,"extract":false,"value":"http:\/\/jenkins2.sandbox\/jenkins2\/jnlpJars\/slave.jar"}}],"sandbox_directory":"\/tmp\/mesos\/slaves\/ac0cfc59-0733-4224-8179-01a6d5e0ed9f-S3\/frameworks\/5356c3cb-4ef6-49fb-85cf-157f386c086a-0013\/executors\/mesos-jenkins-a9f1d5fdc5b447769c146c387d706c38-framework\/runs\/b3dd9ca6-7749-4fcd-94bd-aeb8e87eee80","user":"jenkins2"}
Fetcher could not execute `os::su()` for user 'jenkins2'
Failed to synchronize with agent (it's probably exited)

**Comment by jeschkies** [comment]
Hm, @hbajaj2, could you try again with 1.0 or 2.0 of the plugin and Mesos 1.7+?

**Comment by jeschkies** [comment]
Closing for lack of response.
