### ISSUE TITLE
Support Mesos maintenance primitives in the Jenkins Mesos Framework

### ISSUE THREAD

**Issue by sjcollin** [jenkinsci/mesos-plugin#290]
Need to be able to drain/disable Mesos agents for maintenance.

I'm assuming that the mesos-plugin doesn't support this feature 
http://mesos.apache.org/documentation/latest/maintenance/
as I have tried to use and it never drained/stopped new Jenkins slave nodes from being created on a Mesos agent.
Thanks!

**Comment by sbeaulie** [comment]
I think this should resolve your issue, but I have not tried it yet https://github.com/jenkinsci/mesos-plugin/pull/243

**Comment by jeschkies** [comment]
This should be an issues for [USI](https://github.com/mesosphere/usi). Would you mind reposting your request there?
