### ISSUE TITLE
Need some help for installation, jnlp can't connect

### ISSUE THREAD

**Issue by kopax** [jenkinsci/mesos-plugin#292]
I have followed the installation guide and I still encounter **issues getting jenkins slaves to connect to the master**.

My mesos slaves are all having a `jenkins` user. with  UID `1000`

`JAVA_HOME` is into mesos slave path as well. 

Version:
======

- mesos: **1.2.0-2.0.6**
- marathon: **1.4.3-1.0.649.ubuntu1604**
- jenkinsci/mesos-plugin: **0.14.1**

Cloud configuration:
================

![image](https://cloud.githubusercontent.com/assets/1866564/25833890/a1ab79be-349e-11e7-974e-82a386cbbf98.png)

In marathon I have the jenkins master instance running in bridge mode : 

![image](https://cloud.githubusercontent.com/assets/1866564/25833830/5ad5dd2c-349e-11e7-8099-ba2a8e070e16.png)

I have consul and HAproxy proxying `jenkins-2.service.consul.50000` 

![image](https://cloud.githubusercontent.com/assets/1866564/25833906/b91d3c68-349e-11e7-8da2-8754ed546d71.png)

I also have consul and HAproxy proxying jenkins master `http://jenkins-2.service.consul`

![image](https://cloud.githubusercontent.com/assets/1866564/25833948/0335ae16-349f-11e7-9a9c-25315b373a7d.png)

Expected result
============

Jenkins master should be able to run jenkins slave in mesos by it's own.

Result
=====

In Mesos, I have a LOT of framework running, is it normal ?

![image](https://cloud.githubusercontent.com/assets/1866564/25833736/b6ca355c-349d-11e7-8333-cf3a6be3e32a.png)

When I run a new task: 

![image](https://cloud.githubusercontent.com/assets/1866564/25833970/24e25d34-349f-11e7-8709-45a5d891c967.png)

The slave have difficulties to start

![image](https://cloud.githubusercontent.com/assets/1866564/25833990/409672a4-349f-11e7-8b3f-6fe171303c62.png)

It is offline : 

![image](https://cloud.githubusercontent.com/assets/1866564/25834000/4ee391c0-349f-11e7-81a1-3df638ab76d4.png)

If I login on a valid mesos slave, and as jenkins user, I start the jnlp agent manually: 

![image](https://cloud.githubusercontent.com/assets/1866564/25834070/bd1744ac-349f-11e7-9c26-d1e94f085f96.png)

It does work :  

![image](https://cloud.githubusercontent.com/assets/1866564/25834096/e74063b2-349f-11e7-85f1-8be2bc72afc7.png)

I also enabled `FINE` Loglevel on my jenkins master : 

https://pastebin.com/93C2qsYR

I noticed this : 

```
INFO: Accepted connection #18 from /172.16.0.2:48806
May 09, 2017 3:47:29 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
WARNING: Connection #18 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:213)

INFO: Accepted connection #19 from /172.16.0.2:49443
May 09, 2017 3:47:44 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
WARNING: Connection #19 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:213)

May 09, 2017 3:47:59 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #20 from /172.16.0.2:50088
May 09, 2017 3:47:59 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
WARNING: Connection #20 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:213)
```

While this is the log when I do it manually: 

```
May 09, 2017 5:34:11 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #81 from /172.16.0.3:58863
May 09, 2017 5:34:12 AM jenkins.security.ExceptionTranslationFilter doFilter
FINER: Chain processed normally
```

Apparently the error come from here : https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/TcpSlaveAgentListener.java#L213

I have tried to use the host port `50000` and remove HAproxy but it didn't change.

I rather not launch my jenkins slaves manually. Is there a way to get more logs or plugin flow explanation. 

- Why does it refuse to connect to the jenkins master at the beginning? 
- I have read about `LIBPROCESS_IP`, but since the command work fine, could this be related to my issue ? I think it is not.
- Why is the slave trying to connect on a different port than `50000` ?

Any help is much appreciated

**Comment by maselvaraj** [comment]
Can you please post the logs from mesos sandbox ?

**Comment by Ballwang** [comment]
i have same issue about ，always say my mesos offline~！somebody help？

**Comment by kopax** [comment]
@maselvaraj the whole pipeline is broken, I had to replace some build using gitlab-ci instead of jenkins. I will try to post some extra logs asap, but by memory, I don't think there is any mesos sandbox started.

**Comment by daxroc** [comment]
I'm seeing a very similar error out using the AWS ECS plugin with the jenkinsci/jnlp container and custom derivatives.  It seems to work intermittently, I'll need to kill off bad slaves and the next will succeed.

**Comment by kopax** [comment]
This leads our team to stop using jenkins completely. We are now using GitlabCI and we are more than satisfied. Our experience with jenkins was very disappointing, we don't think we are gonna ever fixed this so I am closing so far.
