### ISSUE TITLE
Launch slave agent provisioning before a scheduled build

### ISSUE THREAD

**Issue by sjcollin** [jenkinsci/mesos-plugin#296]
So that scheduled builds don't have to wait (sometimes up to two minutes+) for an agent to be created with docker container, allow for the launch of an agent X amount of time before builds that have known scheduled build times.

Thanks, great work on this plugin.

**Comment by jeschkies** [comment]
Hm, I think what we want is to reserved resources or we predict some kind of throughput. @sjcollin, do you think Jenkins could be configured to schedule agents ahead? I don't think this should be a special feature of this plugin.
