### ISSUE TITLE
Using an environment variable as part of a labels docker image

### ISSUE THREAD

**Issue by hibbert** [jenkinsci/mesos-plugin#301]
Hi,

Not sure if this is possible as maybe jenkins environment variables are just for use in jobs but will ask anyway. We have an environment variable DOCKER_REPO which holds the URL of our docker repo, we use this as part of our jenkins jobs, but as all our slaves come from there I was hoping we could use this variable as part of the docker image string in the mesos cloud slave docker image? Maybe this is possible with a fix? (Mesos Cloud > Advanced > Add > Fill out > Click Advanced > Select Use Docker Containerizer > Fill in docker image > Try using $DOCKER_REPO/image:tag > Launch a job using this label > Fails to pull image)

Thanks

**Comment by jeschkies** [comment]
@hibbert, thanks for the request. If I understood this correctly you mean the Jenkins master has the env var `DOCKER_REPO`. Is that right? Do you know other Jenkins plugins that support variables?

**Comment by jeschkies** [comment]
Closing for lack of response.
