### ISSUE TITLE
When using 'Docker Image Can Be Customized', plugin ignores mesos offer selection attributes

### ISSUE THREAD

**Issue by sjcollin** [jenkinsci/mesos-plugin#303]
When a mesos cloud has multiple nodes and some nodes ares setup with specific mesos offer selection attributes, the agents that are created by mesos no longer are restricted to just those nodes in the defined selection attributes when a docker image is provided in a job using the 'Docker Image Can Be Customized'

**Comment by danielmagnussons** [comment]
Anyone having any idea how to fix this?

**Comment by sxcoll2** [comment]
I had to revert back to 0.16 to resolve.   Must have been a bug that was introduced when that part of the code was refactored in 0.17.

**Comment by jeschkies** [comment]
@sjcollin and @danielmagnussons, did you try 1.0 of the plugin?

**Comment by jeschkies** [comment]
Closing for lack of response.
