### ISSUE TITLE
Is this plugin support mesos 1.4.1 and jenkins 2.89.2 ?

### ISSUE THREAD

**Issue by hbceylan** [jenkinsci/mesos-plugin#307]

**Comment by willylee** [comment]
We just upgraded our Mesos to 1.4.1-2.0.1 and the plugin stopped working, so I'm inclined to say, not yet. I did a jenkins update to 2.101 to see if that helped anything and that didn't help either.

**Comment by willylee** [comment]
I guess I could elaborate. Jenkins can register a Mesos framework, but I never get a node created in Jenkins, nor do I get any tasks to get sent to the framework. Tasks just sit in the queue.

**Comment by maselvaraj** [comment]
What does the logs from Mesos/Jenkins say ?

**Comment by willylee** [comment]
Which logs are you looking for? The Jenkins logs in Manage Jenkins through the UI seem to be lacking anything useful.

**Comment by willylee** [comment]
OK, a build that was restricted to run on the label "mesos" managed to get a task to launch, but looking at the mesos logs, it fails because it can't find java

`/bin/sh: java: not found`

Our plain vanilla mesos doesn't include much of a path since tasks don't run as login shells. I'll try to put some path info into the systemd service file to test this on cluster restart later this week

**Comment by willylee** [comment]
Clearly something odd is happening, but it's working now. Setting up the docker containerizer settings, saving them, and then removing them has restored this plugin to a working state.

**Comment by jeschkies** [comment]
@willylee, is the plugin working fine? Can I close this issue?

**Comment by willylee** [comment]
We ended up giving up on the plugin after it failed again shortly after this.

**Comment by jeschkies** [comment]
It's sad to hear this. If you don't mind me asking. What are you using now? What could we do some you'd come on board again? Tbh, I am not the biggest fan of this plugin but I know we can do much better.

**Comment by willylee** [comment]
We are currently running all our tasks on the jenkins box instead. We might be willing to look at this again, but we have other priorities.

**Comment by jeschkies** [comment]
Thanks for the feedback. If your Jenkins box is big enough this plugin might be too much overhead for now.
