### ISSUE TITLE
pipeline jobs fails after master restarts

### ISSUE THREAD

**Issue by kontact-chan** [jenkinsci/mesos-plugin#308]
A pipeline job after master restart fails to reconnect.
1 - Jenkins is loosing the slave
2 - Mesos shows it as a active empty framework

Here is the console log of my pipeline job, after master restart:
<snip>
pipeline
[Pipeline] {
[Pipeline] sleep
Sleeping for 4 min 10 sec
Resuming build at Tue Dec 19 19:21:13 PST 2017 after Jenkins restart
Waiting to resume part of sandbox ? test-mesos-pipeline # 2: ???
Waiting to resume part of sandbox ? test-mesos-pipeline # 2: There are no nodes with the label ?mesos-jenkins-a4ea24452e554a4bb79a32caedfd275f-mesospawplatform? 
<snip>

**Comment by jeschkies** [comment]
Do you have the issue with 1.0 or 2.0 of the plugin?

**Comment by jeschkies** [comment]
Closing for lack of response.
