### ISSUE TITLE
Incompatibility with Jenkins 2.11* and Mesos 1.2.0?

### ISSUE THREAD

**Issue by brianmisle** [jenkinsci/mesos-plugin#319]
I've been searching all over for a solution to my issue in which my Jenkins slave nodes register and immediately unregister in Mesos. Does the current plugin not support more recent versions of Jenkins/Mesos? Looking at all the tutorials, it seems like they were created for much older versions but I would imagine people are still using this plugin today.

I've attempted to downgrade to 2.103 which appears to be the last mentioned supported version; however, that version breaks my Jenkins config.

**Comment by vinodkone** [comment]
Can you paste the Jenkins master and Mesos master logs ?

**Comment by brianmisle** [comment]
Mesos logs:
`I0423 10:17:12.927397 23107 master.cpp:2737] Received SUBSCRIBE call 
for framework 'Jenkins Scheduler' at scheduler-5be6bf9c-7ebb-484e- 
80c4-f7e60b3400d6@127.0.1.1:33889
I0423 10:17:12.927868 23107 master.cpp:2813] Subscribing framework 
Jenkins Scheduler with checkpointing disabled and capabilities [  ]
E0423 10:17:12.928674 23110 process.cpp:2426] Failed to shutdown 
socket with fd 51: Transport endpoint is not connected
I0423 10:17:12.929549 23105 master.cpp:1381] Framework f3f7a58b-d7a5- 
4336-bc7e-69500d29c3ff-6973 (Jenkins Scheduler) at scheduler-5be6bf9c- 
7ebb-484e-80c4-f7e60b3400d6@127.0.1.1:33889 disconnected
I0423 10:17:12.929616 23105 master.cpp:3081] Deactivating framework 
f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973 (Jenkins Scheduler) at 
scheduler-5be6bf9c-7ebb-484e-80c4-f7e60b3400d6@127.0.1.1:33889
I0423 10:17:12.929649 23105 master.cpp:3058] Disconnecting framework 
f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973 (Jenkins Scheduler) at 
scheduler-5be6bf9c-7ebb-484e-80c4-f7e60b3400d6@127.0.1.1:33889
I0423 10:17:12.929675 23105 master.cpp:1396] Giving framework 
f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973 (Jenkins Scheduler) at 
scheduler-5be6bf9c-7ebb-484e-80c4-f7e60b3400d6@127.0.1.1:33889 0ns to 
failover
E0423 10:17:12.929584 23110 process.cpp:2426] Failed to shutdown 
socket with fd 51: Transport endpoint is not connected
I0423 10:17:12.928707 23108 hierarchical.cpp:286] Added framework 
f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973
I0423 10:17:12.930029 23108 hierarchical.cpp:415] Deactivated 
framework f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973
I0423 10:17:12.930209 23103 master.cpp:6832] Framework failover 
timeout, removing framework f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973 
(Jenkins Scheduler) at scheduler-5be6bf9c-7ebb-484e-80c4- 
f7e60b3400d6@127.0.1.1:33889
I0423 10:17:12.930279 23103 master.cpp:7717] Removing framework 
f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973 (Jenkins Scheduler) at 
scheduler-5be6bf9c-7ebb-484e-80c4-f7e60b3400d6@127.0.1.1:33889
I0423 10:17:12.933053 23108 hierarchical.cpp:362] Removed framework 
f3f7a58b-d7a5-4336-bc7e-69500d29c3ff-6973`

Jenkins logs:
`Apr 24, 2018 9:08:31 AM org.jenkinsci.plugins.mesos.Mesos getInstance
INFO: Adding a new cloud with unique cloud ID:  d761feab-44ad-47e2- 
aa54-aadc9e933cec
Apr 24, 2018 9:08:33 AM org.jenkinsci.plugins.mesos.MesosCloud 
restartMesos
INFO: Mesos master changed from 'null' to '10.0.x.x:5050'
Apr 24, 2018 9:08:33 AM org.jenkinsci.plugins.mesos.JenkinsScheduler 
<init>
INFO: JenkinsScheduler instantiated with jenkins http://10.0.x.x:8080 
and mesos 10.0.x.x:5050
Apr 24, 2018 9:08:34 AM org.jenkinsci.plugins.mesos.JenkinsScheduler 
init
INFO: Initializing the Mesos driver with options
Framework Name: Jenkins Scheduler
Principal: jenkins
Checkpointing: false
Apr 24, 2018 9:08:34 AM org.jenkinsci.plugins.mesos.MesosCloud 
provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining 
excess workload: 0 executors)
INFO: Started provisioning MesosCloud from MesosCloud with 1 
executors. Remaining excess workload: 0
I0424 09:08:34.068917 13193 sched.cpp:232] Version: 1.5.0
I0424 09:08:34.075914 13189 sched.cpp:336] New master detected at 
master@10.0.x.x:5050
I0424 09:08:34.076942 13189 sched.cpp:351] No credentials provided. 
Attempting to register without authentication
Apr 24, 2018 9:08:41 AM 
org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins- 
bdfb011dfa074c809dfd98535bec30db-mesos
INFO: MesosCloud provisioning successfully completed. We have now 3 
computer(s)
Apr 24, 2018 9:09:00 AM 
org.jenkinsci.plugins.mesos.MesosWorkspaceBrowser getWorkspace
INFO: Nodes went offline. Hence fetching it through master`

**Comment by vinodkone** [comment]
Looks like the networking between mesos master and jenkins scheduler is not
working. It's trying to send registration acknowledgement on 127.0.0.1
which presumably the scheduler is unable to listen on. Can you try setting
LIBPROCESS_IP to 10.0.x.x address in Jenkin's environment?

**Comment by brianmisle** [comment]
@vinodkone, can you explain how to set this property? Do I need to set it on the Jenkins Master or on the slave(s)?

**Comment by vinodkone** [comment]
Set it on the Jenkins master.

**Comment by brianmisle** [comment]
I'm not sure what did it, but I got a build to complete successfully.

- I replaced the 127.0.1.1 entry in my Jenkin's master /etc/hosts/ file with the actual IP
- I copied the libmesos.so file from Mesos Master to Jenkins master (there was a version mismatch)
- I set the LIBPROCESS_IP environment variable on my Jenkin's master to the Mesos Master IP
