### ISSUE TITLE
 Make it possible to disable Metrics healthcheck

### ISSUE THREAD

**Issue by Lucas-C** [jenkinsci/mesos-plugin#321]
Hi.

In our use infrastructure, we use the metrics plugin to provide a healthcheck for our instances, and we have tools relying on it to evaluate if the Jenkins instance is up.

We witnessed that sometimes this healthcheck is failing because the Mesos plugin indicates we have unmatched labels (_cf._ [MesosAdministrativeMonitor.java#L23](https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/java/org/jenkinsci/plugins/mesos/MesosAdministrativeMonitor.java#L23)).

Hence, we would like to make the metrics healtcheck exposed by this plugin optional, throuch a checkbox in the `/configure` page.

Is that OK for you ?

We submitted PR #320 that implements this.
It includes 5 unit tests and also fixes the current CI state (by correcting 3 minor Findbugs issues).

**Comment by jeschkies** [comment]
The PR landed 🙂
