### ISSUE TITLE
No Milestones found

### ISSUE THREAD

**Issue by qper** [jenkinsci/mesos-plugin#326]
Hi there

We are going through Jenkins infrastructure update, because of this we looking at Jenkins+Apache Mesos approach.

In this regard there is a question, do you plan to support mesos-plugin in a future?

Advance thanks

**Comment by maselvaraj** [comment]
Yes, we will support this plugin

**Comment by jeschkies** [comment]
@qper, I'm the new maintainer. Did you process with the update?

**Comment by qper** [comment]
Yes. Thx

**Comment by jeschkies** [comment]
Cool. How is it working for you? Would you be willing to try out the experimental 2.0 release?

**Comment by qper** [comment]
Everything is alright. Yes, I'll try

**Comment by jeschkies** [comment]
Cool thanks. Feel free to reopen this issue.
