### ISSUE TITLE
Mesos Leader Selection

### ISSUE THREAD

**Issue by JC1738** [jenkinsci/mesos-plugin#327]
This plugin is great, thank you!  I had a question about the mesos master:5050 link.  Currently everything works great once I enter one of the leaders, but it will all stop working if a new master is elected leader.  It starts working again once we change the host to the newly elected leader. 

I tried to use master:5050/redirect as the host but that didn’t work (didn’t expect it too, but figured that would be a nice feature?)

Thank you,
Jim

**Comment by geoffroyjabouley** [comment]
Hi
please see here: https://github.com/jenkinsci/mesos-plugin/issues/306
You have to use the zk:// url format to properly configure the plugin with a mesos cluster.

**Comment by JC1738** [comment]
@geoffroyjabouley Thanks, I tried to input as suggested and I it doesn't seem to work.  I see the following error in the jenkins logs.

Here is what is in plugin:

`zk://mesos1-qa-XXX.com:5050,mesos2-qa-XXX.com:5050,mesos3-qa-XXX.com:5050`

Here is logs:

`Failed to create a master detector for 'zk://mesos1-qa-XXX.com:5050,mesos2-qa-XXX.com:5050,mesos3-qa-XXX.com:5050': Expecting a (chroot) path for ZooKeeper ('/' is not supported)`

**Comment by geoffroyjabouley** [comment]
I have created a PR: #332
For now it is just documented in README.md, but probably updating the jelly file shall also be done. If i find some time i'll complete the PR
