### ISSUE TITLE
some unexpected exceptions in v0.17

### ISSUE THREAD

**Issue by chrisliu529** [jenkinsci/mesos-plugin#328]
Last week I upgraded mesos-plugin from v0.16 to v0.17 but I found the 'Jenkins Scheduler' framework stopped working from time to time so I had to downgrade to v0.16.

When the framework stopped working, it didn't accept or decline offers from some agents and "outstanding offers" from these agents could be found in the mesos web UI. If offers from all agents were stuck then no job could be built. In this case, I have to restart mesos master to get it fixed temporarily but this issue may appear again in one day or two.

I checked the logs and found a lot of error logs like 'SEVERE: Offer processing thread failed with exception: java.lang.NullPointerException' which I've never seen in v0.16.

Hope it helps and please let me know if more info is required.
Thanks.

**Comment by chrisliu529** [comment]
The same issue still remains in latest v0.18.1. I found some interesting logs: 
--------------------------------------------------------------------------------
Sep 26, 2018 9:28:43 PM org.jenkinsci.plugins.mesos.JenkinsScheduler processOffers
INFO: Processing 7 offers.
Sep 26, 2018 9:28:43 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$2 run
INFO: Started offer processing thread: mesos-offer-processor-167797f6-bce1-4605-b0d1-dd397bf10201-0007
Sep 26, 2018 9:28:43 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$2 run
SEVERE: Offer processing thread failed with exception: java.lang.NullPointerException
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.declineOffer(JenkinsScheduler.java:310)
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.declineShort(JenkinsScheduler.java:304)
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.processOffers(JenkinsScheduler.java:361)
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.access$500(JenkinsScheduler.java:52)
	at org.jenkinsci.plugins.mesos.JenkinsScheduler$2.run(JenkinsScheduler.java:427)
	at java.lang.Thread.run(Thread.java:748)

Sep 26, 2018 9:28:53 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-f971d36ea18c4d7e8faa3a86405d6336-docker
Sep 26, 2018 9:28:53 PM hudson.slaves.NodeProvisioner$2 run
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)
Sep 26, 2018 9:29:13 PM org.jenkinsci.plugins.mesos.JenkinsScheduler processOffers
INFO: Processing 0 offers.
--------------------------------------------------------------------------------

Hope it helps

**Comment by chrisliu529** [comment]
As this issue has been persistent from v0.17 (more than 2 months), I take sometime to look into it today. Please find the full analysis below:
1. it's an issue first appeared in v0.17 in which introduced a multi-threaded model to handle resource offers
2. the NullPointerException is reported by the **old** thread started by the previous JenkinsScheduler instance. When the previous framework disconnected from mesos master because 'On-demand framework registration' is set to 'yes', its 'driver' is set to null in JenkinsScheduler.java#167. However, when a new JenkinsScheduler is up for a newly issued build request, the resource offers will be pushed into a global queue which is being drained from both threads and if the old thread take all pending resource and try to decline one of them, it will reference the null 'driver' variable thus the exception above occurs!
3. When such an exception happens, there will be an outage of the Jenkins framework because the mesos master will hold the resource offered to jenkins framework for the old offer thread crashed when trying to answer but the new offer thread will be starved for no more incoming resource offer..

workaround:
Set 'On-demand framework registration' to 'no' to avoid the jenkins framework disconnecting from mesos master

fix suggestions:
1. back to single-threaded model by changing MesosImpl.java#18 from
`scheduler = new JenkinsScheduler(jenkinsMaster, mesosCloud, true);`
to
`scheduler = new JenkinsScheduler(jenkinsMaster, mesosCloud, false);`

or

2. make the offer thread exit when its associated scheduler stopped by changing JenkinsScheduler.java#426 from
`while (true) {`
to
`while (isRunning()) {`

**Comment by chrisliu529** [comment]
@maselvaraj @gabrielhartmann 
Can any of you kindly include this fix into next release? Or else the multi-thread model can hardly work with feature 'On-demand framework registration'. Thanks.

**Comment by gabrielhartmann** [comment]
@chrisliu529 Thank you for the investigation.  Just FYI, I no longer contribute to this project.

**Comment by schneidexe** [comment]
Still broken in 0.18.1 :/

**Comment by sbeaulie** [comment]
We hit this issue too, but 'On-demand framework registration' is already off

**Comment by chrisliu529** [comment]
> We hit this issue too, but 'On-demand framework registration' is already off

There are other several race conditions in task queue operations which has all been fixed in PR #338 . However, it's not merged yet. So I suggest you try [my own fork](https://github.com/chrisliu529/mesos-plugin) which has been in production for more than 6 months and this issue never re-appeared.

**Comment by jeschkies** [comment]
@chrisliu529, we closed your pull request because we didn't get any feedback. Feel free to reopen the PR 🙂
