### ISSUE TITLE
Jenkins Label expressions do not seem to work with mesos clouds

### ISSUE THREAD

**Issue by etrikp** [jenkinsci/mesos-plugin#329]
If there are two clouds defined in mesos-plugin, cloud1 and cloud2, that reference mesos nodes by attributes, referencing the clouds in an expression does not work

node('cloud1 || cloud2') {}

As far as I can tell from the code, it seems there is no parsing of label expressions, but not 100% sure.

**Comment by sxcoll2** [comment]
I have also been having issues for a few weeks now where the Selection Attributes not being honored.
I have confirmed that the selection attributes in the Jenkins/Mesos config is correct but the job is being launched on an node in the Mesos Cloud that does not have the attribute.   This is a significant issue for us and we'll be reviewing the plugin code.  The selection attributes are the same we have been using for over a year now and appears to have started with the latest release of the plugin.

**Comment by sxcoll2** [comment]
I have downgraded quite a few Jenkins to version 0.16 and it has resolved the issue but more time/load will tell.

**Comment by jeschkies** [comment]
@etrikp and @sxcoll2, could you try 1.0 or 2.0 of the plugin? We might have a regression here.

**Comment by jeschkies** [comment]
Closing for lack of response.
