### ISSUE TITLE
wrong description of parameter 'Decline offer duration'

### ISSUE THREAD

**Issue by chrisliu529** [jenkinsci/mesos-plugin#334]
It's said ' In milliseconds.' in current help description, however, according to implementation, it's actually in seconds. Therefore, the intended 10 minutes default value (600000) is actually nearly 7 days..

Surprisingly, this issue can hardly be noticed by users because all offers will be revived when a new build request comes. I won't notice it also if I didn't have a deep code reading to analyze issue https://github.com/jenkinsci/mesos-plugin/issues/328

**Comment by jeschkies** [comment]
Fixed in #344.
