### ISSUE TITLE
Framework should set a non-default failover_timeout

### ISSUE THREAD

**Issue by etrikp** [jenkinsci/mesos-plugin#335]
In its current state 0.18.1, the mesos plugin does not set the failover_timeout attribute when instantiating the FrameworkInfo class. This attribute is set to a non-production ready default that will cause HA implementations of mesos to kill (failover) the framework and all the tasks associated with it, if there are any small network interruptions.  Per the mesos docs, this timeout should be set to a week or more.

http://mesos.apache.org/documentation/latest/high-availability-framework-guide/#recommendations-for-highly-available-frameworks

Would be great to have this as a setting that can be changed from the Jenkins UI that has a default of 1 week.

**Comment by jeschkies** [comment]
The new plugin uses [Lightbend Config](https://github.com/lightbend/config) for its operational configuration. See the [application.conf](https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/resources/application.conf#L31). This allows an operator to override the timeout at startup. Would that work for you?

**Comment by jeschkies** [comment]
Closing for lack of response.
