### ISSUE TITLE
Propagation configuration in docker volume configuration 

### ISSUE THREAD

**Issue by mavaishn** [jenkinsci/mesos-plugin#336]
provide the configuration to specify Propagation option in configuration for volumes.

To access the autofs mount inside container we have to specify :shared (e.g. -v /net:/net:shared). But there is no configuration option to specify Propagation.

**Comment by jeschkies** [comment]
@mavaishn, you can configure volumes. Is that working for you or do you require more options?

**Comment by jeschkies** [comment]
Closing for lack of response.
