### ISSUE TITLE
On mesos-containerizer launch, sh: java: command not found ERROR

### ISSUE THREAD

**Issue by Amithahiriadaka** [jenkinsci/mesos-plugin#337]
Hi,

My default  JAVA PATH is not in  /usr/local/bin. I see below error. 

I  tried,setting JAVA PATH  at .bash_profile, .profile ,ssh/environment . Still I see the error. 

1106 02:58:23.242352 31479 fetcher.cpp:533] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch","items":[{"action":"BYPASS_CACHE","uri":{"executable":false,"extract":false,"value":"http:\/\/10.160.148.222:10999\/jenkins\/jnlpJars\/slave.jar"}}],"sandbox_directory":"\/u01\/AbacusInstallation\/AbacusPlatform\/mesos\/mesos-1.4.1\/mesos-slave\/slaves\/9dff6111-36d7-4793-9c1f-8d8bcbf77b0a-S13\/frameworks\/254eaf4e-d78a-4b86-b986-ed12904ae85b-0009\/executors\/mesos-jenkins-2ded81e8d70046d6aee9ca7b5186befe-coolastra\/runs\/b73d2689-4b33-43c5-9248-56857047d8e4"}
I1106 02:58:23.262466 31479 fetcher.cpp:444] Fetching URI 'http://10.160.148.222:10999/jenkins/jnlpJars/slave.jar'
I1106 02:58:23.262547 31479 fetcher.cpp:285] Fetching directly into the sandbox directory
I1106 02:58:23.262610 31479 fetcher.cpp:222] Fetching URI 'http://10.160.148.222:10999/jenkins/jnlpJars/slave.jar'
I1106 02:58:23.262668 31479 fetcher.cpp:165] Downloading resource from 'http://10.160.148.222:10999/jenkins/jnlpJars/slave.jar' to '/u01/AbacusInstallation/AbacusPlatform/mesos/mesos-1.4.1/mesos-slave/slaves/9dff6111-36d7-4793-9c1f-8d8bcbf77b0a-S13/frameworks/254eaf4e-d78a-4b86-b986-ed12904ae85b-0009/executors/mesos-jenkins-2ded81e8d70046d6aee9ca7b5186befe-coolastra/runs/b73d2689-4b33-43c5-9248-56857047d8e4/slave.jar'
I1106 02:58:23.307310 31479 fetcher.cpp:582] Fetched 'http://10.160.148.222:10999/jenkins/jnlpJars/slave.jar' to '/u01/AbacusInstallation/AbacusPlatform/mesos/mesos-1.4.1/mesos-slave/slaves/9dff6111-36d7-4793-9c1f-8d8bcbf77b0a-S13/frameworks/254eaf4e-d78a-4b86-b986-ed12904ae85b-0009/executors/mesos-jenkins-2ded81e8d70046d6aee9ca7b5186befe-coolastra/runs/b73d2689-4b33-43c5-9248-56857047d8e4/slave.jar'
I1106 02:58:23.567204 31528 exec.cpp:162] Version: 1.4.1
I1106 02:58:23.589823 31548 exec.cpp:237] Executor registered on agent 9dff6111-36d7-4793-9c1f-8d8bcbf77b0a-S13
I1106 02:58:23.594990 31546 executor.cpp:171] Received SUBSCRIBED event
I1106 02:58:23.596611 31546 executor.cpp:175] Subscribed executor on ausslabaap09.us.dell.com
I1106 02:58:23.596784 31546 executor.cpp:171] Received LAUNCH event
I1106 02:58:23.597014 31546 executor.cpp:633] Starting task mesos-jenkins-2ded81e8d70046d6aee9ca7b5186befe-coolastra
I1106 02:58:23.618700 31546 executor.cpp:477] Running '/u01/AbacusInstallation/AbacusPlatform/mesos/mesos-1.4.1/build/src/mesos-containerizer launch <POSSIBLY-SENSITIVE-DATA>'
I1106 02:58:23.622797 31546 executor.cpp:646] Forked command at 31551
sh: java: command not found
I1106 02:58:23.868088 31546 executor.cpp:925] Command exited with status 127 (pid: 31551)
I1106 02:58:24.871309 31550 process.cpp:1068] Failed to

**Comment by jeschkies** [comment]
Which Docker image did you use?

**Comment by jeschkies** [comment]
Closing for lack of response.
