### ISSUE TITLE
Support docker image usage with mesos containerizer

### ISSUE THREAD

**Issue by kamaradclimber** [jenkinsci/mesos-plugin#339]
This plugin support docker containerizer and mesos containerizer but does not seem to support using docker images with mesos containerizer.

**Comment by jeschkies** [comment]
You can set a custom Docker image:
<img width="858" alt="Screen Shot 2019-11-11 at 11 35 52" src="https://user-images.githubusercontent.com/2418440/68580829-7217c080-0477-11ea-8247-dad3a006463b.png">

Would that work for you?

**Comment by kamaradclimber** [comment]
Yes this feature was added after I created this issue. It can be closed
