### ISSUE TITLE
jenkins slave on mesos offline

### ISSUE THREAD

**Issue by jbinglei** [jenkinsci/mesos-plugin#355]
I use Jenkins ver. 2.9 and Mesos plugin ver. 0.11.0 at my local machine (with ubuntuOS). I have a simple job with mesos label. My configuration for Mesos plugin:
![image](https://user-images.githubusercontent.com/20805384/63219745-37212c00-c1ab-11e9-9bfd-d4ef739c391b.png)
![image](https://user-images.githubusercontent.com/20805384/63219747-42745780-c1ab-11e9-9e73-12eda991ecc6.png)
While from Jenkins page, it should slave is offline
![image](https://user-images.githubusercontent.com/20805384/63219769-ba428200-c1ab-11e9-8652-fc024ec9a462.png)
![image](https://user-images.githubusercontent.com/20805384/63219774-d3e3c980-c1ab-11e9-9d74-70f4facdde26.png)

**Comment by jeschkies** [comment]
@jbinglei, could you try 1.0 or 2.0 of the plugin?

**Comment by jeschkies** [comment]
Closing for lack of response.
