### ISSUE TITLE
Jenkins Agents do not successfully launch on Mesos

### ISSUE THREAD

**Issue by MHarris021** [jenkinsci/mesos-plugin#395]
When trying to use the Mesos Plugin to launch a simple `echo "Hello World"` Freestyle Build, the jenkins agents fail to properly execute the build. In the jenkins logs we are seeing the container exit with a status of 127.

In the Mesos Agent Sandbox logs we are seeing the following error:
` cat stderr I0427 14:20:49.582945 4852 fetcher.cpp:562] Fetcher Info: {"cache_directory":"/tmp/mesos/fetch/jenkins","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http://35.224.90.141:8080/jnlpJars/agent.jar"}}],"sandbox_directory":"/var/lib/mesos/slaves/ec724f43-53bb-4959-9e37-61e8f8d49ede-S0/frameworks/f6448124-ce57-4c5d-b53b-84f4ca6337a1/executors/jenkins-agent-mesos-fe414928-6553-4457-8025-f7bcd3498044/runs/846adf5c-1abb-4347-8b7c-5471d8672c27","stall_timeout":{"nanoseconds":60000000000},"user":"jenkins"}I0427 14:20:49.596081 4852 fetcher.cpp:459] Fetching URI 'http://35.224.90.141:8080/jnlpJars/agent.jar'I0427 14:20:49.596127 4852 fetcher.cpp:290] Fetching 'http://35.224.90.141:8080/jnlpJars/agent.jar' directly into the sandbox directoryI0427 14:20:49.596207 4852 fetcher.cpp:175] Downloading resource from 'http://35.224.90.141:8080/jnlpJars/agent.jar' to '/var/lib/mesos/slaves/ec724f43-53bb-4959-9e37-61e8f8d49ede-S0/frameworks/f6448124-ce57-4c5d-b53b-84f4ca6337a1/executors/jenkins-agent-mesos-fe414928-6553-4457-8025-f7bcd3498044/runs/846adf5c-1abb-4347-8b7c-5471d8672c27/agent.jar'I0427 14:20:49.620573 4852 fetcher.cpp:618] Fetched 'http://35.224.90.141:8080/jnlpJars/agent.jar' to '/var/lib/mesos/slaves/ec724f43-53bb-4959-9e37-61e8f8d49ede-S0/frameworks/f6448124-ce57-4c5d-b53b-84f4ca6337a1/executors/jenkins-agent-mesos-fe414928-6553-4457-8025-f7bcd3498044/runs/846adf5c-1abb-4347-8b7c-5471d8672c27/agent.jar'I0427 14:20:49.620627 4852 fetcher.cpp:623] Successfully fetched all URIs into '/var/lib/mesos/slaves/ec724f43-53bb-4959-9e37-61e8f8d49ede-S0/frameworks/f6448124-ce57-4c5d-b53b-84f4ca6337a1/executors/jenkins-agent-mesos-fe414928-6553-4457-8025-f7bcd3498044/runs/846adf5c-1abb-4347-8b7c-5471d8672c27'I0427 14:20:50.510594 4900 exec.cpp:164] Version: 1.9.0I0427 14:20:50.527103 4920 exec.cpp:237] Executor registered on agent ec724f43-53bb-4959-9e37-61e8f8d49ede-S0I0427 14:20:50.529095 4916 executor.cpp:130] Registered docker executor on mesos-agent2.c.ps-dev-201405.internalI0427 14:20:50.529680 4920 executor.cpp:186] Starting task jenkins-agent-mesos-fe414928-6553-4457-8025-f7bcd3498044WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap./usr/local/bin/jenkins-slave: line 33: /home/jenkins/java -DHUDSON_HOME=jenkins -server -Xmx32m -jar ${MESOS_SANDBOX-.}/agent.jar -noReconnect -secret f986b8ef0052a338be56e92a138aefcf234d5f58c3105ea30b763d6a076b420c -jnlpUrl http://35.224.90.141:8080/computer/jenkins-agent-mesos-fe414928-6553-4457-8025-f7bcd3498044/slave-agent.jnlp: No such file or directoryI0427 14:20:51.224097 4920 executor.cpp:752] Container exited with status 127I0427 14:20:52.226647 4922 process.cpp:935] Stopped the socket accept loop`

The agent.jar file is present in the same directory as this log file.

**Comment by jeschkies** [comment]
It seems the agent cannot start. The best way to start is to use the `mesosphere/jenkins-dind:0.8.0` image which provides a Docker daemon. This can then be used with the [agent { docker {} } declaration](https://www.jenkins.io/doc/book/pipeline/docker/).

If you want to use your own image you need to provide the JRE8 and define the `ETNRYPOINT` of the image with eg `/bin/bash`.

**Comment by jeschkies** [comment]
Ping @MHarris021 🙂

**Comment by MHarris021** [comment]
Ty @jeschkies ,

Would it be possible to include this information in the documentation?

**Comment by jeschkies** [comment]
@MHarris021, sure. Just to be sure. Were you able to build a custom Docker image?
