### ISSUE TITLE
Add ability to specify -jnlpUrl when running jenkins slave.

### ISSUE THREAD

**Issue by ktf** [jenkinsci/mesos-plugin#40]
We are evaluating jenkins + mesos for our CI system. I've a mesos cluster set up and a jenkins instance running with the plugin configured, but it does not work because jenkins is behind a SSO page and mesos fails with:

```
Failing to obtain https://URL-BEHIND-SSO/jenkins/computer/mesos-jenkins-bf496dbb-8921-4e0e-95d5-40d112189acd/slave-agent.jnlp
```

because it cannot authenticate. I could bypass the problem if I was able to specify my own -jnlpUrl and use the jenkins master backend url (which the slave can access), however I could not find any way to do specify it. Ideas?

**Comment by maselvaraj** [comment]
@ktf The recent plugin release(0.6.0) release includes a feature where you don't have to pass the -jnclpCredentials. It uses Jenkins secret(unique hex code for each slave name) for authentication. Please try that. I'm closing this issue. Thanks!
