### ISSUE TITLE
Have an option to only allow a slave to run one job and then terminate

### ISSUE THREAD

**Issue by jeid64** [jenkinsci/mesos-plugin#48]
Is it possible to have the Jenkins plugin only spin up a slave and use it for one run of a job and then kill the slave after the run is finished so that the slave only is used once? We're testing out the containerizer features and only want a container to live for one run of a job. I've seen this feature in other Jenkins plugins where the framework checks if a job has been run on a slave and if a job has run it kills the slave and spins up another one.

**Comment by barkerd427** [comment]
We are also investigating this use-case. The overhead isn't necessarily that substantial as we currently have to wait on other jobs to finish. Not sure if there's a timeout I can adjust so a new slave is provisioned for every build almost immediately if there are resources. I thought if I adjusted the idle time to 0 that might cause the slave to die immediately, but that probably isn't true if there's a queue waiting on the executor.

It looks like JClouds gets the build information and on tearDown they set the slave to offline. I'm not sure how long it takes them to get those slaves cleaned up so the resources become available again. I'm assuming they leave it connected to finish transferring any information, but this isn't clear. It looks like they use this for cleanup: https://github.com/jenkinsci/jclouds-plugin/blob/master/jclouds-plugin/src/main/java/jenkins/plugins/jclouds/compute/JCloudsCleanupThread.java

**Comment by vinodkone** [comment]
I would love to have this feature merged in. @barkerd427 any chance you can send a PR for this?

**Comment by barkerd427** [comment]
I haven't gotten to this yet. I plan to move back to it, but it hasn't become pressing enough to make it back to the top of my priority queue. I am using a workaround [1] that has helped alleviate some of the issues, but I think this would be a better solution. I just need to make time to write it.

[1] https://groups.google.com/forum/#!topic/jenkins-mesos/b9DkLIpknCc

**Comment by wharfedale01** [comment]
I'm running against the same issue. I'm running a quine with 50 languages (https://github.com/mame/quine-relay/tree/50). Every language is a job in jenkins. But sometimes a job will be executed in the same Docker container.
@barkerd427 Do you know the best settings for MARGIN and MARGIN0? Site [1] suggest -MARGIN=50 
and MARGIN0=0.85

[1] http://operations-center.cloudbees.com/docs/operations-center/_configuring_a_jenkins_enterprise_14_11_client_master.html

**Comment by barkerd427** [comment]
Those are the settings I'm currently using. I'm waiting on more VM's and
time to test more settings as restarting our instance can only be done
occasionally as it serves so many people. The settings you posted have
helped a lot. The initial slave spins up reliably under 30 seconds now, and
subsequent slaves that used to take 5 minutes sometimes now spin up
reliably under 2 minutes. You'll still have the problem of subsequent
builds starting on slaves that are still up but with nothing running on
them. The best solution for that is to add something to each job that
allows for a unique label. I still haven't had time to look into this.

**Comment by stephenliang** [comment]
I made a pull request that supports this feature. From my testing, it is working fairly well but I am open to comments on the pull request.
