### ISSUE TITLE
jenkins framework  not registering

### ISSUE THREAD

**Issue by suchisubhra** [jenkinsci/mesos-plugin#63]
I installed jenkins and then added mesos plugin...I am using thre mesos master  and 4 slaves.
Using zookeeper.

getting logs from  master
I1009 16:36:55.259125 32062 master.cpp:1315] Received registration request from scheduler-a5db5a5f-9c35-4ce1-b7a9-22f5931b250c@127.0.0.1:47216
I1009 16:36:55.259404 32062 master.cpp:1374] Registering framework 20141009-134452-471669258-5050-32035-0085 at scheduler-a5db5a5f-9c35-4ce1-b7a9-22f5931b250c@127.0.0.1:47216
I1009 16:36:55.259742 32062 hierarchical_allocator_process.hpp:329] Added framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.260838 32062 master.cpp:3559] Sending 3 offers to framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.261261 32062 master.cpp:725] Framework 20141009-134452-471669258-5050-32035-0085 disconnected
I1009 16:36:55.261462 32062 master.cpp:1655] Deactivating framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.261652 32060 hierarchical_allocator_process.hpp:405] Deactivated framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.261884 32060 hierarchical_allocator_process.hpp:563] Recovered cpus(_):2; mem(_):2808; disk(_):23412; ports(_):[31000-32000](total allocatable: cpus%28*%29:2; mem%28*%29:2808; disk%28*%29:23412; ports%28*%29:[31000-32000]) on slave 20141002-012013-471669258-5050-32411-0 from framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.262166 32060 hierarchical_allocator_process.hpp:563] Recovered cpus(_):2; mem(_):2808; disk(_):23412; ports(_):[31000-32000](total allocatable: cpus%28*%29:2; mem%28*%29:2808; disk%28*%29:23412; ports%28*%29:[31000-32000]) on slave 20141001-151543-471669258-5050-26236-0 from framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.262220 32062 master.cpp:747] Giving framework 20141009-134452-471669258-5050-32035-0085 0ns to failover
I1009 16:36:55.262444 32060 hierarchical_allocator_process.hpp:563] Recovered cpus(_):2; mem(_):2808; disk(_):23412; ports(_):[31000-32000](total allocatable: cpus%28*%29:2; mem%28*%29:2808; disk%28*%29:23412; ports%28*%29:[31000-32000]) on slave 20141002-012009-488446474-5050-19698-2 from framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.262681 32064 master.cpp:3439] Framework failover timeout, removing framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.262810 32064 master.cpp:3935] Removing framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.263146 32064 hierarchical_allocator_process.hpp:360] Removed framework 20141009-134452-471669258-5050-32035-0085
I1009 16:36:55.389073 32060 master.cpp:3559] Sending 2 offers to framework 20141009-134452-471669258-5050-32035-0000
I1009 16:36:55.391134 32063 master.cpp:2169] Processing reply for offers: [ 20141009-134452-471669258-5050-32035-5083 ] on slave 20141002-012013-471669258-5050-32411-0 at slave(1)@10.26.29.32:5051 (ecprasvmpsjk03) for framework 20141009-134452-471669258-5050-32035-0000
I1009 16:36:55.391527 32063 master.cpp:2169] Processing reply for offers: [ 20141009-134452-471669258-5050-32035-5084 ] on slave 20141001-151543-471669258-5050-26236-0 at slave(1)@10.26.29.29:5051 (ecprasvmpsjk02) for framework 20141009-134452-471669258-5050-32035-0000
I1009 16:36:55.392098 32067 hierarchical_allocator_process.hpp:563] Recovered cpus(_):2; mem(_):2808; disk(_):23412; ports(_):[31000-32000](total allocatable: cpus%28*%29:2; mem%28*%29:2808; disk%28*%29:23412; ports%28*%29:[31000-32000]) on slave 20141002-012013-471669258-5050-32411-0 from framework 20141009-134452-471669258-5050-32035-0000
I1009 16:36:55.392382 32067 hierarchical_allocator_process.hpp:563] Recovered cpus(_):2; mem(_):2808; disk(_):23412; ports(_):[31000-32000](total allocatable: cpus%28*%29:2; mem%28*%29:2808; disk%28*%29:23412; ports%28*%29:[31000-32000]) on slave 20141001-151543-471669258-5050-26236-0 from framework 20141009-134452-471669258-5050-32035-0000

On slaves I am seeing this 
I1009 13:49:49.962013 32110 slave.cpp:1406] Asked to shut down framework 20141009-134452-471669258-5050-32035-0001 by master@10.26.29.28:5050
W1009 13:49:49.962136 32110 slave.cpp:1421] Cannot shut down unknown framework 20141009-134452-471669258-5050-32035-0001
I1009 13:49:50.960909 32110 slave.cpp:1406] Asked to shut down framework 20141009-134452-471669258-5050-32035-0002 by master@10.26.29.28:5050
W1009 13:49:50.960960 32110 slave.cpp:1421] Cannot shut down unknown framework 20141009-134452-471669258-5050-32035-0002
I1009 13:49:51.958961 32110 slave.cpp:1406] Asked to shut down framework 20141009-134452-471669258-5050-32035-0003 by master@10.26.29.28:5050
W1009 13:49:51.959012 32110 slave.cpp:1421] Cannot shut down unknown framework 20141009-134452-471669258-5050-32035-0003
I1009 13:49:52.959492 32110 slave.cpp:1406] Asked to shut down framework 20141009-134452-471669258-5050-32035-0004 by master@10.26.29.28:5050
W1009 13:49:52.959540 32110 slave.cpp:1421] Cannot shut down unknown framework 20141009-134452-471669258-5050-32035-0004
I1009 13:49:53.960479 32110 slave.cpp:1406] Asked to shut down framework 20141009-134452-471669258-5050-32035-0005 by master@10.26.29.28:5050
W1009 13:49:5

In mesos webeb page i am seeing this

Terminated Frameworks
ID  Host    User    Name    Registered  Unregistered
…5050-32035-0102  ecprasvmpsjk03.adsksaas.local   jenkins     JenkinsMaster   5 minutes ago   5 minutes ago
…5050-32035-0101  ecprasvmpsjk03.adsksaas.local   jenkins     JenkinsMaster   5 minutes ago   5 minutes ago
…5050-32035-0100  ecprasvmpsjk03.adsksaas.local   jenkins     JenkinsMaster   5 minutes ago   5 minutes ago
…5050-32035-0099  ecprasvmpsjk03.adsksaas.local   jenkins     JenkinsMaster   6 minutes ago   6 minutes ago
…5050-32035-0098  ecprasvmpsjk03.adsksaas.local   jenkins     JenkinsMaster   6 minutes ago   6 minutes ago

I did set up LIBPROCESS_IP..no change..any help  will be great.. I am stuck

**Comment by montells** [comment]
I am trying to use mesos-plugin. I am receiving same issue. After export LIBPROCESS_IP and comment my hostname in /etc/hosts and then jenkins not start showing following error:

**sudo service jenkins start ;  tailf /var/log/jenkins/jenkins.log**

    sudo: unable to resolve host jenkins-server
     * Starting Jenkins Continuous Integration Server jenkins                                                                                               [ OK ] 
    I0106 10:02:20.597182 22363 sched.cpp:234] New master detected at master@172.23.0.76:5050
    I0106 10:02:20.606560 22363 sched.cpp:242] No credentials provided. Attempting to register without authentication
    Jan 06, 2015 10:02:20 AM org.jenkinsci.main.modules.sshd.SSHD start
    INFO: Started SSHD at port 45750
    Jan 06, 2015 10:02:20 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Completed initialization
    Jan 06, 2015 10:02:20 AM hudson.WebAppMain$3 run
    INFO: Jenkins is fully up and running
    Jan 06, 2015 10:03:33 AM winstone.Logger logInternal
    INFO: JVM is terminating. Shutting down Winstone

    Running from: /usr/share/jenkins/jenkins.war
    Jan 06, 2015 10:05:51 AM winstone.Logger logInternal
    INFO: Beginning extraction from war file
    Jan 06, 2015 10:05:51 AM org.eclipse.jetty.util.log.JavaUtilLog info
    INFO: jetty-winstone-2.8
    Jan 06, 2015 10:05:53 AM org.eclipse.jetty.util.log.JavaUtilLog info
    INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
    Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
    Jan 06, 2015 10:05:54 AM org.eclipse.jetty.util.log.JavaUtilLog info
    INFO: Started SelectChannelConnector@0.0.0.0:8080
    Jan 06, 2015 10:05:54 AM winstone.Logger logInternal
    INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
    Jan 06, 2015 10:05:55 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Started initialization
    Jan 06, 2015 10:05:55 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Listed all plugins
    Jan 06, 2015 10:05:55 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Prepared all plugins
    Jan 06, 2015 10:05:55 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Started all plugins
    Jan 06, 2015 10:05:55 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Augmented all extensions
    Jan 06, 2015 10:05:57 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Loaded all jobs
    Jan 06, 2015 10:05:58 AM org.jenkinsci.plugins.mesos.MesosCloud restartMesos
    INFO: Mesos master changed, restarting the scheduler
    Jan 06, 2015 10:05:58 AM org.jenkinsci.plugins.mesos.JenkinsScheduler <init>
    INFO: JenkinsScheduler instantiated with jenkins http://localhost:8080/ and mesos mesos.mydomain:5050
    Jan 06, 2015 10:05:58 AM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
    INFO: Initializing the Mesos driver with options
    User: 
    Framework Name: Jenkins Scheduler
    Checkpointing: false
    Jan 06, 2015 10:05:59 AM org.jenkinsci.main.modules.sshd.SSHD start
    INFO: Started SSHD at port 45169
    Jan 06, 2015 10:05:59 AM jenkins.InitReactorRunner$1 onAttained
    INFO: Completed initialization
    Jan 06, 2015 10:05:59 AM javax.jmdns.impl.HostInfo newHostInfo
    WARNING: Could not intialize the host network interface on nullbecause of an error: jenkins-server: jenkins-server: Name or service not known
    java.net.UnknownHostException: jenkins-server: jenkins-server: Name or service not known
    	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
    	at javax.jmdns.impl.HostInfo.newHostInfo(HostInfo.java:75)
    	at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:407)
    	at javax.jmdns.JmDNS.create(JmDNS.java:60)
    	at hudson.DNSMultiCast$1.call(DNSMultiCast.java:32)
    	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.net.UnknownHostException: jenkins-server: Name or service not known
    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
    	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
    	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
    	... 9 more
    
    Jan 06, 2015 10:05:59 AM hudson.WebAppMain$3 run
    INFO: Jenkins is fully up and running
    WARNING: Logging before InitGoogleLogging() is written to STDERR
    F0106 10:06:14.010785 22708 process.cpp:1561] Failed to initialize, gethostbyname2: Host name lookup failure
    *** Check failure stack trace: ***

**Comment by vinodkone** [comment]
It looks like the server is not able to connect to 172.23.0.76 address. Has this issue been resolved?
