### ISSUE TITLE
Slaves are failing to launch

### ISSUE THREAD

**Issue by webdev** [jenkinsci/mesos-plugin#64]
Slaves are failing to launch and result in "This node is offline because Jenkins failed to launch the slave agent on it" error messages. 

I can see that Jenkins Scheduler gets registered in the Mesos UI in the frameworks section, and I can see that the tasks are getting queued up, but the slaves are not coming up to process them

```
mesos-jenkins-90af3c3c-6476-473c-8287-0bce0e3e7b12  task mesos-jenkins-90af3c3c-6476-473c-8287-0bce0e3e7b12 RUNNING just now    06c11b1b5059    Sandbox
mesos-jenkins-e49c7467-c8fe-4cdb-861f-4b697292687c  task mesos-jenkins-e49c7467-c8fe-4cdb-861f-4b697292687c RUNNING just now    06c11b1b5059    Sandbox
mesos-jenkins-07ec33d0-dec5-43d4-b43a-3c20f6c63fc6  task mesos-jenkins-07ec33d0-dec5-43d4-b43a-3c20f6c63fc6 RUNNING 2 minutes ago   06c11b1b5059    Sandbox
jenkins-master.36618937-5500-11e4-b3c1-d227cdd4be17 jenkins-master.36618937-5500-11e4-b3c1-d227cdd4be17 RUNNING 12 minutes ago  06c11b1b5059    Sandbox
busybox.adaa2575-54ff-11e4-b3c1-d227cdd4be17    busybox.adaa2575-54ff-11e4-b3c1-d227cdd4be17    RUNNING 16 minutes ago  06c11b1b5059    Sandbox
```

How can I go about debugging it? I'm not seeing any errors on mesos slave or master.

Thanks.

Google Hangout would be AMAZINGLY appreciated!

**Comment by zkay** [comment]
@benhardy did you ever get this working? I am having the same issue, it just spins and spins trying to start a slave and never does.

**Comment by vidyajothiraman** [comment]
Hi
I am facing similar issues in my setup. I have started a new issue at https://github.com/jenkinsci/mesos-plugin/issues/187

Can some one help me here as what mistake I am doing.
