### ISSUE TITLE
Maven build in Vagrant instance fails

### ISSUE THREAD

**Issue by hardieas** [jenkinsci/mesos-plugin#76]
Vagrant up and vagrant ssh work but running mvn hpi:run after ssh-ing to vagrant instance fails with this error:

[INFO] --- maven-hpi-plugin:1.95:run (default-cli) @ mesos ---
[INFO] Generating ./work/plugins/mesos.hpl
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.487s
[INFO] Finished at: Thu Jan 08 14:19:52 UTC 2015
[INFO] Final Memory: 20M/230M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:1.95:run (default-cli) on project mesos: Error preparing the manifest: ./work/plugins/mesos.hpl (No such file or directory) -> [Help 1]

**Comment by KostyaSha** [comment]
Please provide exact command and its result.
