### ISSUE TITLE
Jenkins Frameword registerd but Slave Jenkins not start

### ISSUE THREAD

**Issue by montells** [jenkinsci/mesos-plugin#77]
I am using:

 - jenkins 1.595 
 - mesos jenkins plugin 0.5.0 
 - mesos 0.21.0

I have configured Cloud Mesos in jenkins. Jenkins framework is already registerd with description in mesos frameworks view like this:

Id: 5050-2830-29614

Host: My-PC

User: Jenkins

Name: Jenkins Scheduler

Active Tasks: 0

CPU: 1.7

Mem: 2.5 Gb

Max Share: 37442%

Registered: 33 minutes ago

Re-Registered: -

But Jenkins not show online slave and get this output
Starting mesos slave mesos-jenkins-d4dd533e-bed4-44bc-b0d9-8fc5474710bd

    HTTP ERROR 404
    
    Problem accessing /computer/mesos-jenkins-d4dd533e-bed4-44bc-b0d9-8fc5474710bd/logText/progressiveHtml. Reason:
    
        Not Found

and this log

    INFO: Enqueuing jenkins slave request
    Jan 13, 2015 10:18:57 AM hudson.model.DownloadService$Downloadable load
    INFO: Obtained the updated data file for hudson.tools.JDKInstaller
    Jan 13, 2015 10:20:12 AM org.jenkinsci.plugins.mesos.MesosRetentionStrategy check
    INFO: Disconnecting offline computer mesos-jenkins-d4dd533e-bed4-44bc-b0d9-8fc5474710bd
    Jan 13, 2015 10:20:12 AM org.jenkinsci.plugins.mesos.MesosSlave terminate
    INFO: Terminating slave mesos-jenkins-d4dd533e-bed4-44bc-b0d9-8fc5474710bd
    Jan 13, 2015 10:20:12 AM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
    INFO: Terminating jenkins slave mesos-jenkins-d4dd533e-bed4-44bc-b0d9-8fc5474710bd
    Jan 13, 2015 10:20:12 AM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
    INFO: Removing enqueued mesos task mesos-jenkins-d4dd533e-bed4-44bc-b0d9-8fc5474710bd
    Jan 13, 2015 10:21:24 AM hudson.model.UpdateSite updateData
    INFO: Obtained the latest update center data file for UpdateSource default

the log in mesos is this:

    I0113 10:07:13.690115  2851 master.cpp:1434] Framework 20150105-100316-1275074476-5050-2830-29614 (Jenkins Scheduler) at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612 already registered, resending acknowledgement
    I0113 10:07:14.690235  2854 master.cpp:1383] Received registration request for framework 'Jenkins Scheduler' at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612
    I0113 10:07:14.690510  2854 master.cpp:1434] Framework 20150105-100316-1275074476-5050-2830-29614 (Jenkins Scheduler) at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612 already registered, resending acknowledgement
    I0113 10:07:15.690466  2854 master.cpp:1383] Received registration request for framework 'Jenkins Scheduler' at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612
    I0113 10:07:15.690723  2854 master.cpp:1434] Framework 20150105-100316-1275074476-5050-2830-29614 (Jenkins Scheduler) at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612 already registered, resending acknowledgement
    I0113 10:07:16.691149  2852 master.cpp:1383] Received registration request for framework 'Jenkins Scheduler' at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612
    I0113 10:07:16.691689  2852 master.cpp:1434] Framework 20150105-100316-1275074476-5050-2830-29614 (Jenkins Scheduler) at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612 already registered, resending acknowledgement
    I0113 10:07:17.691560  2853 master.cpp:1383] Received registration request for framework 'Jenkins Scheduler' at scheduler-83e56c80-e586-4564-88cb-e0fd541ad845@172.23.0.76:58612

and so on...

also mesos show
Offered 	1.7 	2.5 GB  (the same resources of framework registered)

**Comment by jeremyjjbrown** [comment]
Me too. On 0.6.0-snapshot I think I'll try 0.4.0

**Comment by vinodkone** [comment]
Looks like Mesos master is not able to talk back to the Jenkins scheduler (even though the scheduler is able to talk back to the master). Make sure that 172.23.0.76:58612 is accessible from the master machine. Please reopen if that doesn't solve the issue.

**Comment by jeremyjjbrown** [comment]
In my case I had High port communication that was blocked.
