### ISSUE TITLE
mesos slave doesn't honor executor count

### ISSUE THREAD

**Issue by bacoboy** [jenkinsci/mesos-plugin#88]
No matter what number of executors I specify, I always get 1 on the actual dynamic slave.

Here you can see I have configured 20:
![configuration](https://cloud.githubusercontent.com/assets/874597/6381478/1bf31f5e-bd07-11e4-870b-0b0b02904722.png)

Once the slave launches, if you go to the configure screen, you can see it is set to 1, not the number I specified:
![1worker](https://cloud.githubusercontent.com/assets/874597/6381502/31b497aa-bd07-11e4-88de-92b25b6a6283.png)

**Comment by maselvaraj** [comment]
@bacoboy It is the behavior of Jenkins. Jenkins won't spawn 20 executors if there is only ONE build in queue. 
Also, say if you have configured 2 executors and there are 2 builds in queue, Jenkins won't immediately spawn 2 executor. It makes sure every executor it spawns is utilized to the maximum. Whole slave spawning logic is based on excess workload which is calculated with number of builds in queue, time spent in queue etc. 

If your use case is  to spawn slave immediately when a build gets into queue and not to wait for the previous executor to complete the build , then you can do that by passing these command line flags while start up of Jenkins: -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 . I use this in my setup. 

Please refer for more details: http://operations-center.cloudbees.com/docs/operations-center/_configuring_a_jenkins_enterprise_14_05_client_master.html#tutorial-over-provisioning

**Comment by bacoboy** [comment]
I opened this bug because I had multiple jobs waiting to run, but only 1 worker started in mesos.  I had hoped by setting this value higher, more mesos slaves/docker containers would launch.  When using docker on mesos, this would seem to be the preferred behavior (rather than having 1 slave running multiple jobs).  

Perhaps I'm not understanding why this setting exists - meaning where it is used.
If I set these overprovisioning flags, does that mean my value to 20 is now the upper limit?

I'll give this a try, but I wasn't the only person I spoke with that didn't understand why the jobs seem to be executed single threaded.  Maybe this should be documented in the plugin configuration?

**Comment by maselvaraj** [comment]
Yes. 20 would be the upper limit. 
Please let me know how it goes after adding the flags. 
I will document this in README file.

**Comment by bacoboy** [comment]
But that would seem to defeat the purpose of running it in mesos in the first place.  If I have 10 jobs, I want 10 docker containers each running 1 job each (and therefore 10 jenkins slaves with 1 executor).

How is this accomplished?

**Comment by maselvaraj** [comment]
It can be accomplished by configuring 'Maximum number of Executors per slave'  to 1.

**Comment by bacoboy** [comment]
OK so setting the max executors per slave in the mesos configuration does create separate instances of the builders as long as there are enough jobs to kick them off (when you have the overprovisioning set):

    -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85

So does this mean there is NO upper limit on the number of slaves that will be spun up (leaving it to mesos resource availability)?

**Comment by maselvaraj** [comment]
So does this mean there is NO upper limit on the number of slaves that will be spun up (leaving it to mesos resource availability)? - That's right

It also appears not more than 1 will start per jenkins job (say if the build is parameterized). Is this a jenkins limitation? - Yes

**Comment by bacoboy** [comment]
Would it make sense to set the default number of executors on docker slaves to be 1?

I guess that would depend on the situation.  Perhaps some documentation on executor counts and configuring the over-provisioning in the README to close this?

**Comment by maselvaraj** [comment]
@vinodkone I was also thinking it is worth to add over-provisioning flags to the README. Can you please let me know your thoughts?

**Comment by vinodkone** [comment]
@maselvaraj SGTM. More info in the README is always great. We could also add a blurb to the executor field itself in the src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-*.html.

**Comment by bacoboy** [comment]
Was the README updated with this information?  I didn't see a commit referenced on this ticket so perhaps it just wasn't tagged as such.

Thanks.

**Comment by maselvaraj** [comment]
@bacoboy Yes. https://github.com/jenkinsci/mesos-plugin/pull/142
