### ISSUE TITLE
using latest tag on docker images doesn't pull if newer version available

### ISSUE THREAD

**Issue by bacoboy** [jenkinsci/mesos-plugin#89]
If I specify ``foo:latest`` for my docker image, once cached on the physical mesos slave, it doesn't check the docker repository to see if ``latest`` has been moved.  I understand if this was a tag like ``1.2.4``, once you have it you don't really need to see if the tag moved, but the ``latest`` tag convention implies that it can change.  Similar to tags in git not moving, but branches can (and do)...

    % docker images 
    REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    aws-monkey               latest              9b10f680645c        6 days ago          997.6 MB
    aws-monkey               1.1.10              9b10f680645c        6 days ago          997.6 MB
    % sudo docker pull aws-monkey:latest
    Pulling repository aws-monkey
    aa4a631d838e: Download complete 
    511136ea3c5a: Download complete 
    5b12ef8fd570: Download complete 
    dade6cb4530a: Download complete 
    dacf258f4b0b: Download complete 
    d32f0d5e1a11: Download complete 
    c8fd68ec9481: Download complete 
    dfb5b387590d: Download complete 
    Status: Downloaded newer image for aws-monkey:latest
    % docker images                                  
    REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    aws-monkey               1.2.4               aa4a631d838e        25 hours ago        999.5 MB
    aws-monkey               latest              aa4a631d838e        25 hours ago        999.5 MB

Do we need a special case to do a ``docker pull foo:latest`` (which will check the repo for a newer version) prior to the ``docker run`` for the slave if the tag is ``latest`` (or maybe always)?

The thinking here is that I maintain a ``foo`` worker image and I always want to use the latest version.  So as I modify my build environment, the next jobs running will just pickup the change without me having to go explicitly change the version number in the jenkins master cloud configuration.

Thoughts?

**Comment by bacoboy** [comment]
This seems to be a more general docker problem.  See https://github.com/docker/docker/issues/10693

It would be nice to keep this open pending resolution of that 'feature'.  Then we can add a flag or checkbox to the plugin to decide if the ``--pull`` flag should be included in the launch of the docker container.

Thoughts?

**Comment by hekaldama** [comment]
This has to do with mesos afaik:

https://github.com/apache/mesos/blob/master/src/docker/docker.cpp#L797

has been released with Mesos v. 0.22.0 and should help you force pull docker tasks in mesos.

**Comment by bacoboy** [comment]
I was just looking at this the other day.  Yes, 0.22 seems to have the fixes and the flag addition has been added to the plugin as of the 0.8.0 release.

Thanks everybody!  Time to schedule a mesos upgrade...
