### ISSUE TITLE
HA Jenkins with Marathon/Mesos/Docker - - slaves stuck in infinite loop

### ISSUE THREAD

**Issue by zkay** [jenkinsci/mesos-plugin#90]
My issue is similar to #77 but different enough that I thought I should open a new one. I am having the same problem, my framework registers but the slaves are getting stuck in an infinite 'starting' loop. They always appear as offline, but when I browse to the node in jenkins it just says 'this node is starting...'.

My issue differs in that I'm deploying the jenkins-master to Mesos through Marathon, and the jenkins-master itself is containerized. All of this is running locally on boot2docker. To get the framework registering, I'm pointing the plugin at the mesos master through a Zookeeper path (zk://192.168.59.103:2181/mesos). I'm giving the jenkins url as the url passed back through Marathon - - generally http://192.168.59.103 + whatever random port it's assigned.

I tried taking the advice I found in several related issues about setting the IP on the jenkins-master's localhost through LIBPROCESS_IP and the marathon host:port to point directly at the b2d IP as well, but this didn't work for me:

```
Mar 05, 2015 11:40:38 PM org.jenkinsci.plugins.mesos.MesosCloud restartMesos
INFO: Mesos master changed, restarting the scheduler
Mar 05, 2015 11:40:38 PM org.jenkinsci.plugins.mesos.JenkinsScheduler <init>
INFO: JenkinsScheduler instantiated with jenkins http://192.168.59.103:31000/ and mesos 192.168.59.103:5050
Mar 05, 2015 11:40:38 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
INFO: Initializing the Mesos driver with options
Framework Name: Jenkins Scheduler
Principal: jenkins
Checkpointing: false
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0305 23:40:38.204964    88 process.cpp:1542] Failed to initialize, bind 192.168.59.103:0: Cannot assign requested address [99]
*** Check failure stack trace: ***
Aborted
```

This is what I get back if I just set jenkins url to the marathon slave's url and the mesos-master host:port to the zookeeper node, WITHOUT defining LIBPROCESS_IP at all:

```
INFO: JenkinsScheduler instantiated with jenkins http://192.168.59.103:31001/ and mesos zk://192.168.59.103:2181/mesos
I0305 22:56:35.673413   315 sched.cpp:752] Stopping framework ''
Mar 05, 2015 10:56:35 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
INFO: Initializing the Mesos driver with options
Framework Name: Jenkins Scheduler
Principal: jenkins
Checkpointing: false
2015-03-05 22:56:35,911:6(0x7f8e290d5700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-03-05 22:56:35,913:6(0x7f8e290d5700):ZOO_INFO@log_env@716: Client environment:host.name=4b2f4c00149d
2015-03-05 22:56:35,913:6(0x7f8e290d5700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-03-05 22:56:35,913:6(0x7f8e290d5700):ZOO_INFO@log_env@724: Client environment:os.arch=3.18.5-tinycore64
2015-03-05 22:56:35,913:6(0x7f8e290d5700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Sun Feb 1 06:02:30 UTC 2015
2015-03-05 22:56:35,913:6(0x7f8e290d5700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
I0305 22:56:35.921505   465 sched.cpp:137] Version: 0.21.1
2015-03-05 22:56:35,923:6(0x7f8e290d5700):ZOO_INFO@log_env@741: Client environment:user.home=/var/lib/jenkins
2015-03-05 22:56:35,923:6(0x7f8e290d5700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-03-05 22:56:35,923:6(0x7f8e290d5700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=192.168.59.103:2181 sessionTimeout=10000 watcher=0x7f8e2ae8e6a0 sessionId=0 sessionPasswd=<null> context=0x7f8e8c460680 flags=0
2015-03-05 22:56:35,929:6(0x7f8e246ca700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.59.103:2181]
2015-03-05 22:56:35,936:6(0x7f8e246ca700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.59.103:2181], sessionId=0x14bebe25434000b, negotiated timeout=10000
I0305 22:56:35.964292   315 group.cpp:313] Group process (group(2)@172.17.0.16:58941) connected to ZooKeeper
I0305 22:56:35.964365   315 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0305 22:56:35.964376   315 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I0305 22:56:36.074975   315 detector.cpp:138] Detected a new leader: (id='4')
I0305 22:56:36.075395   315 group.cpp:659] Trying to get '/mesos/info_0000000004' in ZooKeeper
I0305 22:56:36.083920   310 detector.cpp:433] A new leading master (UPID=master@172.17.0.9:5050) is detected
I0305 22:56:36.087827   314 sched.cpp:234] New master detected at master@172.17.0.9:5050
I0305 22:56:36.088454   314 sched.cpp:242] No credentials provided. Attempting to register without authentication
I0305 22:56:36.098711   314 sched.cpp:408] Framework registered with 20150305-214055-150999468-5050-1-0002
Mar 05, 2015 10:56:36 PM org.jenkinsci.plugins.mesos.JenkinsScheduler registered
INFO: Framework registered! ID = 20150305-214055-150999468-5050-1-0002
```

So that looks good, but if I give it a job:

![](http://img.ctrlv.in/img/15/03/06/54f921cca7bbf.png)

Then I see this in the logs:

```
Mar 05, 2015 10:56:41 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
Mar 05, 2015 10:56:41 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: 0
Mar 05, 2015 10:56:41 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
Mar 05, 2015 10:56:41 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 10:56:51 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 10:56:51 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 10:56:51 PM org.jenkinsci.plugins.mesos.JenkinsScheduler requestJenkinsSlave
INFO: Enqueuing jenkins slave request
Mar 05, 2015 10:56:51 PM hudson.slaves.NodeProvisioner update
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)
Mar 05, 2015 11:00:56 PM org.jenkinsci.plugins.mesos.MesosRetentionStrategy check
INFO: Disconnecting offline computer mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 11:00:56 PM org.jenkinsci.plugins.mesos.MesosSlave terminate
INFO: Terminating slave mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 11:00:56 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Terminating jenkins slave mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 11:00:56 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Removing enqueued mesos task mesos-jenkins-ca704034-7aac-4774-a5aa-a182277a7ce6
Mar 05, 2015 11:01:01 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
Mar 05, 2015 11:01:01 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: 0
Mar 05, 2015 11:01:01 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
Mar 05, 2015 11:01:01 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:01:11 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:01:11 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:01:11 PM org.jenkinsci.plugins.mesos.JenkinsScheduler requestJenkinsSlave
INFO: Enqueuing jenkins slave request
Mar 05, 2015 11:01:11 PM hudson.slaves.NodeProvisioner update
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)
2015-03-05 23:03:07,366:6(0x7f8e246ca700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 15ms
Mar 05, 2015 11:05:56 PM org.jenkinsci.plugins.mesos.MesosRetentionStrategy check
INFO: Disconnecting offline computer mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:05:56 PM org.jenkinsci.plugins.mesos.MesosSlave terminate
INFO: Terminating slave mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:05:56 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Terminating jenkins slave mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:05:56 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Removing enqueued mesos task mesos-jenkins-45e8a262-f649-4689-af6b-ae3332a10c70
Mar 05, 2015 11:06:01 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
Mar 05, 2015 11:06:01 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: 0
Mar 05, 2015 11:06:01 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
Mar 05, 2015 11:06:01 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:06:11 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:06:11 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:06:11 PM org.jenkinsci.plugins.mesos.JenkinsScheduler requestJenkinsSlave
INFO: Enqueuing jenkins slave request
Mar 05, 2015 11:06:11 PM hudson.slaves.NodeProvisioner update
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)
Mar 05, 2015 11:10:56 PM org.jenkinsci.plugins.mesos.MesosRetentionStrategy check
INFO: Disconnecting offline computer mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:10:56 PM org.jenkinsci.plugins.mesos.MesosSlave terminate
INFO: Terminating slave mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:10:56 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Terminating jenkins slave mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:10:56 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Removing enqueued mesos task mesos-jenkins-a9a3a7cf-df3d-4668-b065-bed1c4664227
Mar 05, 2015 11:11:01 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
Mar 05, 2015 11:11:01 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: 0
Mar 05, 2015 11:11:01 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
Mar 05, 2015 11:11:01 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-41564f87-bfce-42cb-9930-752ea3236def
Mar 05, 2015 11:11:11 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-41564f87-bfce-42cb-9930-752ea3236def
Mar 05, 2015 11:11:11 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-41564f87-bfce-42cb-9930-752ea3236def
Mar 05, 2015 11:11:11 PM org.jenkinsci.plugins.mesos.JenkinsScheduler requestJenkinsSlave
INFO: Enqueuing jenkins slave request
Mar 05, 2015 11:11:11 PM hudson.slaves.NodeProvisioner update
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)
```

This is on:

Jenkins 1.601
Jenkins-Mesos 0.8
Marathon 0.8.0
Mesos 0.21.1

**UPDATE**: So in messing with this today I managed to get some different behavior. Now, instead of only building up to 2 slaves, it's just continually building them until the last one times out, then killing them all and restarting the process (still in an infinite loop, the build never actually fails). My log is [here](https://gist.github.com/zkay/192c4a1f1a8cc1e389d0). 

![](http://img.ctrlv.in/img/15/03/06/54f9e1df33a33.png)

Some notes:

- The failed docker plugin loading was because I bundled the 0.9-SNAPSHOT version in my build. Pulling the newest available plugin from the Jenkins UI and restarting fixed it.
- I upgraded several other plugins as well, namely the SSH Slaves plugin to the newest available.
- I pointed the 'Docker Builder URL' to the daemon running in my b2d instance

**Comment by maselvaraj** [comment]
What does the Mesos log say?

**Comment by zkay** [comment]
@maselvaraj https://gist.github.com/zkay/330b4feb8a5360462457 Logs from the master and both mesos-slaves running on my local boot2docker

**Comment by maselvaraj** [comment]
thanks @zkay . Can you please post the sanbox logs as well? 
Mesos master URL -> Framwork - > Terminated Frameworks -> Failed task(if you see failed task) -> both stderr and stdout

**Comment by zkay** [comment]
@maselvaraj There isn't anything there, stderr/stdout is blank for every failed task. There is a list of failed tasks, though.

**Comment by maselvaraj** [comment]
Looking at this line https://gist.github.com/zkay/330b4feb8a5360462457#file-slave1-txt-L10 , I believe Mesos is not launched containerization option. 

Can you launch your Mesos slave with option  '–containerizers=docker,mesos' and try?

**Comment by zkay** [comment]
@maselvaraj With that defined, here are the new logs: https://gist.github.com/zkay/567d5bbe3395ed375d90

These are the environment variables the mesos slaves are being launched with

```
MESOS_CONTAINERIZERS: docker,mesos
MESOS_DOCKER_STOP_TIMEOUT: 10secs
MESOS_LOG_DIR: /var/log
MESOS_MASTER: zk://192.168.59.103:2181/mesos
MESOS_WORK_DIR: /mesos
MESOS_PORT: "5151"
DOCKER_HOST: 192.168.59.103:2375
```

**Comment by maselvaraj** [comment]
https://gist.github.com/zkay/567d5bbe3395ed375d90#file-mesos_slave1-txt-L7 - This is the issue now. 
Is Mesos slave process started as privileged super user ?  It needs to be a super user to make some changes in /tmp directory for hosting the logs. 
You can try two things: 

1. Start the slave process with a privileged user. 
2. Create a user 'jenkins' in the mesos slaves

**Comment by zkay** [comment]
@maselvaraj Okay, progress! Now in the stderr/stdout I get output for the tasks, but it says they're trying to connect on an unavailable port...?

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0307 15:49:56.488519   215 fetcher.cpp:76] Fetching URI 'http://192.168.59.103:31000/jnlpJars/slave.jar'
I0307 15:49:56.488649   215 fetcher.cpp:126] Downloading 'http://192.168.59.103:31000/jnlpJars/slave.jar' to '/mesos/slaves/20150307-154224-150999468-5050-1-S1/frameworks/20150307-154224-150999468-5050-1-0000/executors/mesos-jenkins-4ec63382-fb62-4509-b37f-955276cbe2d9/runs/4c03986c-27c1-4735-be15-b2bdd0c808ac/slave.jar'
I0307 15:49:56.505367   215 fetcher.cpp:255] Skipped extracting path '/mesos/slaves/20150307-154224-150999468-5050-1-S1/frameworks/20150307-154224-150999468-5050-1-0000/executors/mesos-jenkins-4ec63382-fb62-4509-b37f-955276cbe2d9/runs/4c03986c-27c1-4735-be15-b2bdd0c808ac/slave.jar'
I0307 15:49:56.583125   223 logging.cpp:172] INFO level logging started!
I0307 15:49:56.585185   223 exec.cpp:132] Version: 0.21.1
I0307 15:49:56.588206   230 exec.cpp:206] Executor registered on slave 20150307-154224-150999468-5050-1-S1
Mar 7, 2015 3:49:56 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: mesos-jenkins-4ec63382-fb62-4509-b37f-955276cbe2d9
Mar 7, 2015 3:49:57 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Mar 7, 2015 3:49:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://192.168.59.103:31000/]
Mar 7, 2015 3:49:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 192.168.59.103:46106
Mar 7, 2015 3:50:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 192.168.59.103:46106 (retrying:2)
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:385)
	at java.net.Socket.connect(Socket.java:546)
	at java.net.Socket.connect(Socket.java:495)
	at java.net.Socket.<init>(Socket.java:392)
	at java.net.Socket.<init>(Socket.java:206)
	at hudson.remoting.Engine.connect(Engine.java:353)
	at hudson.remoting.Engine.run(Engine.java:237)
```

**Comment by maselvaraj** [comment]
Good progress! I think this might be a firewall issue. Jenkins chooses a random port so that a slave can connect through JNLP. In the log you posted above it was port 46106 on which connection was refused. 
Can you please verify if your firewall settings block unknown ports?

**Comment by zkay** [comment]
@maselvaraj I don't think so? I'm not positive how it works under boot2docker. None of the traffic is going anywhere outside boot2docker for the moment, it's all contained within the boot2docker VM.

**Comment by maselvaraj** [comment]
Check your idle termination minutes in Jenkins -> Mesos cloud configuration and How long it takes for this message to be printed from the moment you see a slave launching state in Jenkins UI. 
Verify if a slave is still shown as 'launching' in Jenkins UI when this log message  is printed.
Try increasing idle termination minutes.

**Comment by zkay** [comment]
@maselvaraj They all stay at 'launching' until they reach the 5th attempt at retrying after receiving a timeout (because the slave can't start). This is what I see when I look at the list of nodes:

![](http://img.ctrlv.in/img/15/03/07/54fb8d4b5e164.png)

After they've reached the 5th time, that slave exits for a few seconds before spawning again and repeating the process over again. The log for each slave just goes on like so:

```
Mar 7, 2015 11:40:19 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 192.168.59.103:51422 (retrying:5)
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:385)
	at java.net.Socket.connect(Socket.java:546)
	at java.net.Socket.connect(Socket.java:495)
	at java.net.Socket.<init>(Socket.java:392)
	at java.net.Socket.<init>(Socket.java:206)
	at hudson.remoting.Engine.connect(Engine.java:353)
	at hudson.remoting.Engine.run(Engine.java:237)
Mar 7, 2015 11:40:29 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 192.168.59.103:51422 (retrying:6)
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:385)
	at java.net.Socket.connect(Socket.java:546)
	at java.net.Socket.connect(Socket.java:495)
	at java.net.Socket.<init>(Socket.java:392)
	at java.net.Socket.<init>(Socket.java:206)
	at hudson.remoting.Engine.connect(Engine.java:353)
	at hudson.remoting.Engine.run(Engine.java:237)
```

For X number of retries.

**Comment by maselvaraj** [comment]
@zkay  I'm not really sure what the issue is. Did you check the JDK version with which Jenkins was started and the JDK that docker container has?

**Comment by zkay** [comment]
@maselvaraj The mesos library was compiled on linux with openjdk 6, the same version within the container. So working backwards, what exactly is happening? Does something like this sound correct?

- An app (jenkins master) is deployed to mesos through marathon
- That app runs on a slave until the mesos cloud plugin is activated and configured to point at the mesos master, through zookeeper
- Once pointing at zookeeper, it registers itself as a framework within mesos
- Creating a job causes a task to be sent to the framework and then delegated out to a dynamically created mesos slave, which is itself running a docker image for the jenkins slave
- After creating the slave, it will try to SSH into the slave to start/monitor the job itself

This last step is the issue, right? How exactly does it assign that dynamically created slave an IP:Port? Is it something to do with SSH, perhaps?

**Comment by maselvaraj** [comment]
You're right except the last step. Communication between Jenkins slave and master is through JNLP and not SSH. Jenkins master when creating a slave, chooses a random port and starts listening in it. Slave(the process spawned by Mesos)later connects to that port using JNLP. Once the connection is established Jenkins slave comes online and it will start taking builds. The error message you see is the connection being refused while slave process tries to connect to the Jenkins master.

**Comment by zkay** [comment]
@maselvaraj A coworker helped me get this working, the final stumbling block had to do with domain name resolution - - I was using an IP where I should have used a domain name.

**Comment by jmiddleton** [comment]
Hi Zkay, 

I'm facing the same issue, my slave doesn't want to start. I have removed Docker from the picture and still Jenkins is not able to start the slave. I have configured one Virtualbox with Jenkins using mesos plugin 0.8.0-SNAPSHOT. The mesos server/slaves run in a different Virtualbox all with 0.22.1. All the servers are in a different network.

Could you explain how and where you configured DNS?  

This is the log from mesos master:
>I0629 12:13:41.640704  1689 master.cpp:3760] Sending 1 offers to framework 20150629-082622-184623020-5050-4371-0000 (Jenkins Scheduler) at scheduler-d79a1618-2fe6-4869-a4ab-99e752ccba3f@192.168.33.10:54838
I0629 12:13:41.643838  1691 master.cpp:2273] Processing ACCEPT call for offers: [ 20150629-120702-184623020-5050-1667-O225 ] on slave 20150629-120702-184623020-5050-1667-S1 at slave(1)@172.31.2.12:5051 (172.31.2.12) for framework 20150629-082622-184623020-5050-4371-0000 (Jenkins Scheduler) at scheduler-d79a1618-2fe6-4869-a4ab-99e752ccba3f@192.168.33.10:54838
I0629 12:13:42.642557  1684 master.cpp:3760] Sending 1 offers to framework 20150629-082622-184623020-5050-4371-0000 (Jenkins Scheduler) at scheduler-d79a1618-2fe6-4869-a4ab-99e752ccba3f@192.168.33.10:54838
I0629 12:13:42.645535  1689 master.cpp:2273] Processing ACCEPT call for offers: [ 20150629-120702-184623020-5050-1667-O226 ] on slave 20150629-120702-184623020-5050-1667-S0 at slave(1)@172.31.2.11:5051 (172.31.2.11) for framework 20150629-082622-184623020-5050-4371-0000 (Jenkins Scheduler) at scheduler-d79a1618-2fe6-4869-a4ab-99e752ccba3f@192.168.33.10:54838
I0629 12:13:46.649333  1689 master.cpp:3760] Sending 1 offers to framework 20150629-082622-184623020-5050-4371-0000 (Jenkins Scheduler) at scheduler-d79a1618-2fe6-4869-a4ab-99e752ccba3f@192.168.33.10:54838

and this one from Jenkins
>Jun 29, 2015 12:13:32 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
Jun 29, 2015 12:13:32 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: 0
Jun 29, 2015 12:13:32 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
Jun 29, 2015 12:13:32 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-321c58e7-55f3-466c-b5b0-5d223b279a83 from cloud 
Jun 29, 2015 12:13:42 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-321c58e7-55f3-466c-b5b0-5d223b279a83
Jun 29, 2015 12:13:42 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-321c58e7-55f3-466c-b5b0-5d223b279a83
Jun 29, 2015 12:13:42 PM org.jenkinsci.plugins.mesos.JenkinsScheduler requestJenkinsSlave
INFO: Enqueuing jenkins slave request
Jun 29, 2015 12:13:42 PM hudson.slaves.NodeProvisioner$2 run
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)

I appreciate any comment, suggestion.

Thanks,
Jorge

**Comment by jmiddleton** [comment]
Hi Zhay, I think I found the problem. In Jenkins I added a logger for mesos and I discovered that the offer from mesos (cpu and memory) was not enough for Jenkins. Jenkins was asking for more RAM than the one offered by mesos so after changed mesos-plugin config (Jenkins Slave Memory in MB and Maximum number of Executors per Slave) it worked.

The error was: `Offer not sufficient for slave request`. You can find more info [here](http://mail-archives.apache.org/mod_mbox/mesos-user/201502.mbox/%3C1422926283.21447.80.camel@bhepple.win2k.corp.tnsi.com%3E)

Thanks,
Jorge

**Comment by sdyrotronc** [comment]
I'm trying to launch jobs using Mesos parameters and encountering a similar issue, although it seems to work with no parameters being set. I just get TASK_FAILED errors after a TASK_RUNNING in Mesos, and the jobs endless enqueue after launching. Might it related to the IP issue that @zkay was having?

```
Apr 27 19:17:10 ip-10-5-0-8.us-west-2.compute.internal mesos-agent[14497]: I0427 19:17:10.662209 14505 slave.cpp:4256] Forwarding the update TASK_RUNNING (UUID: c984d336-6111-4ab3-9b97-cf8f9440b797) for task mesos-jenkins-dbc1edbc46054f5985d94f9664beb871-disk of framework 19db5b62-49d1-4825-9723-c433af96bc4e-0016 to master@10.5.4.234:5050
Apr 27 19:17:10 ip-10-5-0-8.us-west-2.compute.internal mesos-agent[14497]: I0427 19:17:10.662374 14505 slave.cpp:4166] Sending acknowledgement for status update TASK_RUNNING (UUID: c984d336-6111-4ab3-9b97-cf8f9440b797) for task mesos-jenkins-dbc1edbc46054f5985d94f9664beb871-disk of framework 19db5b62-49d1-4825-9723-c433af96bc4e-0016 to executor(1)@10.5.0.8:39061
Apr 27 19:17:10 ip-10-5-0-8.us-west-2.compute.internal mesos-agent[14497]: I0427 19:17:10.665318 14505 status_update_manager.cpp:395] Received status update acknowledgement (UUID: c984d336-6111-4ab3-9b97-cf8f9440b797) for task mesos-jenkins-dbc1edbc46054f5985d94f9664beb871-disk of framework 19db5b62-49d1-4825-9723-c433af96bc4e-0016
Apr 27 19:17:10 ip-10-5-0-8.us-west-2.compute.internal mesos-agent[14497]: I0427 19:17:10.665411 14505 status_update_manager.cpp:832] Checkpointing ACK for status update TASK_RUNNING (UUID: c984d336-6111-4ab3-9b97-cf8f9440b797) for task mesos-jenkins-dbc1edbc46054f5985d94f9664beb871-disk of framework 19db5b62-49d1-4825-9723-c433af96bc4e-0016
Apr 27 19:17:10 ip-10-5-0-8.us-west-2.compute.internal mesos-agent[14497]: I0427 19:17:10.842598 14502 slave.cpp:3816] Handling status update TASK_FAILED (UUID: 374fcfe8-a314-4d0c-8bfb-5f0e8dcc0337) for task mesos-jenkins-dbc1edbc46054f5985d94f9664beb871-disk of framework 19db5b62-49d1-4825-9723-c433af96bc4e-0016 from executor(1)@10.5.0.8:39061
Apr 27 19:17:10 ip-10-5-0-8.us-west-2.compute.internal mesos-agent[14497]: I0427 19:17:10.843530 14506 disk.cpp:207] Updating the disk resources for container a9901d6a-122b-4dad-ab57-84ff40093ce7 to cpus(*)(allocated: *):0.1; mem(*)(allocated: *):32
```
