### ISSUE TITLE
Error: Unable to access jarfile /mnt/mesos/sandbox/slave.jar

### ISSUE THREAD

**Issue by zkay** [jenkinsci/mesos-plugin#91]
I'm not really clear on why it can't access this file?

Here's the log from the mesos task:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0309 21:49:26.429782   763 fetcher.cpp:76] Fetching URI 'http://local.dev.com:9090/jnlpJars/slave.jar'
I0309 21:49:26.429904   763 fetcher.cpp:126] Downloading 'http://local.dev.com:9090/jnlpJars/slave.jar' to '/mesos/slaves/20150309-204509-1979716012-5050-1-S0/frameworks/20150309-204509-1979716012-5050-1-0001/executors/mesos-jenkins-ed480621-d778-4662-8bf9-30057830c7f9/runs/b34b6f83-8d4f-4512-8a89-e8f3fff954d5/slave.jar'
I0309 21:49:26.445976   763 fetcher.cpp:255] Skipped extracting path '/mesos/slaves/20150309-204509-1979716012-5050-1-S0/frameworks/20150309-204509-1979716012-5050-1-0001/executors/mesos-jenkins-ed480621-d778-4662-8bf9-30057830c7f9/runs/b34b6f83-8d4f-4512-8a89-e8f3fff954d5/slave.jar'
I0309 21:49:27.317360   781 logging.cpp:172] INFO level logging started!
I0309 21:49:27.322778   781 exec.cpp:132] Version: 0.21.1
I0309 21:49:27.358571   793 exec.cpp:206] Executor registered on slave 20150309-204509-1979716012-5050-1-S0
Error: Unable to access jarfile /mnt/mesos/sandbox/slave.jar
```

[Here](https://gist.github.com/zkay/b5f4b3c9e3937bf7ef73) are my jenkins-master and mesos-slave logs, along with output from ```docker diff```/```docker inspect``` being run on the container the slave tried to start. [Here](https://gist.github.com/zkay/d6a2f282d9fe39794ff4) is my terminal output from checking to see if the slave jar was present on the run, which it seems to have been.

In picture form:

![image](https://cloud.githubusercontent.com/assets/5808881/6580552/70020872-c71f-11e4-9d6c-87cd62b9d2c6.png)

Things I've tried:
 - Running all users as root (jenkins-master/jenkins-slave/mesos-slave)
 - Adding ```slave.jar``` to my jenkins-master image at the ```MESOS_SANDBOX``` path
 - Upgrading docker within all of my containers so that they're all the same version (1.5)
 - Adding a ```privileged: true``` parameter to the Mesos cloud docker containerizer UI

:confused:

**Comment by eghobo** [comment]
@zkay - do you see any errors in /var/log/docker.log. I also saw similar error with .20.1 when CentOS file limits are too low.

**Comment by zkay** [comment]
@eghobo We wound up switching from having mesos in docker to vagrant, that seemed to fix it. 
¯\_(ツ)_/¯

**Comment by zkay** [comment]
This was an issue with running Mesos(0.21.1) in Docker. Taking it out of containers and running it in vagrant seemed to fix the issue.

**Comment by mirosval** [comment]
This issue was the first search result for `Error: Unable to access jarfile /mnt/mesos/sandbox/slave.jar` so even though it is not strictly a Mesos or Mesos Plugin issue I will post my solution for other people who encounter this issue.

If you are running mesos slave inside a docker container, make sure the sandbox directory is volume mapped to the host:

```shell
docker run ... -v /var/lib/mesos/slave:/var/lib/mesos/slave ...
```

otherwise you'll see the slave.jar in the Mesos UI, but not in the actual directory `/mnt/mesos/sandbox` in your DIND container...
