### ISSUE TITLE
can't not create mesos node 

### ISSUE THREAD

**Issue by mk-qi** [jenkinsci/mesos-plugin#93]
i use mesosplugin with latest version.
See the following figure I can not enter any information in the next table,if a click save button, jenkins will restart automaticely 

![2015-03-18 10 49 31](https://cloud.githubusercontent.com/assets/642228/6701780/81e17af8-cd5c-11e4-82c8-abace420776d.png)

**Comment by maselvaraj** [comment]
@mk-qi I'm not sure why Jenkins gets restarted. But I see that you are trying to configure a new node manually. You don't have to do this when you use Jenkins Mesos plugin. Slaves will be spawned on demand, that is when there is a build in queue. All you need to do is configure Mesos master/ZK, required resources etc in Jenkins Global Config -> Add a new cloud -> Mesos cloud.

Please refer the documentation : https://github.com/jenkinsci/mesos-plugin  "Configuring the plugin" section for more details.

**Comment by mk-qi** [comment]
@maselvaraj thanks for reply I have read the configuration instructions and try it before, Just did not add jenkins users on slave machines. so i not not sure here is the problem.

And I've seen   jenkins framework is already registered on mesos webui, but  nothing 
 about jenkins  on mesos slave, so I thought I need  add it manually 

![2015-03-18 1 46 16](https://cloud.githubusercontent.com/assets/642228/6703341/3658c0be-cd75-11e4-89b1-d463b6d20d5f.png)

![2015-03-18 1 42 11](https://cloud.githubusercontent.com/assets/642228/6703302/9faa85a8-cd74-11e4-869c-9f22389e24f0.png)
![2015-03-18 1 42 52](https://cloud.githubusercontent.com/assets/642228/6703307/b571f8a8-cd74-11e4-9e71-aeb2a1530c7b.png)
![2015-03-18 1 43 24](https://cloud.githubusercontent.com/assets/642228/6703315/c5cc3204-cd74-11e4-810a-00bf6dbd9435.png)

i have no idea about next things  what should i do 
ps:
i buid jenkins  master   with marathon Command  like below

    git clone https://github.com/mk-qi/jenkins-standalone.git &&cd jenkins-standalone;sh jenkins-standalone.sh -z $(cat /etc/mesos/zk)

**Comment by maselvaraj** [comment]
@mk-qi 
Have you labelled your Jenkins job as 'mesos' ?

Just add the label name you have configured in Mesos cloud configuration -> Advanced -> Slave Info -> Label String (default is mesos) to the jobs (configure -> Restrict where this project can run checkbox) that you want to run on a specific slave type inside Mesos cluster.

**Comment by mk-qi** [comment]
@maselvaraj  Thanks for the help, I have tried as you say, it works for me, and  can i have different labes for sone nodes  as used to  specify a task  running on a specify  node in one mesos cluster?

**Comment by maselvaraj** [comment]
yes. You can have different labels with that you can have different flavors of slaves. Please refer "Adding Slave Info" in documentation. 

Can you please close this issue if it is resolved?
