### ISSUE TITLE
Only 1 Mesos cluster supported at a time

### ISSUE THREAD

**Issue by bacoboy** [jenkinsci/mesos-plugin#94]
I have 2 different mesos clusters (long story -- let's just say 'production' and 'pre-production').  I have configured both in the jenkins master under different 'Cloud' entries and created a slave for each (with different tags).  When I launch my job, both tagged jobs get launched on whichever cluster whose scheduler got launched first.

I looked at the code, and there appears to be a lazy instantiation of a single Mesos object here: https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/java/org/jenkinsci/plugins/mesos/Mesos.java#L89

What I was expecting was that a slave configuration tagged under the specific MesosCloud object would launch a different scheduler (and hence a different slave in that cluster).

Rather than assuming there is only 1 cluster in MesosComputerLauncher here: https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java#L58
can't we create a different Mesos object depending which.  It probably involves passing a reference to the  MesosCloud to the MesosSlave/MesosSlaveInfo????

Thoughts?

**Comment by vinodkone** [comment]
As you correctly diagnosed, currently the plugin only supports one Mesos Cloud at a time. But if connecting to multiple Mesos clusters from the same Jenkins master is a use case that you are interested in, we can think about adding that feature (PRs are welcome too :)). Is running multiple Jenkins masters, one for each Mesos cluster, not an option for you?

**Comment by bacoboy** [comment]
Already submitted pull request.  Please look it over...

**Comment by vinodkone** [comment]
Ah. I missed that PR. I will take a look. Thanks.
