### ISSUE TITLE
Set container hostname

### ISSUE THREAD

**Issue by lloydoliver** [jenkinsci/mesos-plugin#99]
I have successfully got the mesos plugin working with our mesos cluster, and it is able to create build slaves just fine. However I am trying to test some Saltstack states which require a hostname to be set for the tests to complete, adding `hostname` and `foobar01` into the parameters of the slave causes docker on mesos to bail out with -

```
exit status = exited with status 1 stderr = docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'
```

I've also tried adding a `net` parameter to the slave with a `bridge` value, however the plugin seems to have `--net host` hard coded with no override.
`--net host --net=bridge` appears in the docker run command.

Also with the hostname, I'd like to be able to use information from the job... for example hostname of `foobar-${BUILD_NUMBER}`or `${BUILD_TAG}` opposed to the hostname of the mesos slave (which breaks the state testing).

Is this already possible, and if so how? If not, is it something that could be added?

**Comment by geoffroyjabouley** [comment]
Hello

regarding bridged network, there is a pull request https://github.com/jenkinsci/mesos-plugin/pull/75
it may be included in the next release v0.7

regarding passing parameters to the docker container from the job, i don't think it is possible right now.
Maybe i am wrong, but i guess Jenkins creates new mesos computer/slave before reading the job configuration (except label), so the docker run command can not be override at job level.

**Comment by jeschkies** [comment]
@lloydoliver, could you try 1.0 or 2.0 of the plugin an see if it still works?

**Comment by jeschkies** [comment]
Closing for lack of response.
